/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ControleClientes_Fornecedores;
import Controle.Maiuscula;
import Controle.ModeloTabela;
import Controle.Validacoes;
import Controle.cadastro;
import Modelo.ModeloClientes_Fornecedores;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Murylo César Souza
 */
public class JIFCliente_fornecedor extends javax.swing.JInternalFrame {

    ConectaBanco conCli = new ConectaBanco();
    ConectaBanco conCid = new ConectaBanco();
    ModeloClientes_Fornecedores mod = new ModeloClientes_Fornecedores();
    ControleClientes_Fornecedores control = new ControleClientes_Fornecedores();
    Validacoes validar = new Validacoes();
    cadastro obj_config = new cadastro();
    MaskFormatter formatoData, formatoCNPJCPF, formatoCEP, Fone, jtTotalRecebido;

    int flag = 0;
    int Movimentacao;

    /**
     * Creates new form JIFCliente_fornecedor
     *
     * @param movimentacao
     */
    public JIFCliente_fornecedor(int movimentacao) {
        initComponents();
        obj_config.carregaconfig();
        conCli.Conexao(obj_config._url);
        conCid.Conexao(obj_config._url);
        PreencherCombo();
        preencherTabela("select * from tb_clientes_fornecedores order by id_cliente_fornecedor");
        jTxt_nome.setDocument(new Maiuscula(60));
        jTxt_endereco.setDocument(new Maiuscula(100));
        jTxt_numero.setDocument(new Maiuscula(10));
        jTxt_bairro.setDocument(new Maiuscula(40));
        jTxt_email.setDocument(new Maiuscula(100));
        jTxt_pesquisa.setDocument(new Maiuscula(60));
        Movimentacao = movimentacao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxt_codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        try{
            formatoData= new MaskFormatter("##/##/####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_datacad = new JFormattedTextField(formatoData);
        ;
        jLabel3 = new javax.swing.JLabel();
        jTxt_nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCbx_estcivil = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRBt_mas = new javax.swing.JRadioButton();
        jRBt_fem = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jTxt_endereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxt_numero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxt_bairro = new javax.swing.JTextField();
        try{
            formatoCEP= new MaskFormatter("##.###-###");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_cep = new JFormattedTextField(formatoCEP);
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCbx_cidade = new javax.swing.JComboBox();
        jTxt_pesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_cliente = new javax.swing.JTable();
        jBtt_novo = new javax.swing.JButton();
        jBtt_salvar = new javax.swing.JButton();
        jBtt_editar = new javax.swing.JButton();
        jBtt_excluir = new javax.swing.JButton();
        jBtt_cancelar = new javax.swing.JButton();
        jBtt_pesquisar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jRBt_fisica = new javax.swing.JRadioButton();
        jRBt_juridica = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTxt_email = new javax.swing.JTextField();
        jFTxt_cnpjcpf = new javax.swing.JFormattedTextField();
        jRBt_Cidades = new javax.swing.JButton();
        try{
            Fone= new MaskFormatter("(##) 9####-####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jTxt_fone = new JFormattedTextField(Fone);
        ;
        try{
            Fone= new MaskFormatter("(##) 9####-####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jTxt_fone2 = new JFormattedTextField(Fone);
        ;
        try{
            formatoData= new MaskFormatter("##/##/####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_datanac = new JFormattedTextField(formatoData);
        ;

        setClosable(true);
        setTitle("Cadastro de cliente e fornecedor");

        jLabel1.setText("Código");

        jTxt_codigo.setEnabled(false);

        jLabel2.setText("Data Cadastro");

        jFTxt_datacad.setEnabled(false);

        jLabel3.setText("Nome");

        jTxt_nome.setEnabled(false);

        jLabel4.setText("CPF");

        jLabel5.setText("Estado civil");

        jCbx_estcivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Estdo Civil-", "Solteiro(a)", "Casado(a)", "Desquitado(a)", "Divorciado(a)", "Separado(a)", "Viuvo(a)", "Amasiado(a)" }));
        jCbx_estcivil.setEnabled(false);

        jLabel6.setText("Data Nasc.");

        jLabel7.setText("Sexo:");

        jRBt_mas.setText("Masculino");
        jRBt_mas.setEnabled(false);

        jRBt_fem.setText("Feminino");
        jRBt_fem.setEnabled(false);

        jLabel8.setText("Endereço");

        jTxt_endereco.setEnabled(false);

        jLabel9.setText("Número");

        jTxt_numero.setEnabled(false);

        jLabel10.setText("Bairro");

        jTxt_bairro.setEnabled(false);

        jFTxt_cep.setEnabled(false);

        jLabel11.setText("CEP");

        jLabel12.setText("Cidade");

        jCbx_cidade.setEnabled(false);

        jTxt_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxt_pesquisaKeyReleased(evt);
            }
        });

        jTbl_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTbl_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_clienteMouseClicked(evt);
            }
        });
        jTbl_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbl_clienteKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTbl_cliente);

        jBtt_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/new.png"))); // NOI18N
        jBtt_novo.setText("Novo");
        jBtt_novo.setToolTipText("Novo");
        jBtt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_novoActionPerformed(evt);
            }
        });

        jBtt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save.png"))); // NOI18N
        jBtt_salvar.setText("Salvar");
        jBtt_salvar.setToolTipText("Salvar");
        jBtt_salvar.setEnabled(false);
        jBtt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_salvarActionPerformed(evt);
            }
        });

        jBtt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jBtt_editar.setText("Editar");
        jBtt_editar.setToolTipText("Editar");
        jBtt_editar.setEnabled(false);
        jBtt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_editarActionPerformed(evt);
            }
        });

        jBtt_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/del.png"))); // NOI18N
        jBtt_excluir.setText("Excluir");
        jBtt_excluir.setToolTipText("Excluir");
        jBtt_excluir.setEnabled(false);
        jBtt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_excluirActionPerformed(evt);
            }
        });

        jBtt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancela.png"))); // NOI18N
        jBtt_cancelar.setText("Cancelar");
        jBtt_cancelar.setToolTipText("Cancelar");
        jBtt_cancelar.setEnabled(false);
        jBtt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_cancelarActionPerformed(evt);
            }
        });

        jBtt_pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        jBtt_pesquisar.setText("Pesquisa");
        jBtt_pesquisar.setToolTipText("Pesquisar");
        jBtt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_pesquisarActionPerformed(evt);
            }
        });

        jLabel13.setText("Tipo");

        buttonGroup1.add(jRBt_fisica);
        jRBt_fisica.setText("Física");
        jRBt_fisica.setEnabled(false);
        jRBt_fisica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBt_fisicaMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRBt_juridica);
        jRBt_juridica.setText("Jurídica");
        jRBt_juridica.setEnabled(false);
        jRBt_juridica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBt_juridicaMouseClicked(evt);
            }
        });

        jLabel14.setText("Fone_1");

        jLabel15.setText("Fone_2");

        jLabel16.setText("E_mail");

        jTxt_email.setEnabled(false);
        jTxt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_emailKeyTyped(evt);
            }
        });

        jFTxt_cnpjcpf.setEnabled(false);

        jRBt_Cidades.setText("+");
        jRBt_Cidades.setEnabled(false);
        jRBt_Cidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBt_CidadesActionPerformed(evt);
            }
        });

        jTxt_fone.setEnabled(false);

        jTxt_fone2.setEnabled(false);

        jFTxt_datanac.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBtt_novo)
                .addGap(18, 18, 18)
                .addComponent(jBtt_salvar)
                .addGap(18, 18, 18)
                .addComponent(jBtt_editar)
                .addGap(18, 18, 18)
                .addComponent(jBtt_excluir)
                .addGap(18, 18, 18)
                .addComponent(jBtt_cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTxt_datanac, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRBt_mas)
                        .addGap(30, 30, 30)
                        .addComponent(jRBt_fem))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jTxt_nome))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBtt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxt_email)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCbx_cidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jRBt_Cidades))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxt_fone, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel15)
                                .addGap(34, 34, 34)
                                .addComponent(jTxt_fone2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxt_pesquisa)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jTxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTxt_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel13)
                                .addGap(22, 22, 22)
                                .addComponent(jRBt_fisica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRBt_juridica)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFTxt_cnpjcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTxt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel11))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTxt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(428, 428, 428)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFTxt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCbx_estcivil, 0, 106, Short.MAX_VALUE)
                                .addComponent(jTxt_numero)))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTxt_fone, jTxt_fone2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jFTxt_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(jRBt_fisica)
                        .addComponent(jRBt_juridica))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jCbx_estcivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTxt_cnpjcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jRBt_mas)
                    .addComponent(jRBt_fem)
                    .addComponent(jFTxt_datanac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTxt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTxt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTxt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jCbx_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRBt_Cidades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jTxt_fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_fone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTxt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtt_pesquisar))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtt_novo)
                    .addComponent(jBtt_salvar)
                    .addComponent(jBtt_editar)
                    .addComponent(jBtt_excluir)
                    .addComponent(jBtt_cancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTxt_fone, jTxt_fone2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTbl_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_clienteMouseClicked
        limpaCampos();
        atualizaTabela();
    }//GEN-LAST:event_jTbl_clienteMouseClicked

    private void jTbl_clienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbl_clienteKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            limpaCampos();
            atualizaTabela();
        }
    }//GEN-LAST:event_jTbl_clienteKeyReleased

    private void jBtt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_novoActionPerformed
        flag = 0;

        conCli.Conexao(obj_config._url);
        conCli.executaSQL("select id_cliente_fornecedor from tb_clientes_fornecedores order by id_cliente_fornecedor");

        try {
            if (!conCli.rs.last()) {
                jTxt_codigo.setText("1");
            } else {
                jTxt_codigo.setText(String.valueOf(conCli.rs.getInt("id_cliente_fornecedor") + 1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro novo registro!\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
        conCli.Desconecta();
        java.util.Date datahoje = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        jFTxt_datacad.setText(df.format(datahoje));
        jTxt_pesquisa.setEnabled(false);
        jBtt_pesquisar.setEnabled(false);
        jBtt_novo.setEnabled(false);
        jBtt_salvar.setEnabled(true);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(true);
        HabilitaDesabilitaCampos(1);
        jFTxt_cnpjcpf.setEnabled(!true);
    }//GEN-LAST:event_jBtt_novoActionPerformed

    private void jBtt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_salvarActionPerformed
        if (preencherObjeto()) {
            if (flag == 0) {
                control.GravarCliente_Fornecedor(mod);
            } else {
                control.AlterarCliente_Fornecedor(mod);
            }
            jTxt_nome.setEnabled(false);
            jBtt_novo.setEnabled(true);
            jBtt_salvar.setEnabled(false);
            jBtt_editar.setEnabled(false);
            jBtt_excluir.setEnabled(false);
            jBtt_cancelar.setEnabled(false);
            Outras_tela();
            limpaCampos();
            HabilitaDesabilitaCampos(0);
            preencherTabela("select * from tb_clientes_fornecedores order by id_cliente_fornecedor");
        }
    }//GEN-LAST:event_jBtt_salvarActionPerformed

    private void jBtt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_editarActionPerformed
        HabilitaDesabilitaCampos(1);
        flag = 1;
        jTxt_nome.setEnabled(true);
        jBtt_novo.setEnabled(false);
        jBtt_salvar.setEnabled(true);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(true);
    }//GEN-LAST:event_jBtt_editarActionPerformed

    private void jBtt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_excluirActionPerformed
        jTxt_nome.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);

        control.ExcluirCliente_Fornecedor(Integer.parseInt(jTxt_codigo.getText()));
        limpaCampos();
        Outras_tela();
        HabilitaDesabilitaCampos(0);
        preencherTabela("select * from tb_clientes_fornecedores order by id_cliente_fornecedor");
    }//GEN-LAST:event_jBtt_excluirActionPerformed

    private void jBtt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_cancelarActionPerformed
        limpaCampos();
        HabilitaDesabilitaCampos(0);
        jTxt_nome.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);
    }//GEN-LAST:event_jBtt_cancelarActionPerformed

    private void jBtt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_pesquisarActionPerformed
        preencherTabela("select * from tb_clientes_fornecedores where nome like '%" + jTxt_pesquisa.getText() + "%' order by id_cliente_fornecedor");
        jTxt_pesquisa.setText("");
    }//GEN-LAST:event_jBtt_pesquisarActionPerformed

    private void jRBt_fisicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBt_fisicaMouseClicked
        jLabel4.setText("CPF");
        jCbx_estcivil.setEnabled(true);
        jFTxt_datanac.setEnabled(true);
        jFTxt_cnpjcpf.setEnabled(true);

        try {
            formatoCNPJCPF = new MaskFormatter("###.###.###-##");
            formatoCNPJCPF.setValueContainsLiteralCharacters(false);
            formatoCNPJCPF.setPlaceholderCharacter('_');
            DefaultFormatterFactory formatocnpjcpf = new DefaultFormatterFactory(formatoCNPJCPF);
            if (jRBt_fisica.isSelected()) {
                jFTxt_cnpjcpf.setFormatterFactory(formatocnpjcpf);
                jFTxt_cnpjcpf.setValue("");
                jFTxt_cnpjcpf.setEnabled(true);
                jFTxt_cnpjcpf.requestFocus();
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher o campo com o tipo de mascara selecionada!\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jRBt_fisicaMouseClicked

    private void jRBt_juridicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBt_juridicaMouseClicked
        jLabel4.setText("CNPJ");
        jCbx_estcivil.setEnabled(true);
        jFTxt_datanac.setEnabled(true);
        jFTxt_cnpjcpf.setEnabled(true);

        try {
            formatoCNPJCPF = new MaskFormatter("##.###.###/####-##");
            formatoCNPJCPF.setValueContainsLiteralCharacters(false);
            formatoCNPJCPF.setPlaceholderCharacter('_');
            DefaultFormatterFactory formatocnpjcpf = new DefaultFormatterFactory(formatoCNPJCPF);
            if (jRBt_juridica.isSelected()) {
                jFTxt_cnpjcpf.setFormatterFactory(formatocnpjcpf);
                jFTxt_cnpjcpf.setValue("");
                jFTxt_cnpjcpf.setEnabled(true);
                jFTxt_cnpjcpf.requestFocus();
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher o campo com o tipo de mascara selecionada!\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jRBt_juridicaMouseClicked

    private void jTxt_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_emailKeyTyped
        if (evt.getKeyChar() == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_jTxt_emailKeyTyped

    private void jRBt_CidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBt_CidadesActionPerformed
        JIFCidades janela = new JIFCidades(1);
        Tela.jDesktop.add(janela);
        Tela.centralizaForm(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jRBt_CidadesActionPerformed

    private void jTxt_pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_pesquisaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            preencherTabela("select * from tb_clientes_fornecedores where nome like '%" + jTxt_pesquisa.getText() + "%' order by id_cliente_fornecedor");
            jTxt_pesquisa.setText("");
        }
    }//GEN-LAST:event_jTxt_pesquisaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtt_cancelar;
    private javax.swing.JButton jBtt_editar;
    private javax.swing.JButton jBtt_excluir;
    private javax.swing.JButton jBtt_novo;
    private javax.swing.JButton jBtt_pesquisar;
    private javax.swing.JButton jBtt_salvar;
    public static javax.swing.JComboBox jCbx_cidade;
    private javax.swing.JComboBox jCbx_estcivil;
    private javax.swing.JFormattedTextField jFTxt_cep;
    private javax.swing.JFormattedTextField jFTxt_cnpjcpf;
    private javax.swing.JFormattedTextField jFTxt_datacad;
    private javax.swing.JFormattedTextField jFTxt_datanac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jRBt_Cidades;
    private javax.swing.JRadioButton jRBt_fem;
    private javax.swing.JRadioButton jRBt_fisica;
    private javax.swing.JRadioButton jRBt_juridica;
    private javax.swing.JRadioButton jRBt_mas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbl_cliente;
    private javax.swing.JTextField jTxt_bairro;
    private javax.swing.JTextField jTxt_codigo;
    private javax.swing.JTextField jTxt_email;
    private javax.swing.JTextField jTxt_endereco;
    private javax.swing.JFormattedTextField jTxt_fone;
    private javax.swing.JFormattedTextField jTxt_fone2;
    private javax.swing.JTextField jTxt_nome;
    private javax.swing.JTextField jTxt_numero;
    private javax.swing.JTextField jTxt_pesquisa;
    // End of variables declaration//GEN-END:variables
public void limpaCampos() {
        jTxt_codigo.setText("");
        jTxt_nome.setText("");
        jFTxt_cnpjcpf.setText("");
        jCbx_estcivil.setSelectedIndex(0);
        jFTxt_datanac.setText("");
        jFTxt_datacad.setText("");
        jTxt_endereco.setText("");
        jTxt_bairro.setText("");
        jTxt_numero.setText("");
        jFTxt_cep.setText("");
        jTxt_fone.setText("");
        jTxt_fone2.setText("");
        jTxt_email.setText("");
        jTxt_pesquisa.setText("");
        jRBt_fisica.setSelected(!false);
        jRBt_mas.setSelected(!false);
    }

    public void PreencherCombo() {

        conCid.Conexao(obj_config._url);
        conCid.executaSQL("select nome from tb_cidades order by nome");
        try {
            conCid.rs.first();
            jCbx_cidade.removeAllItems();
            do {

                jCbx_cidade.addItem(conCid.rs.getString("nome"));

            } while (conCid.rs.next());

        } catch (SQLException ex) {

        }
        conCid.Desconecta();
    }

    public void HabilitaDesabilitaCampos(int acao) {

        if (acao == 1) {
            jRBt_fisica.setEnabled(true);
            jRBt_juridica.setEnabled(true);
            jRBt_fem.setEnabled(true);
            jRBt_mas.setEnabled(true);
            jTxt_nome.setEnabled(true);
            jFTxt_cnpjcpf.setEnabled(true);
            jCbx_estcivil.setEnabled(true);
            jFTxt_datanac.setEnabled(true);
            jTxt_endereco.setEnabled(true);
            jTxt_bairro.setEnabled(true);
            jTxt_numero.setEnabled(true);
            jFTxt_cep.setEnabled(true);
            jCbx_cidade.setEnabled(true);
            jTxt_fone.setEnabled(true);
            jTxt_fone2.setEnabled(true);
            jTxt_email.setEnabled(true);
            jTxt_pesquisa.setEnabled(false);
            jBtt_pesquisar.setEnabled(false);
            jRBt_Cidades.setEnabled(true);
        } else {
            jRBt_fisica.setEnabled(false);
            jRBt_juridica.setEnabled(false);
            jRBt_fem.setEnabled(false);
            jRBt_mas.setEnabled(false);
            jTxt_nome.setEnabled(false);
            jFTxt_cnpjcpf.setEnabled(false);
            jCbx_estcivil.setEnabled(false);
            jFTxt_datanac.setEnabled(false);
            jTxt_endereco.setEnabled(false);
            jTxt_bairro.setEnabled(false);
            jTxt_numero.setEnabled(false);
            jFTxt_cep.setEnabled(false);
            jCbx_cidade.setEnabled(false);
            jTxt_fone.setEnabled(false);
            jTxt_fone2.setEnabled(false);
            jTxt_email.setEnabled(false);
            jTxt_pesquisa.setEnabled(true);
            jBtt_pesquisar.setEnabled(true);
            jRBt_Cidades.setEnabled(!true);
        }
    }

    public boolean preencherObjeto() {
        mod.setId_cliente_fornecedor(Integer.parseInt(jTxt_codigo.getText()));
        if (("   .   .   -  ".equals(jFTxt_cnpjcpf.getText())) || ("  .   .   /    -  ".equals(jFTxt_cnpjcpf.getText()))) {
            JOptionPane.showMessageDialog(null, "Digite a cpf corretamente", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (jRBt_fisica.isSelected()) {
            mod.setCliente_fornecedor("F");
            if (!Validacoes.ValidarCPF(jFTxt_cnpjcpf.getText())) {
                JOptionPane.showMessageDialog(null, "CPF invalido!!!", "Erro", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else if (jRBt_juridica.isSelected()) {
            mod.setCliente_fornecedor("J");
            if (!Validacoes.ValidarCNPJ(jFTxt_cnpjcpf.getText())) {
                JOptionPane.showMessageDialog(null, "CNPJ invalido!!!", "Erro", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o tipo , cliente ou fornecedor", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!validar.ValidarNome(jTxt_nome.getText())) {
            JOptionPane.showMessageDialog(null, "Preencher o nome!", "Erro", JOptionPane.ERROR_MESSAGE);
            jTxt_nome.setText("");
            return false;
        }
        mod.setNome(jTxt_nome.getText());
        mod.setCpf(jFTxt_cnpjcpf.getText());

        if ("-Estdo Civil-".equals(jCbx_estcivil.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Escolhar o estado civil", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        mod.setEstado_civil((String) jCbx_estcivil.getSelectedItem());/////erro

        if (!validar.ValidarNome(jTxt_endereco.getText())) {
            JOptionPane.showMessageDialog(null, "Preencher o compo endereço!!", "Erro", JOptionPane.ERROR_MESSAGE);
            jTxt_nome.setText("");
            return false;
        }
        mod.setEndereco(jTxt_endereco.getText());
        mod.setBairro(jTxt_bairro.getText());
        mod.setNumero(jTxt_numero.getText());
        mod.setCep(jFTxt_cep.getText());
        mod.setId_cidade((String) jCbx_cidade.getSelectedItem());
        if ("  /  /    ".equals(jFTxt_datanac.getText())) {
            JOptionPane.showMessageDialog(null, "Digite a data corretamente", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        mod.setDatacad((Date) validar.formDataStrToData(jFTxt_datacad.getText()));
        mod.setDatanasc((Date) validar.formDataStrToData(jFTxt_datanac.getText()));
        if (jRBt_mas.isSelected()) {
            mod.setSexo("M");
        } else if (jRBt_fem.isSelected()) {
            mod.setSexo("F");
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o sexo", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (("(  ) 9    -    ".equals(jTxt_fone.getText())) && ("(  ) 9    -    ".equals(jTxt_fone2.getText()))) {
            JOptionPane.showMessageDialog(null, "Digite um contato pelo menos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if ((!validar.ValidarDDDbr(jTxt_fone.getText())) && (!"(  ) 9    -    ".equals(jTxt_fone.getText()))) {
            JOptionPane.showMessageDialog(null, "O DDD está errado fone 1", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        mod.setTelefone1(jTxt_fone.getText());
        if ((!validar.ValidarDDDbr(jTxt_fone2.getText())) && (!"(  ) 9    -    ".equals(jTxt_fone2.getText()))) {
            JOptionPane.showMessageDialog(null, "O DDD está errado fone 2", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        mod.setTelefone2(jTxt_fone2.getText());

        if (!validar.Validar_Email(jTxt_email.getText())) {
            JOptionPane.showMessageDialog(null, "O E_mail está errado", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        mod.setEmail(jTxt_email.getText());

        return true;
    }

    public void preencherTabela(String SQL) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Nome da Cliente", "CPF"};
        conCli.Conexao(obj_config._url);
        conCli.executaSQL(SQL);
        try {
            conCli.rs.first();

            do {
                dados.add(new Object[]{conCli.rs.getInt("id_cliente_fornecedor"), conCli.rs.getString("nome"), conCli.rs.getString("CPF_CNPJ")});

            } while (conCli.rs.next());

        } catch (SQLException ex) {

        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTbl_cliente.setModel(modelo);
        jTbl_cliente.getColumnModel().getColumn(0).setPreferredWidth(50);//90
        jTbl_cliente.getColumnModel().getColumn(0).setResizable(false);
        jTbl_cliente.getColumnModel().getColumn(1).setPreferredWidth(420);//420
        jTbl_cliente.getColumnModel().getColumn(1).setResizable(false);
        jTbl_cliente.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTbl_cliente.getColumnModel().getColumn(2).setResizable(false);
        jTbl_cliente.getTableHeader().setReorderingAllowed(false);
        jTbl_cliente.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTbl_cliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void atualizaTabela() {

        conCli.Conexao(obj_config._url);
        conCli.executaSQL("select * from tb_clientes_fornecedores where id_cliente_fornecedor = '" + jTbl_cliente.getValueAt(jTbl_cliente.getSelectedRow(), 0) + "'");

        try {
            conCli.rs.first();
            jTxt_codigo.setText(String.valueOf(conCli.rs.getInt("id_cliente_fornecedor")));

            if (conCli.rs.getString("fisica_juridica").equals("F")) {
                jRBt_fisica.setSelected(true);
                jLabel4.setText("CPF");
                formatoCNPJCPF = new MaskFormatter("###.###.###-##");
            } else {
                jRBt_juridica.setSelected(true);
                jLabel4.setText("CNPJ");
                formatoCNPJCPF = new MaskFormatter("##.###.###/####-##");
            }

            formatoCNPJCPF.setValueContainsLiteralCharacters(false);
            formatoCNPJCPF.setPlaceholderCharacter('_');
            DefaultFormatterFactory formatocnpjcpf = new DefaultFormatterFactory(formatoCNPJCPF);
            jFTxt_cnpjcpf.setFormatterFactory(formatocnpjcpf);
            jFTxt_cnpjcpf.setValue("");

            jTxt_nome.setText(conCli.rs.getString("nome"));
            jFTxt_cnpjcpf.setText(conCli.rs.getString("CPF_CNPJ"));
            jTxt_endereco.setText(conCli.rs.getString("endereco"));
            jTxt_bairro.setText(conCli.rs.getString("bairro"));
            jTxt_numero.setText(conCli.rs.getString("numero"));
            jFTxt_cep.setText(conCli.rs.getString("cep"));
            jCbx_estcivil.setSelectedItem(conCli.rs.getString("estado_civil"));

            try {
                jFTxt_datacad.setText(validar.formDataDateToStr(conCli.rs.getDate("datacad")));
                jFTxt_datanac.setText(validar.formDataDateToStr(conCli.rs.getDate("datanasc")));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro na data");
            }
            if (conCli.rs.getString("sexo").equals("M")) {
                jRBt_mas.setSelected(true);
                jRBt_fem.setSelected(false);
            } else {
                jRBt_mas.setSelected(false);
                jRBt_fem.setSelected(true);
            }

            jTxt_fone.setText(conCli.rs.getString("fone1"));

            jTxt_fone2.setText(conCli.rs.getString("fone2"));
            jTxt_email.setText(conCli.rs.getString("email"));
            conCid.Conexao(obj_config._url);
            conCid.executaSQL("select * from tb_cidades where id_cidade = " + conCli.rs.getInt("id_cidade"));
            conCid.rs.first();
            jCbx_cidade.setSelectedItem(conCid.rs.getString("nome"));

            jBtt_novo.setEnabled(false);
            jBtt_salvar.setEnabled(false);
            jBtt_editar.setEnabled(true);
            jBtt_excluir.setEnabled(true);
            jBtt_cancelar.setEnabled(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados do registro!", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher o campo com o tipo de mascara selecionada!" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
        HabilitaDesabilitaCampos(0);
    }

    public void Outras_tela() {
        if (Movimentacao != 0) {
            conCli.Conexao(obj_config._url);
            conCli.executaSQL("select nome from tb_clientes_fornecedores order by nome");
            try {
                conCli.rs.first();
                if (Movimentacao == 1) {
                    JIFCompra.jCbx_Clientes.removeAllItems();
                } else if (Movimentacao == 2) {
                    JIFVenda.jCbx_Clientes.removeAllItems();
                } else {
                    JIFTroca.jCbx_Clientes.removeAllItems();
                }

                do {
                    if (Movimentacao == 1) {
                        JIFCompra.jCbx_Clientes.addItem(conCli.rs.getString("nome"));
                    } else if (Movimentacao == 2) {
                        JIFVenda.jCbx_Clientes.addItem(conCli.rs.getString("nome"));
                    } else {
                        JIFTroca.jCbx_Clientes.addItem(conCli.rs.getString("nome"));
                    }

                } while (conCli.rs.next());

            } catch (SQLException ex) {

            }
            conCli.Desconecta();
        }
    }
}
