/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ControleCompras;
import Controle.ControleVeiculos;
import Controle.Imprimir;
import Controle.Maiuscula;
import Controle.ModeloTabela;
import Controle.Numeric;
import Controle.Validacoes;
import Controle.cadastro;
import Modelo.ModeloCompras;
import Modelo.ModeloVeiculos;
import static Visao.Tela.jDesktop;
import com.itextpdf.text.DocumentException;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.nio.channels.FileChannel;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Murylo César Souza
 */
public class JIFCompra extends javax.swing.JInternalFrame {

    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco conMod = new ConectaBanco();
    ConectaBanco conFun = new ConectaBanco();
    ConectaBanco conCli = new ConectaBanco();
    ConectaBanco conVei = new ConectaBanco();
    ControleVeiculos control = new ControleVeiculos();
    ControleCompras controlCom = new ControleCompras();
    ModeloCompras modCom = new ModeloCompras();
    ModeloVeiculos model = new ModeloVeiculos();
    Validacoes validar = new Validacoes();
    MaskFormatter formatoData, anomodelo, formatoCNPJCPF, Placa;
    DecimalFormat formatoDecimal = new DecimalFormat("##,###,###,##0.00");
    NumberFormat Fd = NumberFormat.getInstance();
    cadastro obj_config = new cadastro();

    private String URL_Foto;
    private boolean seletor = false;
    private String formato = "????";
    String fotoAntida;
    boolean carregamento = false;

    /**
     * Creates new form JIFVeiculos
     */
    public JIFCompra() {

        obj_config.carregaconfig();

        try {
            double Lucro = obj_config._LucroVeiculoEntrada;
            initComponents();

            jTxt_quilometro.setDocument(new Numeric(15));
            jTxt_versao.setDocument(new Maiuscula(50));
            jTxt_chassi.setDocument(new Maiuscula(17));
            jTxtA_obs.setDocument(new Maiuscula(100));

            jTxt_valor_pago.setDocument(new Numeric(15));
            jTxt_valor_venda.setDocument(new Numeric(15));

            jCbx_marca.setModel(new javax.swing.DefaultComboBoxModel(validar.preencherCampo((String) jCbx_veiculo.getSelectedItem())));
            imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));

            PreencherComboFun("select nome from tb_funcionarios where status = 'C' order by nome");
            PreencherComboCliente();
            preencherTabela();
            PreencherComboModelo("select descricao from tb_modelos where marca = '" + (String) jCbx_marca.getSelectedItem() + "' and veiculo ='" + (String) jCbx_veiculo.getSelectedItem() + "' order by descricao");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Por favor configure o lucro do veículo de entrada!\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
            JIFConf janela = new JIFConf();
            jDesktop.add(janela);
            Tela.centralizaForm(janela);
            janela.setVisible(true);
            dispose();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel113 = new javax.swing.JLabel();
        jTxt_codigo_Vei = new javax.swing.JTextField();
        jLabel115 = new javax.swing.JLabel();
        try{
            formatoData= new MaskFormatter("##/##/####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_datacad = new JFormattedTextField(formatoData);
        ;
        jLabel111 = new javax.swing.JLabel();
        jCbx_veiculo = new javax.swing.JComboBox();
        jLabel112 = new javax.swing.JLabel();
        jCbx_condicao = new javax.swing.JComboBox();
        jLabel114 = new javax.swing.JLabel();
        jTxt_quilometro = new javax.swing.JTextField();
        jCbx_marca = new javax.swing.JComboBox();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jTxt_versao = new javax.swing.JTextField();
        jLabel125 = new javax.swing.JLabel();
        jTxt_chassi = new javax.swing.JTextField();
        imagem = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        try{
            formatoData = new MaskFormatter("##/##/####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_dataFabricacao = new JFormattedTextField(formatoData);
        ;
        jLabel124 = new javax.swing.JLabel();
        try{
            anomodelo= new MaskFormatter("##/##");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_anoModelo = new JFormattedTextField(anomodelo);
        ;
        jLabel127 = new javax.swing.JLabel();
        jCbx_porte = new javax.swing.JComboBox();
        jLabel126 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jCbx_cor = new javax.swing.JComboBox();
        jLabel129 = new javax.swing.JLabel();
        jCbx_porta = new javax.swing.JComboBox();
        jLabel116 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRBt_completo = new javax.swing.JRadioButton();
        jRBt_flex = new javax.swing.JRadioButton();
        jRBt_direcao = new javax.swing.JRadioButton();
        jRBt_arC = new javax.swing.JRadioButton();
        jBtt_alterafoto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jBtt_salvar = new javax.swing.JButton();
        jBtt_cancelar = new javax.swing.JButton();
        jLabel117 = new javax.swing.JLabel();
        jTxt_codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCbx_Funcionarios = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jCbx_Clientes = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jFTxt_cpf = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtA_obs = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTbl_compra = new javax.swing.JTable();
        jBtt_novo = new javax.swing.JButton();
        jBtt_anula = new javax.swing.JButton();
        jBtt_excluir = new javax.swing.JButton();
        try{
            Placa= new MaskFormatter("UUU-####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_placa = new JFormattedTextField(Placa);
        ;
        jRBt_Modelos = new javax.swing.JButton();
        jCbx_modelo = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        try{
            formatoDecimal= new DecimalFormat("##,###,###,##0.00");

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");
        }
        jTxt_valor_pago = jTxt_valor_pago =  new JFormattedTextField(formatoDecimal);
        try{
            formatoDecimal= new DecimalFormat("#,##0.00");

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");
        }
        jTxt_lucro = jTxt_lucro =  new JFormattedTextField(formatoDecimal);
        jTxt_valor_venda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBtt_imprimir = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setTitle("Comprar");

        jLabel113.setText("Código");

        jTxt_codigo_Vei.setEnabled(false);

        jLabel115.setText("Data entrada");

        jFTxt_datacad.setEnabled(false);

        jLabel111.setText("Veículo");

        jCbx_veiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Moto", "Automovel", "Micro/Ônibus", "Caminhão" }));
        jCbx_veiculo.setEnabled(false);
        jCbx_veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbx_veiculoActionPerformed(evt);
            }
        });

        jLabel112.setText("Condição");

        jCbx_condicao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novo", "Semi", "Usado" }));
        jCbx_condicao.setEnabled(false);
        jCbx_condicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbx_condicaoActionPerformed(evt);
            }
        });

        jLabel114.setText("Quilometragens");

        jTxt_quilometro.setText("0");
        jTxt_quilometro.setAutoscrolls(false);
        jTxt_quilometro.setEnabled(false);
        jTxt_quilometro.setOpaque(false);
        jTxt_quilometro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxt_quilometroKeyReleased(evt);
            }
        });

        jCbx_marca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AUDI", "HYUNDAI", "VOLVO", "CHEVROLET", "NISSAN", "MERCEDES_BENZ" }));
        jCbx_marca.setEnabled(false);
        jCbx_marca.setOpaque(false);
        jCbx_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbx_marcaActionPerformed(evt);
            }
        });

        jLabel120.setText("Marca");

        jLabel121.setText("Modelo");

        jLabel122.setText("Versão");

        jTxt_versao.setAutoscrolls(false);
        jTxt_versao.setEnabled(false);

        jLabel125.setText("Chassi");

        jTxt_chassi.setEnabled(false);
        jTxt_chassi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_chassiKeyTyped(evt);
            }
        });

        imagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/AUDI.jpg"))); // NOI18N
        imagem.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        imagem.setPreferredSize(new java.awt.Dimension(265, 200));

        jLabel123.setText("Data Fab.");

        jFTxt_dataFabricacao.setAutoscrolls(false);
        jFTxt_dataFabricacao.setEnabled(false);
        jFTxt_dataFabricacao.setOpaque(false);

        jLabel124.setText("Ano Modelo");

        jFTxt_anoModelo.setAutoscrolls(false);
        jFTxt_anoModelo.setEnabled(false);
        jFTxt_anoModelo.setOpaque(false);

        jLabel127.setText("Porte");

        jCbx_porte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pequeno", "Medio", "Grande" }));
        jCbx_porte.setEnabled(false);

        jLabel126.setText("Placa");

        jLabel128.setText("Cor");

        jCbx_cor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Preto", "Branco", "Vermelho", "Prata", "Amarelo" }));
        jCbx_cor.setEnabled(false);

        jLabel129.setText("N° Portas");

        jCbx_porta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4" }));
        jCbx_porta.setEnabled(false);

        jLabel116.setText("Valor Pago");

        jLabel3.setText("Lucro +");

        jLabel1.setText("Adicionais");

        jRBt_completo.setText("Completo");
        jRBt_completo.setEnabled(false);
        jRBt_completo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBt_completoActionPerformed(evt);
            }
        });

        jRBt_flex.setText("Flex");
        jRBt_flex.setEnabled(false);

        jRBt_direcao.setText("Direção hidralica");
        jRBt_direcao.setEnabled(false);

        jRBt_arC.setText("Ar condicionado");
        jRBt_arC.setEnabled(false);

        jBtt_alterafoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/foto.png"))); // NOI18N
        jBtt_alterafoto.setText("Alterar Foto");
        jBtt_alterafoto.setEnabled(false);
        jBtt_alterafoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_alterafotoActionPerformed(evt);
            }
        });

        jBtt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save.png"))); // NOI18N
        jBtt_salvar.setText("Salvar");
        jBtt_salvar.setToolTipText("Salvar");
        jBtt_salvar.setEnabled(false);
        jBtt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_salvarActionPerformed(evt);
            }
        });

        jBtt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancela.png"))); // NOI18N
        jBtt_cancelar.setText("Cancelar");
        jBtt_cancelar.setToolTipText("Cancelar");
        jBtt_cancelar.setEnabled(false);
        jBtt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_cancelarActionPerformed(evt);
            }
        });

        jLabel117.setText("Código ");

        jTxt_codigo.setEnabled(false);

        jLabel2.setText("Funcionário");

        jCbx_Funcionarios.setEnabled(false);

        jLabel6.setText("Cliente");

        jCbx_Clientes.setEnabled(false);
        jCbx_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbx_ClientesActionPerformed(evt);
            }
        });

        jLabel7.setText("CPF");

        jFTxt_cpf.setEnabled(false);

        jTxtA_obs.setColumns(20);
        jTxtA_obs.setRows(5);
        jTxtA_obs.setEnabled(false);
        jScrollPane3.setViewportView(jTxtA_obs);

        jTbl_compra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTbl_compra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_compraMouseClicked(evt);
            }
        });
        jTbl_compra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbl_compraKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTbl_compra);

        jBtt_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/new.png"))); // NOI18N
        jBtt_novo.setText("Novo");
        jBtt_novo.setToolTipText("Novo");
        jBtt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_novoActionPerformed(evt);
            }
        });

        jBtt_anula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancela.png"))); // NOI18N
        jBtt_anula.setText("Anula");
        jBtt_anula.setToolTipText("Editar");
        jBtt_anula.setEnabled(false);
        jBtt_anula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_anulaActionPerformed(evt);
            }
        });

        jBtt_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/del.png"))); // NOI18N
        jBtt_excluir.setText("Excluir");
        jBtt_excluir.setToolTipText("Excluir");
        jBtt_excluir.setEnabled(false);
        jBtt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_excluirActionPerformed(evt);
            }
        });

        jFTxt_placa.setEnabled(false);

        jRBt_Modelos.setText("+");
        jRBt_Modelos.setEnabled(false);
        jRBt_Modelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBt_ModelosActionPerformed(evt);
            }
        });

        jCbx_modelo.setEnabled(false);

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTxt_valor_pago.setEnabled(false);
        jTxt_valor_pago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxt_valor_pagoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_valor_pagoKeyTyped(evt);
            }
        });

        jTxt_lucro.setEnabled(false);
        jTxt_lucro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxt_lucroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_lucroKeyTyped(evt);
            }
        });

        jTxt_valor_venda.setEnabled(false);

        jLabel4.setText("Valor venda");

        jBtt_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Printer Add.jpg"))); // NOI18N
        jBtt_imprimir.setText("Imprimir");
        jBtt_imprimir.setEnabled(false);
        jBtt_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtt_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtt_anula, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtt_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtt_excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtt_cancelar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtt_imprimir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel113, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jTxt_codigo_Vei, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel115)
                                .addGap(18, 18, 18)
                                .addComponent(jFTxt_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel111, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jCbx_veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel112)
                                .addGap(10, 10, 10)
                                .addComponent(jCbx_condicao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel127)
                                .addGap(4, 4, 4)
                                .addComponent(jCbx_porte, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel117, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jTxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addGap(22, 22, 22)
                                .addComponent(jCbx_Funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCbx_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jFTxt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel126, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel116))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFTxt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel128)
                                        .addGap(16, 16, 16)
                                        .addComponent(jCbx_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel129)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCbx_porta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRBt_completo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jRBt_direcao)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBt_arC)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBt_flex, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jTxt_valor_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTxt_lucro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTxt_valor_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel121, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCbx_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRBt_Modelos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel123, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFTxt_dataFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                        .addComponent(jLabel114)
                                        .addGap(11, 11, 11)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel122, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTxt_versao, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel125, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jTxt_chassi, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxt_quilometro, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel124)
                                        .addGap(10, 10, 10)
                                        .addComponent(jFTxt_anoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel120, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jCbx_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 475, Short.MAX_VALUE)
                            .addComponent(jBtt_alterafoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(25, 57, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel113, jLabel116, jLabel121, jLabel123, jLabel126});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtt_anula, jBtt_cancelar, jBtt_excluir, jBtt_imprimir, jBtt_novo, jBtt_salvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel113, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_codigo_Vei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel115, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTxt_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel111, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel112, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_condicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel127, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_porte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel114, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxt_quilometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel124, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFTxt_anoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel120, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCbx_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel123, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFTxt_dataFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxt_chassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel121, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCbx_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRBt_Modelos)
                                        .addComponent(jLabel122, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxt_versao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel125, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel126, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel116, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel128, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCbx_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel129, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCbx_porta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jFTxt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRBt_completo)
                                    .addComponent(jRBt_direcao)
                                    .addComponent(jRBt_arC)
                                    .addComponent(jRBt_flex))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxt_valor_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTxt_lucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxt_valor_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel117, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_Funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbx_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2))
                            .addComponent(jFTxt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtt_anula)
                        .addComponent(jBtt_novo)
                        .addComponent(jBtt_salvar)
                        .addComponent(jBtt_excluir)
                        .addComponent(jBtt_cancelar)
                        .addComponent(jBtt_imprimir))
                    .addComponent(jBtt_alterafoto))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel113, jLabel116, jLabel121, jLabel123, jLabel126});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtt_anula, jBtt_cancelar, jBtt_excluir, jBtt_imprimir, jBtt_novo, jBtt_salvar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCbx_condicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbx_condicaoActionPerformed
        if (jCbx_condicao.getSelectedItem() == "Novo") {
            jTxt_quilometro.setText("0");
            jTxt_quilometro.setEnabled(!true);
        } else {
            jTxt_quilometro.setText("0");
            jTxt_quilometro.setEnabled(true);
        }
    }//GEN-LAST:event_jCbx_condicaoActionPerformed

    private void jBtt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_salvarActionPerformed
        if (preencherObjeto()) {

            if ((seletor) && (!"".equals(URL_Foto))) {
                try {
                    FileInputStream origem = new FileInputStream(URL_Foto);  //arquivo que você quer copiar
                    FileOutputStream destino = new FileOutputStream("Imagens\\" + jTxt_codigo_Vei.getText() + formato); //onde irá ficar a copia do aquivo
                    FileChannel fcOrigem = origem.getChannel();
                    FileChannel fcDestino = destino.getChannel();
                    fcOrigem.transferTo(0, fcOrigem.size(), fcDestino);//copiando o arquivo e salvando no diretório que você escolheu  
                    destino.close();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao copiar imagem\n\n" + ex);
                }
            }
            model.setFoto(jTxt_codigo_Vei.getText() + formato);

            control.GravarVeiculos(model);
            controlCom.GravarCompra(modCom);

            limpaCampos();
            preencherTabela();
            HabilitaDesabilitaCampos(0);
            jBtt_imprimir.setEnabled(!true);
            imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
        }
    }//GEN-LAST:event_jBtt_salvarActionPerformed

    private void jBtt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_cancelarActionPerformed
        limpaCampos();
        HabilitaDesabilitaCampos(0);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_anula.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);
        jBtt_imprimir.setEnabled(!true);
    }//GEN-LAST:event_jBtt_cancelarActionPerformed

    private void jRBt_completoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBt_completoActionPerformed
        if (jRBt_completo.isSelected()) {
            jRBt_flex.setSelected(true);
            jRBt_direcao.setSelected(true);
            jRBt_arC.setSelected(true);
        } else {
            jRBt_flex.setSelected(!true);
            jRBt_direcao.setSelected(!true);
            jRBt_arC.setSelected(!true);
        }
    }//GEN-LAST:event_jRBt_completoActionPerformed

    private void jBtt_alterafotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_alterafotoActionPerformed
        try {
            javax.swing.JFileChooser busca_foto = new javax.swing.JFileChooser();
            busca_foto.setMultiSelectionEnabled(false);
            busca_foto.setCurrentDirectory(new File("D:\\"));
            busca_foto.setDialogTitle("Selecione a foto do veiculo");
            busca_foto.setFileFilter(new FileNameExtensionFilter("JPG, GIF, BMP e PNG", "jpg", "gif", "png", "bmp"));//nao entendi pq tem que repetir as extencoes  
            busca_foto.setFileSelectionMode(JFileChooser.FILES_ONLY);

            if (busca_foto.showOpenDialog(this) == 0) {// se clica em abrir imagem faz isso... 

                char[] format = formato.toCharArray(), foto = busca_foto.getSelectedFile().getName().toCharArray();
                format[0] = foto[busca_foto.getSelectedFile().getName().length() - 4];
                format[1] = foto[busca_foto.getSelectedFile().getName().length() - 3];
                format[2] = foto[busca_foto.getSelectedFile().getName().length() - 2];
                format[3] = foto[busca_foto.getSelectedFile().getName().length() - 1];
                char[] upper = String.valueOf(format).toCharArray();
                for (int i = 0; i < upper.length; i++) {
                    upper[i] = Character.toUpperCase(upper[i]);
                }
                formato = String.valueOf(upper);
                if ((".PNG".equals(formato)) || (".JPG".equals(formato)) || (".GIF".equals(formato)) || (".BMP".equals(formato))) {
                    URL_Foto = busca_foto.getSelectedFile().getAbsolutePath();
                    imagem.setIcon(new ImageIcon(new ImageIcon(busca_foto.getSelectedFile().getAbsolutePath()).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
                    seletor = true;
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor selecione as imagens com o formato:\n\n.PNG, .JPG, .GIF, .BMP");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir seletor de arquivo\n\n!" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtt_alterafotoActionPerformed

    private void jCbx_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbx_marcaActionPerformed
        imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
        URL_Foto = "";
        PreencherComboModelo("select descricao from tb_modelos where marca = '" + (String) jCbx_marca.getSelectedItem() + "' and veiculo ='" + (String) jCbx_veiculo.getSelectedItem() + "' order by descricao");
    }//GEN-LAST:event_jCbx_marcaActionPerformed

    private void jCbx_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbx_ClientesActionPerformed

        if (carregamento) {
            conecta.Conexao(obj_config._url);
            conecta.executaSQL("select CPF_CNPJ,fisica_juridica from tb_clientes_fornecedores where nome = '" + ((String) jCbx_Clientes.getSelectedItem()) + "'");
            try {
                conecta.rs.first();
                if (conecta.rs.getString("fisica_juridica").equals("F")) {

                    jLabel7.setText("CPF");
                    formatoCNPJCPF = new MaskFormatter("###.###.###-##");
                } else {
                    jLabel7.setText("CNPJ");
                    formatoCNPJCPF = new MaskFormatter("##.###.###/####-##");
                }
                jFTxt_cpf.setText(String.valueOf(conecta.rs.getString("CPF_CNPJ")));

            } catch (SQLException ex) {
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao inserir mascara!\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
            }
            conecta.Desconecta();
        }
        carregamento = true;
    }//GEN-LAST:event_jCbx_ClientesActionPerformed

    private void jBtt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_novoActionPerformed
        limpaCampos();
        conVei.Conexao(obj_config._url);
        conVei.executaSQL("select id_veiculo from tb_veiculos order by id_veiculo");
        conecta.Conexao(obj_config._url);
        conecta.executaSQL("select id_compra from tb_compras order by id_compra");

        try {
            if (!conVei.rs.last()) {
                jTxt_codigo_Vei.setText("1");
            } else {
                jTxt_codigo_Vei.setText(String.valueOf(conVei.rs.getInt("id_veiculo") + 1));
            }
            if (!conecta.rs.last()) {
                jTxt_codigo.setText("1");
            } else {
                jTxt_codigo.setText(String.valueOf(conecta.rs.getInt("id_compra") + 1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir registro!\n\n" + ex);
        }

        conVei.Desconecta();
        conecta.Desconecta();
        java.util.Date datahoje = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        jFTxt_datacad.setText(df.format(datahoje));
        jBtt_novo.setEnabled(false);
        jBtt_salvar.setEnabled(true);
        jBtt_anula.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(true);

        HabilitaDesabilitaCampos(1);

        jTxt_quilometro.setText("0");
        jTxt_quilometro.setEnabled(!true);
        jRBt_completo.setEnabled(!true);
        jRBt_flex.setEnabled(true);
        jRBt_direcao.setEnabled(!true);
        jRBt_arC.setEnabled(!true);
        jCbx_porta.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"0"}));
        jCbx_porta.setEnabled(!true);
        jBtt_imprimir.setEnabled(!true);
        imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_jBtt_novoActionPerformed

    private void jTbl_compraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbl_compraKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            atualizaTabela();
        }
    }//GEN-LAST:event_jTbl_compraKeyReleased

    private void jTbl_compraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_compraMouseClicked
        atualizaTabela();
    }//GEN-LAST:event_jTbl_compraMouseClicked

    private void jBtt_anulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_anulaActionPerformed
        controlCom.AlterarCompra(Integer.parseInt(jTxt_codigo.getText()), Integer.parseInt(jTxt_codigo_Vei.getText()));
        preencherTabela();
        imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_anula.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);
        jBtt_imprimir.setEnabled(!true);
    }//GEN-LAST:event_jBtt_anulaActionPerformed

    private void jBtt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_excluirActionPerformed
        jTxt_codigo_Vei.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_anula.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);
        jBtt_imprimir.setEnabled(!true);
        controlCom.ExcluirCompra(Integer.parseInt(jTxt_codigo.getText()));
        limpaCampos();
        HabilitaDesabilitaCampos(0);
        preencherTabela();
        imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_jBtt_excluirActionPerformed

    private void jCbx_veiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbx_veiculoActionPerformed
        if (jCbx_veiculo.getSelectedItem() == "Moto") {
            jRBt_completo.setEnabled(!true);
            jRBt_flex.setEnabled(true);
            jRBt_direcao.setEnabled(!true);
            jRBt_arC.setEnabled(!true);

            jRBt_completo.setSelected(!true);
            jRBt_flex.setSelected(!true);
            jRBt_direcao.setSelected(!true);
            jRBt_arC.setSelected(!true);

            jCbx_porta.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"0"}));
            jCbx_porta.setEnabled(!true);
        } else {
            jRBt_completo.setEnabled(true);
            jRBt_flex.setEnabled(true);
            jRBt_direcao.setEnabled(true);
            jRBt_arC.setEnabled(true);

            jCbx_porta.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"0", "3", "4"}));
            jCbx_porta.setEnabled(true);
        }
        URL_Foto = "";
        jCbx_marca.setModel(new javax.swing.DefaultComboBoxModel(validar.preencherCampo((String) jCbx_veiculo.getSelectedItem())));
        imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
        PreencherComboModelo("select descricao from tb_modelos where marca = '" + (String) jCbx_marca.getSelectedItem() + "' and veiculo ='" + (String) jCbx_veiculo.getSelectedItem() + "' order by descricao");
    }//GEN-LAST:event_jCbx_veiculoActionPerformed

    private void jRBt_ModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBt_ModelosActionPerformed

        JIFModelos janela = new JIFModelos();
        Tela.jDesktop.add(janela);
        Tela.centralizaForm(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jRBt_ModelosActionPerformed

    private void jTxt_quilometroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_quilometroKeyReleased
        if ((evt.getKeyChar() == '-') || (evt.getKeyChar() == '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTxt_quilometroKeyReleased

    private void jTxt_chassiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_chassiKeyTyped
        if ((evt.getKeyChar() == 'o') || (evt.getKeyChar() == 'q') || (evt.getKeyChar() == 'i') || (evt.getKeyChar() == ' ')
                || (evt.getKeyChar() == 'O') || (evt.getKeyChar() == 'Q') || (evt.getKeyChar() == 'I')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTxt_chassiKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JIFCliente_fornecedor janela = new JIFCliente_fornecedor(1);
        Tela.jDesktop.add(janela);
        Tela.centralizaForm(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTxt_valor_pagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_valor_pagoKeyTyped
        if (!((evt.getKeyChar() == ',') || (evt.getKeyChar() == '.') || (evt.getKeyChar() == '1') || (evt.getKeyChar() == '2') || (evt.getKeyChar() == '3') || (evt.getKeyChar() == '4') || (evt.getKeyChar() == '5') || (evt.getKeyChar() == '6') || (evt.getKeyChar() == '7') || (evt.getKeyChar() == '8') || (evt.getKeyChar() == '9') || (evt.getKeyChar() == '0'))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTxt_valor_pagoKeyTyped

    private void jTxt_lucroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_lucroKeyTyped
        if (!((evt.getKeyChar() == ',') || (evt.getKeyChar() == '.') || (evt.getKeyChar() == '1') || (evt.getKeyChar() == '2') || (evt.getKeyChar() == '3') || (evt.getKeyChar() == '4') || (evt.getKeyChar() == '5') || (evt.getKeyChar() == '6') || (evt.getKeyChar() == '7') || (evt.getKeyChar() == '8') || (evt.getKeyChar() == '9') || (evt.getKeyChar() == '0'))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTxt_lucroKeyTyped

    private void jTxt_valor_pagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_valor_pagoKeyReleased
        jTxt_valor_venda.setText(Fd.format(new BigDecimal(validar.Lucro_Veiculo_Entrada(jTxt_valor_pago.getText(), jTxt_lucro.getText(), obj_config._LucroVeiculoEntrada / 100))));
    }//GEN-LAST:event_jTxt_valor_pagoKeyReleased

    private void jTxt_lucroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_lucroKeyReleased
        jTxt_valor_venda.setText(Fd.format(new BigDecimal(validar.Lucro_Veiculo_Entrada(jTxt_valor_pago.getText(), jTxt_lucro.getText(), obj_config._LucroVeiculoEntrada / 100))));
    }//GEN-LAST:event_jTxt_lucroKeyReleased

    private void jBtt_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_imprimirActionPerformed
        try {
            new Imprimir().Comprar_PDF(Integer.parseInt(jTxt_codigo.getText()));
        } catch (NumberFormatException | DocumentException | IOException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao criar arquivo pdf\n\n" + ex, "erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir pdf\n\n" + ex, "erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBtt_imprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagem;
    private javax.swing.JButton jBtt_alterafoto;
    private javax.swing.JButton jBtt_anula;
    private javax.swing.JButton jBtt_cancelar;
    private javax.swing.JButton jBtt_excluir;
    private javax.swing.JButton jBtt_imprimir;
    private javax.swing.JButton jBtt_novo;
    private javax.swing.JButton jBtt_salvar;
    private javax.swing.JButton jButton2;
    public static javax.swing.JComboBox jCbx_Clientes;
    private javax.swing.JComboBox jCbx_Funcionarios;
    private javax.swing.JComboBox jCbx_condicao;
    private javax.swing.JComboBox jCbx_cor;
    private javax.swing.JComboBox jCbx_marca;
    private javax.swing.JComboBox jCbx_modelo;
    private javax.swing.JComboBox jCbx_porta;
    private javax.swing.JComboBox jCbx_porte;
    private javax.swing.JComboBox jCbx_veiculo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFormattedTextField jFTxt_anoModelo;
    private javax.swing.JFormattedTextField jFTxt_cpf;
    private javax.swing.JFormattedTextField jFTxt_dataFabricacao;
    private javax.swing.JFormattedTextField jFTxt_datacad;
    private javax.swing.JFormattedTextField jFTxt_placa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JButton jRBt_Modelos;
    private javax.swing.JRadioButton jRBt_arC;
    private javax.swing.JRadioButton jRBt_completo;
    private javax.swing.JRadioButton jRBt_direcao;
    private javax.swing.JRadioButton jRBt_flex;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTbl_compra;
    private javax.swing.JTextArea jTxtA_obs;
    private javax.swing.JTextField jTxt_chassi;
    private javax.swing.JTextField jTxt_codigo;
    private javax.swing.JTextField jTxt_codigo_Vei;
    private javax.swing.JFormattedTextField jTxt_lucro;
    private javax.swing.JTextField jTxt_quilometro;
    private javax.swing.JFormattedTextField jTxt_valor_pago;
    private javax.swing.JTextField jTxt_valor_venda;
    private javax.swing.JTextField jTxt_versao;
    // End of variables declaration//GEN-END:variables

    public void limpaCampos() {
        jTxt_codigo_Vei.setText("");
        jFTxt_datacad.setText("");
        jTxt_quilometro.setText("");
        jFTxt_dataFabricacao.setText("");
        jFTxt_anoModelo.setText("");
        jTxt_versao.setText("");
        jTxt_chassi.setText("");
        jFTxt_placa.setText("");
        jRBt_completo.setSelected(!true);
        jRBt_flex.setSelected(!true);
        jRBt_direcao.setSelected(!true);
        jRBt_arC.setSelected(!true);
        jTxtA_obs.setText("");
        jTxt_valor_pago.setText("");
        jTxt_codigo.setText("");
        imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
        fotoAntida = null;

    }

    public void HabilitaDesabilitaCampos(int acao) {

        if (acao == 1) {
            jTxt_quilometro.setText("0");
            jCbx_veiculo.setEnabled(true);
            jCbx_condicao.setEnabled(true);
            jTxt_quilometro.setEnabled(!true);
            jFTxt_dataFabricacao.setEnabled(true);
            jFTxt_anoModelo.setEnabled(true);
            jCbx_porte.setEnabled(true);
            jCbx_marca.setEnabled(true);
            jCbx_modelo.setEnabled(true);
            jTxt_versao.setEnabled(true);
            jTxt_chassi.setEnabled(true);
            jFTxt_placa.setEnabled(true);
            jCbx_cor.setEnabled(true);
            jCbx_porta.setEnabled(true);
            jRBt_completo.setEnabled(!true);
            jRBt_flex.setEnabled(true);
            jRBt_direcao.setEnabled(!true);
            jRBt_arC.setEnabled(!true);
            jTxtA_obs.setEnabled(true);
            jTxt_valor_pago.setEnabled(true);
            jTxt_lucro.setEnabled(true);
            jBtt_alterafoto.setEnabled(true);
            jRBt_Modelos.setEnabled(true);
            jCbx_Funcionarios.setEnabled(true);
            jCbx_Clientes.setEnabled(true);

        } else {
            jCbx_veiculo.setEnabled(!true);
            jCbx_condicao.setEnabled(!true);
            jTxt_quilometro.setEnabled(!true);
            jFTxt_dataFabricacao.setEnabled(!true);
            jFTxt_anoModelo.setEnabled(!true);
            jCbx_porte.setEnabled(!true);
            jCbx_marca.setEnabled(!true);
            jCbx_modelo.setEnabled(!true);
            jTxt_versao.setEnabled(!true);
            jTxt_chassi.setEnabled(!true);
            jFTxt_placa.setEnabled(!true);
            jCbx_cor.setEnabled(!true);
            jCbx_porta.setEnabled(!true);
            jRBt_completo.setEnabled(!true);
            jRBt_flex.setEnabled(!true);
            jRBt_direcao.setEnabled(!true);
            jRBt_arC.setEnabled(!true);
            jTxtA_obs.setEnabled(!true);
            jTxt_valor_pago.setEnabled(!true);
            jTxt_lucro.setEnabled(!true);
            jBtt_alterafoto.setEnabled(!true);
            jRBt_Modelos.setEnabled(!true);
            jCbx_Funcionarios.setEnabled(!true);
            jCbx_Clientes.setEnabled(!true);
        }
    }

    public void PreencherComboModelo(String SQL) {

        conMod.Conexao(obj_config._url);
        conMod.executaSQL(SQL);
        try {
            conMod.rs.first();
            jCbx_modelo.removeAllItems();
            do {
                jCbx_modelo.addItem(conMod.rs.getString("descricao"));
            } while (conMod.rs.next());
        } catch (SQLException ex) {
        }
        conMod.Desconecta();
    }

    public void PreencherComboFun(String SQL) {
        conecta.Conexao(obj_config._url);
        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            jCbx_Funcionarios.removeAllItems();
            do {
                jCbx_Funcionarios.addItem(conecta.rs.getString("nome"));
            } while (conecta.rs.next());
        } catch (SQLException ex) {
        }
        conecta.Desconecta();
    }

    public void PreencherComboCliente() {
        conecta.Conexao(obj_config._url);
        conecta.executaSQL("select nome,fisica_juridica,cpf_cnpj from tb_clientes_fornecedores order by nome");
        try {
            conecta.rs.first();
            jCbx_Clientes.removeAllItems();

            if (conecta.rs.getString("fisica_juridica").equals("F")) {

                jLabel7.setText("CPF");
                formatoCNPJCPF = new MaskFormatter("###.###.###-##");
            } else {
                jLabel7.setText("CNPJ");
                formatoCNPJCPF = new MaskFormatter("##.###.###/####-##");
            }
            jFTxt_cpf.setText(String.valueOf(conecta.rs.getString("CPF_CNPJ")));

            do {
                jCbx_Clientes.addItem(conecta.rs.getString("nome"));
            } while (conecta.rs.next());
        } catch (SQLException ex) {
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir mascara!\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
        conecta.Desconecta();
    }

    public boolean preencherObjeto() {
        model.setId_veiculo(Integer.parseInt(jTxt_codigo_Vei.getText()));
        model.setDataCad((Date) validar.formDataStrToData(jFTxt_datacad.getText()));

        model.setCompra_venda("C");

        if (jCbx_veiculo.getSelectedItem() == "Moto") {
            model.setVeiculo("M");
        } else if (jCbx_veiculo.getSelectedItem() == "Carro") {
            model.setVeiculo("C");
        } else {
            model.setVeiculo("O");
        }
        if (jCbx_condicao.getSelectedItem() == "Novo") {
            model.setCondicao("N");
        } else if (jCbx_veiculo.getSelectedItem() == "Semi") {
            model.setCondicao("S");
        } else {
            model.setCondicao("U");
        }
        if ("".equals(jTxt_quilometro.getText())) {
            JOptionPane.showMessageDialog(null, "Complete o campo quilomentragens", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        model.setQuilomentragem(Integer.parseInt(jTxt_quilometro.getText()));
        if ("  /  /    ".equals(jFTxt_dataFabricacao.getText())) {
            JOptionPane.showMessageDialog(null, "Complete o campo quilomentragens", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        model.setDataFab((Date) validar.formDataStrToData(jFTxt_dataFabricacao.getText()));
        model.setAnoModelo(jFTxt_anoModelo.getText());
        if (jCbx_porte.getSelectedItem() == "Pequeno") {
            model.setPorte("P");
        } else if (jCbx_porte.getSelectedItem() == "Medio") {
            model.setPorte("M");
        } else {
            model.setPorte("G");
        }
        model.setMarca((String) jCbx_marca.getSelectedItem());
        model.setModelo((String) jCbx_modelo.getSelectedItem());
        model.setVersao(jTxt_versao.getText());
        if (!validar.chassi(jTxt_chassi.getText())) {
            JOptionPane.showMessageDialog(null, "Chassi invalido", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        model.setChassi(jTxt_chassi.getText());
        model.setPlaca(jFTxt_placa.getText());
        model.setCor((String) jCbx_cor.getSelectedItem());
        int porta = Integer.parseInt((String) (jCbx_porta.getSelectedItem()));
        model.setPorta(porta);
        if (jRBt_flex.isSelected()) {
            model.setFlex("T");
        } else {
            model.setFlex("F");
        }
        if (jRBt_direcao.isSelected()) {
            model.setDirecao_hidraulica("T");
        } else {
            model.setDirecao_hidraulica("F");
        }
        if (jRBt_arC.isSelected()) {
            model.setAr_condicionado("T");
        } else {
            model.setAr_condicionado("F");
        }

        model.setObs(jTxtA_obs.getText());

        if (("".equals(jTxt_valor_pago.getText()))) {
            JOptionPane.showMessageDialog(null, "O erro no Valor_pago", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        model.setValor_pago(Double.valueOf(jTxt_valor_pago.getText().replaceAll("\\.", "").replaceAll("\\,", ".")));

        modCom.setValor(Double.valueOf(jTxt_valor_pago.getText().replaceAll("\\.", "").replaceAll("\\,", ".")));

        jTxt_valor_venda.setText(Fd.format(new BigDecimal(validar.Lucro_Veiculo_Entrada(jTxt_valor_pago.getText(), jTxt_lucro.getText(), obj_config._LucroVeiculoEntrada))));
        if (("".equals(jTxt_valor_venda.getText()))) {
            JOptionPane.showMessageDialog(null, "Complete o campo Valor_pago", "Atenção", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        model.setValor_venda(Double.valueOf(jTxt_valor_pago.getText().replaceAll("\\.", "").replaceAll("\\,", ".")));

        model.setSituacao("T");

        modCom.setId_compra(Integer.parseInt(jTxt_codigo.getText()));
        modCom.setDatacad((Date) validar.formDataStrToData(jFTxt_datacad.getText()));
        modCom.setId_veiculo(Integer.parseInt(jTxt_codigo_Vei.getText()));
        modCom.setId_fornecedor((String) (jCbx_Clientes.getSelectedItem()));
        modCom.setId_funcionario((String) (jCbx_Funcionarios.getSelectedItem()));
        return true;
    }

    public void preencherTabela() {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Nulo", "Data", "Funcionarios", "Cliente", "Valor"};
        conecta.Conexao(obj_config._url);
        conecta.executaSQL("select * from tb_compras C ,tb_clientes_fornecedores F , tb_veiculos V ,tb_modelos M where"//Selecione as tabela
                + " C.id_fornecedor = F.id_cliente_fornecedor"
                + " and V.id_veiculo = C.id_veiculo"
                + " and M.id_modelo = V.modelo"
                + " order by C.id_compra");
        conFun.Conexao(obj_config._url);
        try {
            conecta.rs.first();

            do {
                conFun.executaSQL("select nome from tb_funcionarios where id_funcionario = " + conecta.rs.getInt("id_funcionario"));
                conFun.rs.first();
                String NULO = conecta.rs.getString("nulo");
                if ("T".equals(NULO)) {
                    NULO = "SIM";
                } else {
                    NULO = "---";
                }
                dados.add(new Object[]{conecta.rs.getInt("id_compra"), NULO, (validar.formDataDateToStr(conecta.rs.getDate("datacad"))), conFun.rs.getString("nome"), conecta.rs.getString("nome"), conecta.rs.getDouble("valor")});
            } while (conecta.rs.next());

        } catch (SQLException ex) {
        }
        conecta.Desconecta();
        conFun.Desconecta();
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTbl_compra.setModel(modelo);
        jTbl_compra.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTbl_compra.getColumnModel().getColumn(0).setResizable(false);
        jTbl_compra.getColumnModel().getColumn(1).setPreferredWidth(40);
        jTbl_compra.getColumnModel().getColumn(1).setResizable(false);
        jTbl_compra.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTbl_compra.getColumnModel().getColumn(2).setResizable(false);
        jTbl_compra.getColumnModel().getColumn(3).setPreferredWidth(500);
        jTbl_compra.getColumnModel().getColumn(3).setResizable(false);
        jTbl_compra.getColumnModel().getColumn(4).setPreferredWidth(500);
        jTbl_compra.getColumnModel().getColumn(4).setResizable(false);
        jTbl_compra.getColumnModel().getColumn(5).setPreferredWidth(70);
        jTbl_compra.getColumnModel().getColumn(5).setResizable(false);
        jTbl_compra.getTableHeader().setReorderingAllowed(false);
        jTbl_compra.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTbl_compra.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    public JIFCompra(DefaultTableModel defaultTableModel) {

        int a = jTbl_compra.getSelectedRow();

        if (a == 2) {
            jTbl_compra.setBackground(Color.red);
        }

    }

    public void atualizaTabela() {

        conecta.Conexao(obj_config._url);
        conecta.executaSQL("select * from tb_compras where id_compra = '" + jTbl_compra.getValueAt(jTbl_compra.getSelectedRow(), 0) + "'");
        try {
            conecta.rs.first();
            jTxt_codigo.setText(String.valueOf(conecta.rs.getInt("id_compra")));
            jFTxt_datacad.setText(validar.formDataDateToStr(conecta.rs.getDate("datacad")));
            int veiculo = conecta.rs.getInt("id_veiculo"), Fornecedor = conecta.rs.getInt("id_fornecedor"), Funcionarios = conecta.rs.getInt("id_funcionario");

            conecta.Desconecta();
            conecta.Conexao(obj_config._url);
            conecta.executaSQL("select nome from tb_clientes_fornecedores where id_cliente_fornecedor = '" + Fornecedor + "'");
            conecta.rs.first();
            jCbx_Clientes.setSelectedItem(conecta.rs.getString("nome"));
            conecta.Desconecta();

            conecta.Conexao(obj_config._url);
            conecta.executaSQL("select * from tb_veiculos V,tb_modelos M where V.id_veiculo = '" + veiculo + "' and M.id_modelo = V.modelo");

            conecta.rs.first();
            jTxt_codigo_Vei.setText(String.valueOf(conecta.rs.getInt("id_veiculo")));
            jFTxt_datacad.setText(validar.formDataDateToStr(conecta.rs.getDate("datacad")));

            if (conecta.rs.getString("veiculo").equals("M")) {
                jCbx_veiculo.setSelectedItem("Moto");
                jCbx_porta.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"0"}));
                jCbx_porta.setEnabled(!true);
            } else if (conecta.rs.getString("veiculo").equals("C")) {
                jCbx_veiculo.setSelectedItem("Carro");
            } else if (conecta.rs.getString("veiculo").equals("O")) {
                jCbx_veiculo.setSelectedItem("Onibus");
            }

            if (conecta.rs.getString("condicao").equals("N")) {
                jCbx_condicao.setSelectedItem("Novo");
            } else if (conecta.rs.getString("condicao").equals("S")) {
                jCbx_condicao.setSelectedItem("Semi");
            } else if (conecta.rs.getString("condicao").equals("U")) {
                jCbx_condicao.setSelectedItem("Usado");
            }

            jTxt_quilometro.setText(conecta.rs.getString("quilomentragem"));
            try {
                jFTxt_dataFabricacao.setText(validar.formDataDateToStr(conecta.rs.getDate("datafab")));
            } catch (Exception e) {
            }

            jFTxt_anoModelo.setText(conecta.rs.getString("anomodelo"));

            if ("P".equals(conecta.rs.getString("porte"))) {
                jCbx_porte.setSelectedItem("Pequeno");
            } else if ("M".equals(conecta.rs.getString("porte"))) {
                jCbx_porte.setSelectedItem("Medio");
            } else if ("G".equals(conecta.rs.getString("porte"))) {
                jCbx_porte.setSelectedItem("Grande");
            }
            jCbx_marca.setSelectedItem(conecta.rs.getString("marca"));
            jCbx_modelo.setSelectedItem(conecta.rs.getString("descricao"));
            jTxt_versao.setText(conecta.rs.getString("versao"));
            jTxt_chassi.setText(conecta.rs.getString("chassi"));
            jFTxt_placa.setText(conecta.rs.getString("placa"));
            jCbx_cor.setSelectedItem(conecta.rs.getString("cor"));
            jCbx_porta.setSelectedItem(conecta.rs.getString("porta"));
            int ok = 0;
            if ("T".equals(conecta.rs.getString("flex"))) {
                jRBt_flex.setSelected(true);
                ok++;
            } else {
                jRBt_flex.setSelected(!true);
            }

            if ("T".equals(conecta.rs.getString("direcao_hidraulica"))) {
                jRBt_direcao.setSelected(true);
                ok++;
            } else {
                jRBt_direcao.setSelected(!true);
            }

            if ("T".equals(conecta.rs.getString("ar_condicionado"))) {
                jRBt_arC.setSelected(true);
                ok++;
            } else {
                jRBt_arC.setSelected(!true);
            }
            if (ok == 3) {
                jRBt_completo.setSelected(true);
            }
            jTxtA_obs.setText(conecta.rs.getString("obs"));
            jTxt_valor_pago.setText(Fd.format(new BigDecimal(conecta.rs.getString("valor_pago"))));
            jTxt_valor_venda.setText(Fd.format(new BigDecimal(conecta.rs.getString("valor_venda"))));

            if (new File("Imagens\\" + conecta.rs.getString("foto")).exists()) {
                URL_Foto = conecta.rs.getString("foto");
                imagem.setIcon(new ImageIcon(new ImageIcon(("Imagens\\" + conecta.rs.getString("foto"))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));

            } else {
                imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
            }

            if (!"SIM".equals(jTbl_compra.getValueAt(jTbl_compra.getSelectedRow(), 1))) {
                jBtt_anula.setEnabled(true);
                jBtt_excluir.setEnabled(!true);
            } else {
                jBtt_anula.setEnabled(!true);
                jBtt_excluir.setEnabled(true);
            }
            PreencherComboFun("select nome from tb_funcionarios where id_funcionario = '" + Funcionarios + "'");
            jBtt_novo.setEnabled(false);
            jBtt_salvar.setEnabled(false);
            jBtt_cancelar.setEnabled(true);
            jBtt_imprimir.setEnabled(true);
            HabilitaDesabilitaCampos(0);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados do registro!\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }

}
