/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ControleCidade;
import Controle.Maiuscula;
import Controle.ModeloTabela;
import Controle.cadastro;
import Modelo.ModeloCidade;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Murylo César Souza
 */
public class JIFCidades extends javax.swing.JInternalFrame {

    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco conCid = new ConectaBanco();

    ControleCidade concid = new ControleCidade();
    ModeloCidade model = new ModeloCidade();
    cadastro obj_config = new cadastro();
    int flag = 0, Pesquisa;

    /**
     * Creates new form JIFCidades
     */
    /**
     * Creates new form JIFCidades
     *
     * @param pesquisa
     */
    public JIFCidades(int pesquisa) {
        initComponents();
        obj_config.carregaconfig();
        jTxt_nome.setDocument(new Maiuscula(45));
        jTxt_pesquisa.setDocument(new Maiuscula(45));
        Pesquisa = pesquisa;
        conecta.Conexao(obj_config._url);
        preencherTabela("select * from tb_cidades order by id_cidade");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTxt_codigo = new javax.swing.JTextField();
        jTxt_nome = new javax.swing.JTextField();
        jBtt_primeiro = new javax.swing.JButton();
        jBtt_anterior = new javax.swing.JButton();
        jBtt_proximo = new javax.swing.JButton();
        jBtt_ultimo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCbx_uf = new javax.swing.JComboBox();
        jBtt_novo = new javax.swing.JButton();
        jBtt_salvar = new javax.swing.JButton();
        jBtt_excluir = new javax.swing.JButton();
        jBtt_editar = new javax.swing.JButton();
        jBtt_cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_cidades = new javax.swing.JTable();
        jTxt_pesquisa = new javax.swing.JTextField();
        jBtt_pesquisar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Cadastro de cidades");

        jLabel2.setText("Código");

        jLabel1.setText("Nome");

        jTxt_codigo.setEnabled(false);

        jTxt_nome.setEnabled(false);

        jBtt_primeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/first.png"))); // NOI18N
        jBtt_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_primeiroActionPerformed(evt);
            }
        });

        jBtt_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/leftarrow.png"))); // NOI18N
        jBtt_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_anteriorActionPerformed(evt);
            }
        });

        jBtt_proximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/next.png"))); // NOI18N
        jBtt_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_proximoActionPerformed(evt);
            }
        });

        jBtt_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/last.png"))); // NOI18N
        jBtt_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_ultimoActionPerformed(evt);
            }
        });

        jLabel3.setText("Estado");

        jCbx_uf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "FN", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        jCbx_uf.setEnabled(false);

        jBtt_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/new.png"))); // NOI18N
        jBtt_novo.setText("Novo");
        jBtt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_novoActionPerformed(evt);
            }
        });

        jBtt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save.png"))); // NOI18N
        jBtt_salvar.setText("Salvar");
        jBtt_salvar.setEnabled(false);
        jBtt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_salvarActionPerformed(evt);
            }
        });

        jBtt_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/del.png"))); // NOI18N
        jBtt_excluir.setText("Excluir");
        jBtt_excluir.setEnabled(false);
        jBtt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_excluirActionPerformed(evt);
            }
        });

        jBtt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jBtt_editar.setText("Editar");
        jBtt_editar.setEnabled(false);
        jBtt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_editarActionPerformed(evt);
            }
        });

        jBtt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancela.png"))); // NOI18N
        jBtt_cancelar.setText("Cancelar");
        jBtt_cancelar.setEnabled(false);
        jBtt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_cancelarActionPerformed(evt);
            }
        });

        jTbl_cidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTbl_cidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_cidadesMouseClicked(evt);
            }
        });
        jTbl_cidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbl_cidadesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTbl_cidades);

        jTxt_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxt_pesquisaKeyReleased(evt);
            }
        });

        jBtt_pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        jBtt_pesquisar.setText("Pesquisar");
        jBtt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_pesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtt_primeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtt_anterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtt_proximo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTxt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtt_ultimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCbx_uf, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxt_pesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(jBtt_pesquisar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtt_novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtt_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtt_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtt_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtt_cancelar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtt_anterior, jBtt_primeiro, jBtt_proximo, jBtt_ultimo});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtt_cancelar, jBtt_editar, jBtt_excluir, jBtt_novo, jBtt_salvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBtt_proximo)
                        .addComponent(jBtt_ultimo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBtt_primeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtt_anterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTxt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jCbx_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtt_salvar)
                    .addComponent(jBtt_editar)
                    .addComponent(jBtt_excluir)
                    .addComponent(jBtt_cancelar)
                    .addComponent(jBtt_novo))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtt_pesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtt_anterior, jBtt_primeiro, jBtt_proximo, jBtt_ultimo});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTxt_codigo, jTxt_nome});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtt_cancelar, jBtt_editar, jBtt_excluir, jBtt_novo, jBtt_salvar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_novoActionPerformed

        limpaCampos();
        flag = 0;

        conecta.executaSQL("select * from tb_cidades order by id_cidade");

        try {
            if (!conecta.rs.last()) {
                jTxt_codigo.setText("1");
            } else {
                jTxt_codigo.setText(String.valueOf(conecta.rs.getInt("id_cidade") + 1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir registro!");
        }

        jTxt_nome.setEnabled(true);
        jCbx_uf.setEnabled(true);
        jBtt_novo.setEnabled(false);
        jBtt_salvar.setEnabled(true);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(true);
        jTxt_pesquisa.setEnabled(false);
        jBtt_pesquisar.setEnabled(false);
    }//GEN-LAST:event_jBtt_novoActionPerformed

    private void jBtt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_salvarActionPerformed

        char[] validaData = jTxt_nome.getText().toCharArray();
        int ok = 0;
        for (int n = 0; n < jTxt_nome.getText().length(); n++) {
            if (validaData[n] == ' ') {
                ok++;
            }
        }
        if (ok != jTxt_nome.getText().length()) {

            jTxt_nome.setEnabled(false);
            jCbx_uf.setEnabled(false);
            jBtt_novo.setEnabled(true);
            jBtt_salvar.setEnabled(false);
            jBtt_editar.setEnabled(false);
            jBtt_excluir.setEnabled(false);
            jBtt_cancelar.setEnabled(false);
            model.setCodigo(Integer.parseInt(jTxt_codigo.getText()));
            model.setNome(jTxt_nome.getText());
            model.setUf((String) jCbx_uf.getSelectedItem());
            if (flag == 0) {
                concid.GravarCidade(model);
            } else {
                concid.AlterarCidade(model);
            }
            limpaCampos();
            preencherTabela("select * from tb_cidades order by id_cidade");
            jTxt_pesquisa.setEnabled(true);
            jBtt_pesquisar.setEnabled(true);
            if (Pesquisa != 0) {
                conCid.Conexao(obj_config._url);
                conCid.executaSQL("select * from tb_cidades order by nome");
                try {
                    conCid.rs.first();
                    if (Pesquisa == 1) {
                        JIFCliente_fornecedor.jCbx_cidade.removeAllItems();
                    } else if (Pesquisa == 2) {
                        JIFuncionarios.jCbx_cidade.removeAllItems();
                    } else {
                        JIFDados_Empresa.jCbx_cidade.removeAllItems();
                    }

                    do {
                        if (Pesquisa == 1) {
                            JIFCliente_fornecedor.jCbx_cidade.addItem(conCid.rs.getString("nome"));
                        } else if (Pesquisa == 2) {
                            JIFuncionarios.jCbx_cidade.addItem(conCid.rs.getString("nome"));
                        } else {
                            JIFDados_Empresa.jCbx_cidade.addItem(conCid.rs.getString("nome"));
                        }

                    } while (conCid.rs.next());

                } catch (SQLException ex) {

                }
                conCid.Desconecta();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha o nome!", "Erro", JOptionPane.ERROR_MESSAGE);
            jTxt_nome.setText("");
        }
    }//GEN-LAST:event_jBtt_salvarActionPerformed

    private void jBtt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_excluirActionPerformed
        jTxt_nome.setEnabled(false);
        jCbx_uf.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);

        concid.ExcluirCidade(Integer.parseInt(jTxt_codigo.getText()));
        limpaCampos();
        preencherTabela("select * from tb_cidades order by id_cidade");
        jTxt_pesquisa.setEnabled(true);
        jBtt_pesquisar.setEnabled(true);

        if (Pesquisa != 0) {
            conCid.Conexao(obj_config._url);
            conCid.executaSQL("select nome ,uf from tb_cidades order by nome");
            try {
                conCid.rs.first();
                if (Pesquisa == 1) {
                    JIFCliente_fornecedor.jCbx_cidade.removeAllItems();
                } else if (Pesquisa == 2) {
                    JIFuncionarios.jCbx_cidade.removeAllItems();
                } else {
                    JIFDados_Empresa.jCbx_cidade.removeAllItems();
                    JIFDados_Empresa.uf.setText(String.valueOf(conCid.rs.getString("uf")));
                }

                do {
                    if (Pesquisa == 1) {
                        JIFCliente_fornecedor.jCbx_cidade.addItem(conCid.rs.getString("nome"));
                    } else if (Pesquisa == 2) {
                        JIFuncionarios.jCbx_cidade.addItem(conCid.rs.getString("nome"));
                    } else {
                        JIFDados_Empresa.jCbx_cidade.addItem(conCid.rs.getString("nome"));
                    }

                } while (conCid.rs.next());

            } catch (SQLException ex) {

            }
            conCid.Desconecta();
        }

    }//GEN-LAST:event_jBtt_excluirActionPerformed

    private void jBtt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_editarActionPerformed

        flag = 1;
        jTxt_nome.setEnabled(true);
        jCbx_uf.setEnabled(true);
        jBtt_novo.setEnabled(false);
        jBtt_salvar.setEnabled(true);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(true);
        jTxt_pesquisa.setEnabled(false);
        jBtt_pesquisar.setEnabled(false);
    }//GEN-LAST:event_jBtt_editarActionPerformed

    private void jBtt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_cancelarActionPerformed
        limpaCampos();
        jTxt_nome.setEnabled(false);
        jCbx_uf.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);
        jTxt_pesquisa.setEnabled(true);
        jBtt_pesquisar.setEnabled(true);
        preencherTabela("select * from tb_cidades order by id_cidade");
    }//GEN-LAST:event_jBtt_cancelarActionPerformed

    private void jBtt_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_primeiroActionPerformed
        jTxt_nome.setEnabled(false);
        jCbx_uf.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(true);
        jBtt_excluir.setEnabled(true);
        jBtt_cancelar.setEnabled(true);
        model = concid.Primeiro();
        jTxt_codigo.setText(String.valueOf(model.getCodigo()));
        jTxt_nome.setText(model.getNome());
        jCbx_uf.setSelectedItem(model.getUf());
        jTxt_pesquisa.setEnabled(true);
        jBtt_pesquisar.setEnabled(true);
    }//GEN-LAST:event_jBtt_primeiroActionPerformed

    private void jBtt_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_anteriorActionPerformed
        jTxt_nome.setEnabled(false);
        jCbx_uf.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(true);
        jBtt_excluir.setEnabled(true);
        jBtt_cancelar.setEnabled(true);
        model = concid.Anterior();
        jTxt_codigo.setText(String.valueOf(model.getCodigo()));
        jTxt_nome.setText(model.getNome());
        jCbx_uf.setSelectedItem(model.getUf());
        jTxt_pesquisa.setEnabled(true);
        jBtt_pesquisar.setEnabled(true);
    }//GEN-LAST:event_jBtt_anteriorActionPerformed

    private void jBtt_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_proximoActionPerformed
        jTxt_nome.setEnabled(false);
        jCbx_uf.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(true);
        jBtt_excluir.setEnabled(true);
        jBtt_cancelar.setEnabled(true);
        model = concid.Proximo();
        jTxt_codigo.setText(String.valueOf(model.getCodigo()));
        jTxt_nome.setText(model.getNome());
        jCbx_uf.setSelectedItem(model.getUf());
        jTxt_pesquisa.setEnabled(true);
        jBtt_pesquisar.setEnabled(true);
    }//GEN-LAST:event_jBtt_proximoActionPerformed

    private void jBtt_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_ultimoActionPerformed

        jTxt_nome.setEnabled(false);
        jCbx_uf.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(true);
        jBtt_excluir.setEnabled(true);
        jBtt_cancelar.setEnabled(true);
        model = concid.Ultimo();
        jTxt_codigo.setText(String.valueOf(model.getCodigo()));
        jTxt_nome.setText(model.getNome());
        jCbx_uf.setSelectedItem(model.getUf());
        jTxt_pesquisa.setEnabled(true);
        jBtt_pesquisar.setEnabled(true);
    }//GEN-LAST:event_jBtt_ultimoActionPerformed

    private void jTbl_cidadesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbl_cidadesKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            atualizaTabela();
        }
    }//GEN-LAST:event_jTbl_cidadesKeyReleased

    private void jTbl_cidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_cidadesMouseClicked
        atualizaTabela();
    }//GEN-LAST:event_jTbl_cidadesMouseClicked

    private void jBtt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_pesquisarActionPerformed
        preencherTabela("select * from tb_cidades where nome like '%" + jTxt_pesquisa.getText() + "%' order by id_cidade");
        jTxt_pesquisa.setText("");
    }//GEN-LAST:event_jBtt_pesquisarActionPerformed

    private void jTxt_pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_pesquisaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            preencherTabela("select * from tb_cidades where nome like '%" + jTxt_pesquisa.getText() + "%' order by id_cidade");
            jTxt_pesquisa.setText("");
        }
    }//GEN-LAST:event_jTxt_pesquisaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtt_anterior;
    private javax.swing.JButton jBtt_cancelar;
    private javax.swing.JButton jBtt_editar;
    private javax.swing.JButton jBtt_excluir;
    private javax.swing.JButton jBtt_novo;
    private javax.swing.JButton jBtt_pesquisar;
    private javax.swing.JButton jBtt_primeiro;
    private javax.swing.JButton jBtt_proximo;
    private javax.swing.JButton jBtt_salvar;
    private javax.swing.JButton jBtt_ultimo;
    private javax.swing.JComboBox jCbx_uf;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTbl_cidades;
    private javax.swing.JTextField jTxt_codigo;
    private javax.swing.JTextField jTxt_nome;
    private javax.swing.JTextField jTxt_pesquisa;
    // End of variables declaration//GEN-END:variables

    public void limpaCampos() {
        jTxt_codigo.setText("");
        jTxt_nome.setText("");
    }

    public void preencherTabela(String SQL) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Nome da Cidade", "Estado"};
        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();

            do {
                dados.add(new Object[]{conecta.rs.getInt("id_cidade"), conecta.rs.getString("nome"), conecta.rs.getString("uf")});

            } while (conecta.rs.next());

        } catch (SQLException ex) {

        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTbl_cidades.setModel(modelo);
        jTbl_cidades.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTbl_cidades.getColumnModel().getColumn(0).setResizable(false);
        jTbl_cidades.getColumnModel().getColumn(1).setPreferredWidth(388);
        jTbl_cidades.getColumnModel().getColumn(1).setResizable(false);
        jTbl_cidades.getColumnModel().getColumn(2).setPreferredWidth(70);
        jTbl_cidades.getColumnModel().getColumn(2).setResizable(false);
        jTbl_cidades.getTableHeader().setReorderingAllowed(false);
        jTbl_cidades.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTbl_cidades.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void atualizaTabela() {
        conecta.Conexao(obj_config._url);
        conecta.executaSQL("select * from tb_cidades where id_cidade = '" + jTbl_cidades.getValueAt(jTbl_cidades.getSelectedRow(), 0) + "'");
        try {
            conecta.rs.first();
            jTxt_codigo.setText(String.valueOf(conecta.rs.getInt("id_cidade")));
            jTxt_nome.setText(conecta.rs.getString("nome"));
            jCbx_uf.setSelectedItem(conecta.rs.getString("uf"));
            jTxt_nome.setEnabled(false);
            jCbx_uf.setEnabled(false);
            jBtt_novo.setEnabled(false);
            jBtt_salvar.setEnabled(false);
            jBtt_editar.setEnabled(true);
            jBtt_excluir.setEnabled(true);
            jBtt_cancelar.setEnabled(true);
            jTxt_pesquisa.setEnabled(true);
            jBtt_pesquisar.setEnabled(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados do registro!\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }
}
