/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ControleDes_Car;
import Controle.Maiuscula;
import Controle.ModeloTabela;
import Controle.Validacoes;
import Controle.Numeric;
import Controle.cadastro;
import Modelo.ModeloDes_Car;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Murylo César Souza
 */
public class JIFDesp_Cars extends javax.swing.JInternalFrame {

    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco conMod = new ConectaBanco();
    ConectaBanco conVei = new ConectaBanco();
    ControleDes_Car desp = new ControleDes_Car();
    ModeloDes_Car model = new ModeloDes_Car();
    cadastro obj_config = new cadastro();

    MaskFormatter formatoData;

    Validacoes validar = new Validacoes();
    int flag = 0;
    int id_veiculo;
    Double Valor;

    /**
     * Creates new form JIFDesp_Cars
     */
    public JIFDesp_Cars() {
        initComponents();
        obj_config.carregaconfig();
        jTxt_descricao.setDocument(new Maiuscula(60));
        jTxt_valor.setDocument(new Numeric(15));
        jTxt_pesquisa.setDocument(new Maiuscula(60));

        preencherTabela("select * from tb_veiculos where status = 'T' order by id_veiculo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTbl_Veiculos = new javax.swing.JTable();
        jTxt_codigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        try{
            formatoData= new MaskFormatter("##/##/####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_datacad = new JFormattedTextField(formatoData);
        ;
        jLabel3 = new javax.swing.JLabel();
        jTxt_descricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxt_valor = new javax.swing.JTextField();
        jBtt_pesquisar = new javax.swing.JButton();
        jTxt_pesquisa = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTbl_despesa_car = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jBtt_cancelar = new javax.swing.JButton();
        jBtt_excluir = new javax.swing.JButton();
        jBtt_editar = new javax.swing.JButton();
        jBtt_salvar = new javax.swing.JButton();
        jBtt_novo = new javax.swing.JButton();

        setClosable(true);
        setTitle("Despesa de veiculos");

        jTbl_Veiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTbl_Veiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_VeiculosMouseClicked(evt);
            }
        });
        jTbl_Veiculos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbl_VeiculosKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTbl_Veiculos);

        jTxt_codigo.setEnabled(false);

        jLabel1.setText("Código");

        jLabel2.setText("Data");

        jFTxt_datacad.setEnabled(false);

        jLabel3.setText("Descrição");

        jTxt_descricao.setEnabled(false);

        jLabel4.setText("Valor");

        jTxt_valor.setEnabled(false);

        jBtt_pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        jBtt_pesquisar.setText("Pesquisar");
        jBtt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_pesquisarActionPerformed(evt);
            }
        });

        jTxt_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_pesquisaKeyTyped(evt);
            }
        });

        jTbl_despesa_car.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTbl_despesa_car.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_despesa_carMouseClicked(evt);
            }
        });
        jTbl_despesa_car.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbl_despesa_carKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTbl_despesa_car);

        jBtt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancela.png"))); // NOI18N
        jBtt_cancelar.setText("Cancelar");
        jBtt_cancelar.setEnabled(false);
        jBtt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_cancelarActionPerformed(evt);
            }
        });

        jBtt_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/del.png"))); // NOI18N
        jBtt_excluir.setText("Excluir");
        jBtt_excluir.setEnabled(false);
        jBtt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_excluirActionPerformed(evt);
            }
        });

        jBtt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jBtt_editar.setText("Editar");
        jBtt_editar.setEnabled(false);
        jBtt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_editarActionPerformed(evt);
            }
        });

        jBtt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save.png"))); // NOI18N
        jBtt_salvar.setText("Salvar");
        jBtt_salvar.setEnabled(false);
        jBtt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_salvarActionPerformed(evt);
            }
        });

        jBtt_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/new.png"))); // NOI18N
        jBtt_novo.setText("Novo");
        jBtt_novo.setEnabled(false);
        jBtt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_novoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jFTxt_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtt_novo)
                        .addGap(18, 18, 18)
                        .addComponent(jBtt_salvar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtt_editar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtt_excluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtt_cancelar)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTxt_pesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(jBtt_pesquisar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jFTxt_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTxt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTxt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtt_salvar)
                    .addComponent(jBtt_editar)
                    .addComponent(jBtt_excluir)
                    .addComponent(jBtt_cancelar)
                    .addComponent(jBtt_novo))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtt_pesquisar)
                    .addComponent(jTxt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_pesquisarActionPerformed
        HabilitaDesabilitaCampos(!true);
        try {
            preencherTabelaDes("select * from tb_car_desp  where id_veiculo =" + jTbl_Veiculos.getValueAt(jTbl_Veiculos.getSelectedRow(), 0) + " and descricao  like '%" + jTxt_pesquisa.getText() + "%' order by id_car");
            jTxt_pesquisa.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione o veiculo de saida!", "Erro!", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jBtt_pesquisarActionPerformed

    private void jBtt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_cancelarActionPerformed

        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);
        limpaCampos();
        HabilitaDesabilitaCampos(!true);
        preencherTabela("select * from tb_veiculos where status = 'T' order by id_veiculo");
    }//GEN-LAST:event_jBtt_cancelarActionPerformed

    private void jBtt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_excluirActionPerformed

        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);
        model.setId_codigo(Integer.parseInt(jTxt_codigo.getText()));
        model.setValor(Double.valueOf(jTxt_valor.getText()) * -1);
        try {
            model.setId_veiculo((int) jTbl_Veiculos.getValueAt(jTbl_Veiculos.getSelectedRow(), 0));
            desp.ExcluirDesp_car(model);
            limpaCampos();
            HabilitaDesabilitaCampos(!true);
            preencherTabelaDes("select * from tb_car_desp  where id_veiculo =" + (int) jTbl_Veiculos.getValueAt(jTbl_Veiculos.getSelectedRow(), 0) + "order by id_car");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione o veículo de saida!" + ex, "Erro!", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jBtt_excluirActionPerformed

    private void jBtt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_editarActionPerformed
        flag = 1;
        Valor = Double.valueOf(jTxt_valor.getText());
        jBtt_novo.setEnabled(false);
        jBtt_salvar.setEnabled(true);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(true);
        HabilitaDesabilitaCampos(true);
    }//GEN-LAST:event_jBtt_editarActionPerformed

    private void jBtt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_salvarActionPerformed

        if (PrencherObjeto()) {
            conecta.Desconecta();
            jBtt_novo.setEnabled(true);
            jBtt_salvar.setEnabled(false);
            jBtt_editar.setEnabled(false);
            jBtt_excluir.setEnabled(false);
            jBtt_cancelar.setEnabled(false);

            if (flag == 0) {
                desp.GravarDesp_car(model);
            } else {
                model.setValor(model.getValor() - Valor);
                desp.AlterarDesp_car(model);
            }

            limpaCampos();
            HabilitaDesabilitaCampos(!true);
            preencherTabelaDes("select * from tb_car_desp  where id_veiculo =" + (int) jTbl_Veiculos.getValueAt(jTbl_Veiculos.getSelectedRow(), 0) + "order by id_car");
        }

    }//GEN-LAST:event_jBtt_salvarActionPerformed

    private void jBtt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_novoActionPerformed
        jBtt_novo.setEnabled(false);
        jBtt_salvar.setEnabled(true);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(true);
        limpaCampos();
        HabilitaDesabilitaCampos(true);
        flag = 0;
        conecta.Conexao(obj_config._url);
        conecta.executaSQL("select id_car from tb_car_desp order by id_car");

        try {
            if (!conecta.rs.last()) {
                jTxt_codigo.setText("1");
            } else {
                jTxt_codigo.setText(String.valueOf(conecta.rs.getInt("id_car") + 1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir registro!" + ex);
        }
        java.util.Date datahoje = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        jFTxt_datacad.setText(df.format(datahoje));

    }//GEN-LAST:event_jBtt_novoActionPerformed

    private void jTbl_VeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_VeiculosMouseClicked
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);
        jBtt_novo.setEnabled(true);
        preencherTabelaDes("select * from tb_car_desp  where id_veiculo =" + jTbl_Veiculos.getValueAt(jTbl_Veiculos.getSelectedRow(), 0) + "order by id_car");
    }//GEN-LAST:event_jTbl_VeiculosMouseClicked

    private void jTbl_VeiculosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbl_VeiculosKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            preencherTabelaDes("select * from tb_car_desp  where id_veiculo =" + jTbl_Veiculos.getValueAt(jTbl_Veiculos.getSelectedRow(), 0) + "order by id_car");
            jBtt_novo.setEnabled(true);
            jBtt_salvar.setEnabled(false);
            jBtt_editar.setEnabled(false);
            jBtt_excluir.setEnabled(false);
            jBtt_cancelar.setEnabled(false);
            jBtt_novo.setEnabled(true);
        }
    }//GEN-LAST:event_jTbl_VeiculosKeyReleased

    private void jTbl_despesa_carKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbl_despesa_carKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            atualizaTabela();
        }
    }//GEN-LAST:event_jTbl_despesa_carKeyReleased

    private void jTbl_despesa_carMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_despesa_carMouseClicked
        atualizaTabela();
    }//GEN-LAST:event_jTbl_despesa_carMouseClicked

    private void jTxt_pesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_pesquisaKeyTyped
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            HabilitaDesabilitaCampos(!true);
            preencherTabelaDes("select * from tb_car_desp  where id_veiculo =" + jTbl_Veiculos.getValueAt(jTbl_Veiculos.getSelectedRow(), 0) + " and descricao  like '%" + jTxt_pesquisa.getText() + "%' order by id_car");
            jTxt_pesquisa.setText("");
        }
    }//GEN-LAST:event_jTxt_pesquisaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtt_cancelar;
    private javax.swing.JButton jBtt_editar;
    private javax.swing.JButton jBtt_excluir;
    private javax.swing.JButton jBtt_novo;
    private javax.swing.JButton jBtt_pesquisar;
    private javax.swing.JButton jBtt_salvar;
    private javax.swing.JFormattedTextField jFTxt_datacad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTbl_Veiculos;
    private javax.swing.JTable jTbl_despesa_car;
    private javax.swing.JTextField jTxt_codigo;
    private javax.swing.JTextField jTxt_descricao;
    private javax.swing.JTextField jTxt_pesquisa;
    private javax.swing.JTextField jTxt_valor;
    // End of variables declaration//GEN-END:variables

    public void limpaCampos() {
        jTxt_codigo.setText("");
        jFTxt_datacad.setText("");
        jTxt_descricao.setText("");
        jTxt_valor.setText("");

    }

    public void HabilitaDesabilitaCampos(boolean acao) {

        if (acao) {
            jTxt_descricao.setEnabled(true);
            jTxt_valor.setEnabled(true);
            jTxt_pesquisa.setEnabled(false);
            jBtt_pesquisar.setEnabled(false);
        } else {
            jTxt_descricao.setEnabled(!true);
            jTxt_valor.setEnabled(!true);
            jTxt_pesquisa.setEnabled(true);
            jBtt_pesquisar.setEnabled(true);
        }
    }

    public boolean PrencherObjeto() {

        model.setId_codigo(Integer.parseInt(jTxt_codigo.getText()));

        try {
            model.setId_veiculo((int) jTbl_Veiculos.getValueAt(jTbl_Veiculos.getSelectedRow(), 0));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione o veiculo de saida!", "Erro!", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        try {
            model.setData((Date) validar.formDataStrToData(jFTxt_datacad.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro na data!");
        }

        char[] validaData = jTxt_descricao.getText().toCharArray();
        int ok = 0;
        for (int n = 0; n < jTxt_descricao.getText().length(); n++) {
            if (validaData[n] == ' ') {
                ok++;
            }
        }
        if (ok == jTxt_descricao.getText().length()) {
            JOptionPane.showMessageDialog(null, "Preencha o nome!", "Erro!", JOptionPane.ERROR_MESSAGE);
            jTxt_descricao.setText("");
            return false;
        }

        model.setDescricao(jTxt_descricao.getText());

        if (("".equals(jTxt_valor.getText()))) {
            JOptionPane.showMessageDialog(null, "Complete o campo no valor", "Atenção", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        model.setValor(Double.valueOf(jTxt_valor.getText().replaceAll("\\.", "").replaceAll("\\,", ".")));

        return true;

    }

    public void preencherTabelaDes(String SQL) {
        HabilitaDesabilitaCampos(false);
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Data", "Descricão", "Valor"};
        conecta.Conexao(obj_config._url);
        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();

            do {
                dados.add(new Object[]{conecta.rs.getInt("id_car"), validar.formDataDateToStr(conecta.rs.getDate("data")), conecta.rs.getString("descricao"), conecta.rs.getDouble("valor")});

            } while (conecta.rs.next());

        } catch (SQLException ex) {

        }
        conecta.Desconecta();
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTbl_despesa_car.setModel(modelo);
        jTbl_despesa_car.getColumnModel().getColumn(0).setPreferredWidth(50);//90
        jTbl_despesa_car.getColumnModel().getColumn(0).setResizable(false);
        jTbl_despesa_car.getColumnModel().getColumn(1).setPreferredWidth(100);//420
        jTbl_despesa_car.getColumnModel().getColumn(1).setResizable(false);
        jTbl_despesa_car.getColumnModel().getColumn(2).setPreferredWidth(597);
        jTbl_despesa_car.getColumnModel().getColumn(2).setResizable(false);
        jTbl_despesa_car.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTbl_despesa_car.getColumnModel().getColumn(3).setResizable(false);
        jTbl_despesa_car.getTableHeader().setReorderingAllowed(false);
        jTbl_despesa_car.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTbl_despesa_car.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void preencherTabela(String SQL) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Marca", "Modelo", "Versão", "Placa", "chassi"};
        conecta.Conexao(obj_config._url);
        conecta.executaSQL(SQL);
        conMod.Conexao(obj_config._url);
        try {
            conecta.rs.first();
            id_veiculo = conecta.rs.getInt("id_veiculo");
            do {
                conMod.executaSQL("select descricao from tb_modelos where id_modelo = " + conecta.rs.getInt("modelo"));
                conMod.rs.first();
                dados.add(new Object[]{conecta.rs.getInt("id_veiculo"), conecta.rs.getString("marca"), conMod.rs.getString("descricao"), conecta.rs.getString("versao"), conecta.rs.getString("placa"), conecta.rs.getString("chassi")});

            } while (conecta.rs.next());

        } catch (SQLException ex) {
            jBtt_novo.setEnabled(false);
        }
        conMod.Desconecta();
        conecta.Desconecta();
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTbl_Veiculos.setModel(modelo);
        jTbl_Veiculos.getColumnModel().getColumn(0).setPreferredWidth(50);//90
        jTbl_Veiculos.getColumnModel().getColumn(0).setResizable(false);
        jTbl_Veiculos.getColumnModel().getColumn(1).setPreferredWidth(197);//420
        jTbl_Veiculos.getColumnModel().getColumn(1).setResizable(false);
        jTbl_Veiculos.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTbl_Veiculos.getColumnModel().getColumn(2).setResizable(false);
        jTbl_Veiculos.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTbl_Veiculos.getColumnModel().getColumn(3).setResizable(false);
        jTbl_Veiculos.getColumnModel().getColumn(4).setPreferredWidth(90);
        jTbl_Veiculos.getColumnModel().getColumn(4).setResizable(false);
        jTbl_Veiculos.getColumnModel().getColumn(5).setPreferredWidth(90);
        jTbl_Veiculos.getColumnModel().getColumn(5).setResizable(false);
        jTbl_Veiculos.getTableHeader().setReorderingAllowed(false);
        jTbl_Veiculos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTbl_Veiculos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void atualizaTabela() {
        HabilitaDesabilitaCampos(!true);
        String codigo = "" + jTbl_despesa_car.getValueAt(jTbl_despesa_car.getSelectedRow(), 0);
        conecta.Conexao(obj_config._url);
        conecta.executaSQL("select * from tb_car_desp where id_car = '" + codigo + "'");
        try {
            conecta.rs.first();
            jTxt_codigo.setText(String.valueOf(conecta.rs.getInt("id_car")));
            jFTxt_datacad.setText(validar.formDataDateToStr(conecta.rs.getDate("data")));
            jTxt_descricao.setText(conecta.rs.getString("descricao"));
            jTxt_valor.setText(String.valueOf(conecta.rs.getDouble("valor")));
            jBtt_novo.setEnabled(false);
            jBtt_salvar.setEnabled(false);
            jBtt_editar.setEnabled(true);
            jBtt_excluir.setEnabled(true);
            jBtt_cancelar.setEnabled(true);
            jTxt_pesquisa.setEnabled(true);
            jBtt_pesquisar.setEnabled(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados do registro!" + ex, "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        conecta.Desconecta();

    }
}
