/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.Dados_empresa;
import Controle.Maiuscula;
import Controle.cadastro;
import java.awt.HeadlessException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.sql.SQLException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Murylo
 */
public class JIFDados_Empresa extends javax.swing.JInternalFrame {

    MaskFormatter Fone;
    cadastro obj_config = new cadastro();
    Dados_empresa obj_dados = new Dados_empresa();
    ConectaBanco conCid = new ConectaBanco();

    boolean carregar = false;

    /**
     * Creates new form Dados_Empresa
     */
    public JIFDados_Empresa() {
        initComponents();

        obj_config.carregaconfig();

        PreencherCombo();
        jTxt_nome.setDocument(new Maiuscula(33));
        jTxt_bairro.setDocument(new Maiuscula(33));
        jTxt_endereco.setDocument(new Maiuscula(33));
        jTxt_email.setDocument(new Maiuscula(50));

        if (obj_dados.carregaconfig(true)) {

            jTxt_nome.setText(obj_dados._nome);
            uf.setText(obj_dados._uf);
            jCbx_cidade.setSelectedItem((String) obj_dados._cidade);
            jTxt_bairro.setText(obj_dados._bairro);
            jTxt_endereco.setText(obj_dados._endereco);
            jTxt_fone.setText(obj_dados._fone);
            jTxt_fone2.setText(obj_dados._fone2);
            jTxt_email.setText(obj_dados._e_mail);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxt_nome = new javax.swing.JTextField();
        jTxt_endereco = new javax.swing.JTextField();
        try{
            Fone= new MaskFormatter("(##) 9####-####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jTxt_fone = new JFormattedTextField(Fone);
        ;
        try{
            Fone= new MaskFormatter("(##) 9####-####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jTxt_fone2 = new JFormattedTextField(Fone);
        ;
        jTxt_email = new javax.swing.JTextField();
        jBtt_Gravar = new javax.swing.JButton();
        jBtt_Editar = new javax.swing.JButton();
        jBtt_cancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jCbx_cidade = new javax.swing.JComboBox();
        jRBt_Cidades = new javax.swing.JButton();
        jTxt_bairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        uf = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dados da Empresa");

        jLabel2.setText("Nome:");

        jLabel3.setText("Endereço");

        jLabel4.setText("Fone");

        jLabel5.setText("Fone");

        jLabel6.setText("E-mail");

        jTxt_nome.setEnabled(false);

        jTxt_endereco.setEnabled(false);

        jTxt_fone.setEnabled(false);

        jTxt_fone2.setEnabled(false);

        jTxt_email.setEnabled(false);

        jBtt_Gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save.png"))); // NOI18N
        jBtt_Gravar.setText("Salva");
        jBtt_Gravar.setEnabled(false);
        jBtt_Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_GravarActionPerformed(evt);
            }
        });

        jBtt_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jBtt_Editar.setText("Editar");
        jBtt_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_EditarActionPerformed(evt);
            }
        });

        jBtt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancela.png"))); // NOI18N
        jBtt_cancelar.setText("Cancelar");
        jBtt_cancelar.setEnabled(false);
        jBtt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_cancelarActionPerformed(evt);
            }
        });

        jLabel7.setText("Cidade");

        jCbx_cidade.setEnabled(false);
        jCbx_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbx_cidadeActionPerformed(evt);
            }
        });

        jRBt_Cidades.setText("+");
        jRBt_Cidades.setEnabled(false);
        jRBt_Cidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBt_CidadesActionPerformed(evt);
            }
        });

        jTxt_bairro.setEnabled(false);

        jLabel8.setText("Bairro");

        uf.setText("XX");

        jLabel9.setText("UF:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTxt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTxt_endereco))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCbx_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(uf)
                                .addGap(18, 18, 18)
                                .addComponent(jRBt_Cidades)
                                .addGap(8, 8, 8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtt_Gravar)
                        .addGap(44, 44, 44)
                        .addComponent(jBtt_Editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtt_cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTxt_fone, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxt_fone2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTxt_email)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtt_Editar, jBtt_Gravar, jBtt_cancelar});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTxt_bairro, jTxt_email, jTxt_endereco, jTxt_nome});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCbx_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRBt_Cidades)
                    .addComponent(uf)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxt_fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_fone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtt_Gravar)
                    .addComponent(jBtt_Editar)
                    .addComponent(jBtt_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, uf});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtt_Editar, jBtt_Gravar, jBtt_cancelar});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCbx_cidade, jTxt_bairro, jTxt_email, jTxt_endereco, jTxt_fone, jTxt_fone2, jTxt_nome});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBt_CidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBt_CidadesActionPerformed
        JIFCidades janela = new JIFCidades(3);
        Tela.jDesktop.add(janela);
        Tela.centralizaForm(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jRBt_CidadesActionPerformed

    private void jBtt_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_EditarActionPerformed
        HabilitarCampo(true);
    }//GEN-LAST:event_jBtt_EditarActionPerformed

    private void jBtt_GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_GravarActionPerformed
        HabilitarCampo(!true);
        obj_dados.nome = jTxt_nome.getText();
        obj_dados.uf = uf.getText();
        obj_dados.cidade = (String) jCbx_cidade.getSelectedItem();
        obj_dados.bairro = jTxt_bairro.getText();
        obj_dados.endereco = jTxt_endereco.getText();
        obj_dados.fone = jTxt_fone.getText();
        obj_dados.fone2 = jTxt_fone2.getText();
        obj_dados.e_mail = jTxt_email.getText();

        try {
            FileOutputStream arquivo = new FileOutputStream("Dados_Empresa.ini");
            ObjectOutputStream obj_gravacao = new ObjectOutputStream(arquivo);
            obj_gravacao.writeObject(obj_dados);
            obj_gravacao.flush();
            JOptionPane.showMessageDialog(null, "Arquivo de configuração gerado com sucesso!", "configuração", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar gerar o arquivo de configuração!\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtt_GravarActionPerformed

    private void jBtt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_cancelarActionPerformed
        HabilitarCampo(!true);
    }//GEN-LAST:event_jBtt_cancelarActionPerformed

    private void jCbx_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbx_cidadeActionPerformed
        if (carregar) {
            try {
                conCid.Conexao(obj_config._url);
                conCid.executaSQL("select uf from tb_cidades where nome = '" + jCbx_cidade.getSelectedItem() + "'");

                conCid.rs.first();
                uf.setText(String.valueOf(conCid.rs.getString("uf")));
            } catch (SQLException ex) {
            }
            conCid.Desconecta();
        }
        carregar = true;
    }//GEN-LAST:event_jCbx_cidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtt_Editar;
    private javax.swing.JButton jBtt_Gravar;
    private javax.swing.JButton jBtt_cancelar;
    public static javax.swing.JComboBox jCbx_cidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jRBt_Cidades;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxt_bairro;
    private javax.swing.JTextField jTxt_email;
    private javax.swing.JTextField jTxt_endereco;
    private javax.swing.JFormattedTextField jTxt_fone;
    private javax.swing.JFormattedTextField jTxt_fone2;
    private javax.swing.JTextField jTxt_nome;
    public static javax.swing.JLabel uf;
    // End of variables declaration//GEN-END:variables

    public void PreencherCombo() {

        conCid.Conexao(obj_config._url);
        conCid.executaSQL("select nome,uf from tb_cidades order by nome");
        try {
            conCid.rs.first();
            jCbx_cidade.removeAllItems();
            uf.setText(conCid.rs.getString("uf"));
            do {

                jCbx_cidade.addItem(conCid.rs.getString("nome"));

            } while (conCid.rs.next());

        } catch (SQLException ex) {

        }
        conCid.Desconecta();
    }

    public void HabilitarCampo(boolean x) {
        if (x) {
            jTxt_nome.setEnabled(true);
            jCbx_cidade.setEnabled(true);
            jRBt_Cidades.setEnabled(true);
            jTxt_bairro.setEnabled(true);
            jTxt_endereco.setEnabled(true);
            jTxt_fone.setEnabled(true);
            jTxt_fone2.setEnabled(true);
            jTxt_email.setEnabled(true);

            jBtt_Gravar.setEnabled(true);
            jBtt_Editar.setEnabled(false);
            jBtt_cancelar.setEnabled(true);
        } else {
            jTxt_nome.setEnabled(!true);
            jCbx_cidade.setEnabled(!true);
            jRBt_Cidades.setEnabled(!true);
            jTxt_bairro.setEnabled(!true);
            jTxt_endereco.setEnabled(!true);
            jTxt_fone.setEnabled(!true);
            jTxt_fone2.setEnabled(!true);
            jTxt_email.setEnabled(!true);

            jBtt_Gravar.setEnabled(!true);
            jBtt_Editar.setEnabled(!false);
            jBtt_cancelar.setEnabled(!true);
        }

    }
}
