/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ControleTaxas;
import Controle.Maiuscula;
import Controle.ModeloTabela;
import Controle.Validacoes;
import Controle.Numeric;
import Controle.cadastro;
import Modelo.ModeloTaxa;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Murylo César Souza
 */
public class JIFtaxa extends javax.swing.JInternalFrame {

    ConectaBanco control = new ConectaBanco();
    ModeloTaxa mod = new ModeloTaxa();
    ControleTaxas conTaxa = new ControleTaxas();

    Validacoes validar = new Validacoes();
    cadastro obj_config = new cadastro();
    MaskFormatter formatoData, formatoanoM;

    int flag = 0;

    /**
     * Creates new form JFtaxa
     */
    public JIFtaxa() {
        initComponents();
        obj_config.carregaconfig();
        control.Conexao(obj_config._url);
        preencherTabela("select * from tb_taxas where tipo = 'O' order by id_taxa");
        preencherTabelaA("select * from tb_taxas where tipo = 'A' order by id_taxa");
        jTxt_nome.setDocument(new Maiuscula(25));
        jTxt_coeficiente.setDocument(new Numeric(18));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCbx_tipo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCbx_parcela = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jCbx_entrada = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTxt_coeficiente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxt_codigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxt_nome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jBtt_cancelar = new javax.swing.JButton();
        jBtt_excluir = new javax.swing.JButton();
        jBtt_editar = new javax.swing.JButton();
        jBtt_salvar = new javax.swing.JButton();
        jBtt_novo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTbl_taxaObrigatorias = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        try{
            formatoData= new MaskFormatter("##/##/####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_dataCad = new JFormattedTextField(formatoData);
        ;
        jScrollPane5 = new javax.swing.JScrollPane();
        jTbl_taxaObrigatorias1 = new javax.swing.JTable();
        try{
            formatoanoM= new MaskFormatter("##/##");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_ano_modelo = new JFormattedTextField(formatoanoM);
        ;

        setClosable(true);
        setTitle("Taxa");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Safe.jpg"))); // NOI18N

        jLabel1.setText("Taxa");

        jCbx_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Adicional", "Obrigatorio" }));
        jCbx_tipo.setEnabled(false);
        jCbx_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbx_tipoActionPerformed(evt);
            }
        });

        jLabel2.setText("Ano Modelo");

        jLabel4.setText("Parcela");

        jCbx_parcela.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12", "24", "36", "48", "60" }));
        jCbx_parcela.setEnabled(false);

        jLabel5.setText("Entrada");

        jCbx_entrada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0%", "10%", "20%", "30%", "40%", "50%" }));
        jCbx_entrada.setEnabled(false);

        jLabel6.setText("Coeficiente");

        jTxt_coeficiente.setEnabled(false);

        jLabel7.setText("Codigo");

        jTxt_codigo.setEnabled(false);

        jLabel8.setText("Descrição");

        jTxt_nome.setEnabled(false);

        jLabel9.setText("Data Cadastro");

        jBtt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancela.png"))); // NOI18N
        jBtt_cancelar.setText("Cancelar");
        jBtt_cancelar.setToolTipText("Cancelar");
        jBtt_cancelar.setEnabled(false);
        jBtt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_cancelarActionPerformed(evt);
            }
        });

        jBtt_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/del.png"))); // NOI18N
        jBtt_excluir.setText("Excluir");
        jBtt_excluir.setToolTipText("Excluir");
        jBtt_excluir.setEnabled(false);
        jBtt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_excluirActionPerformed(evt);
            }
        });

        jBtt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jBtt_editar.setText("Editar");
        jBtt_editar.setToolTipText("Editar");
        jBtt_editar.setEnabled(false);
        jBtt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_editarActionPerformed(evt);
            }
        });

        jBtt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save.png"))); // NOI18N
        jBtt_salvar.setText("Salvar");
        jBtt_salvar.setToolTipText("Salvar");
        jBtt_salvar.setEnabled(false);
        jBtt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_salvarActionPerformed(evt);
            }
        });

        jBtt_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/new.png"))); // NOI18N
        jBtt_novo.setText("Novo");
        jBtt_novo.setToolTipText("Novo");
        jBtt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_novoActionPerformed(evt);
            }
        });

        jTbl_taxaObrigatorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTbl_taxaObrigatorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_taxaObrigatoriasMouseClicked(evt);
            }
        });
        jTbl_taxaObrigatorias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbl_taxaObrigatoriasKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTbl_taxaObrigatorias);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Adicionais");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Obrigatórios");

        jFTxt_dataCad.setEnabled(false);

        jTbl_taxaObrigatorias1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTbl_taxaObrigatorias1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_taxaObrigatorias1MouseClicked(evt);
            }
        });
        jTbl_taxaObrigatorias1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbl_taxaObrigatorias1KeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(jTbl_taxaObrigatorias1);

        jFTxt_ano_modelo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxt_nome))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCbx_parcela, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCbx_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxt_coeficiente))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCbx_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTxt_dataCad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jFTxt_ano_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jBtt_novo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtt_salvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtt_editar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtt_excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtt_cancelar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jCbx_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jFTxt_dataCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCbx_parcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jCbx_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTxt_coeficiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFTxt_ano_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtt_salvar)
                    .addComponent(jBtt_editar)
                    .addComponent(jBtt_excluir)
                    .addComponent(jBtt_cancelar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtt_novo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel4, jLabel5, jLabel6});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCbx_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbx_tipoActionPerformed
        if (jCbx_tipo.getSelectedItem() == "Obrigatorio") {
            jTxt_nome.setEnabled(true);

            jCbx_parcela.setEnabled(!true);
            jCbx_entrada.setEnabled(!true);
            jLabel6.setText("Valor Taxa");
            jFTxt_ano_modelo.setEnabled(!true);
            jFTxt_ano_modelo.setText("");
        } else {
            jTxt_nome.setEnabled(!true);
            jTxt_nome.setText("");
            jCbx_parcela.setEnabled(true);
            jCbx_entrada.setEnabled(true);
            jLabel6.setText("Coeficiente");
            jFTxt_ano_modelo.setEnabled(true);
        }

    }//GEN-LAST:event_jCbx_tipoActionPerformed

    private void jBtt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_cancelarActionPerformed
        limpaCampos();
        HabilitaDesabilitaCampos(0);
        jTxt_nome.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);
    }//GEN-LAST:event_jBtt_cancelarActionPerformed

    private void jBtt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_excluirActionPerformed
        jTxt_nome.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);
        HabilitaDesabilitaCampos(0);
        mod.setId_taxa(Integer.parseInt(jTxt_codigo.getText()));
        conTaxa.ExcluirTaxa(mod);
        limpaCampos();
        jCbx_parcela.setEnabled(false);
        jCbx_entrada.setEnabled(false);
        jFTxt_ano_modelo.setEnabled(false);
        preencherTabela("select * from tb_taxas where tipo = 'O' order by id_taxa");
        preencherTabelaA("select * from tb_taxas where tipo = 'A' order by id_taxa");

    }//GEN-LAST:event_jBtt_excluirActionPerformed

    private void jBtt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_editarActionPerformed
        HabilitaDesabilitaCampos(1);
        flag = 1;
        jTxt_nome.setEnabled(true);
        jBtt_novo.setEnabled(false);
        jBtt_salvar.setEnabled(true);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(true);
    }//GEN-LAST:event_jBtt_editarActionPerformed

    private void jBtt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_salvarActionPerformed
        if (preencherObjeto()) {
            if (flag == 0) {
                conTaxa.GravarTaxa(mod);
            } else {
                conTaxa.AlterarTaxa(mod);
            }
            jTxt_nome.setEnabled(false);
            jBtt_novo.setEnabled(true);
            jBtt_salvar.setEnabled(false);
            jBtt_editar.setEnabled(false);
            jBtt_excluir.setEnabled(false);
            jBtt_cancelar.setEnabled(false);
            limpaCampos();
            HabilitaDesabilitaCampos(0);
            preencherTabela("select * from tb_taxas where tipo = 'O' order by id_taxa");
            preencherTabelaA("select * from tb_taxas where tipo = 'A' order by id_taxa");
        }
    }//GEN-LAST:event_jBtt_salvarActionPerformed

    private void jBtt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_novoActionPerformed

        flag = 0;

        control.Conexao(obj_config._url);
        control.executaSQL("select * from tb_taxas order by id_taxa");

        try {
            if (!control.rs.last()) {
                jTxt_codigo.setText("1");
            } else {
                jTxt_codigo.setText(String.valueOf(control.rs.getInt("id_taxa") + 1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar o último código!\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
        java.util.Date datahoje = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        jFTxt_dataCad.setText(df.format(datahoje));
        jBtt_novo.setEnabled(false);
        jBtt_salvar.setEnabled(true);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(true);
        HabilitaDesabilitaCampos(1);
        jTxt_nome.setEnabled(false);
        jFTxt_ano_modelo.setEnabled(true);
    }//GEN-LAST:event_jBtt_novoActionPerformed

    private void jTbl_taxaObrigatoriasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbl_taxaObrigatoriasKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            String codigo_taxa = "" + jTbl_taxaObrigatorias.getValueAt(jTbl_taxaObrigatorias.getSelectedRow(), 0);
            control.Conexao(obj_config._url);
            control.executaSQL("select * from tb_taxas where id_taxa = '" + codigo_taxa + "'");
            atualizaTabela();
        }
    }//GEN-LAST:event_jTbl_taxaObrigatoriasKeyReleased

    private void jTbl_taxaObrigatoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_taxaObrigatoriasMouseClicked
        String codigo_taxa = "" + jTbl_taxaObrigatorias.getValueAt(jTbl_taxaObrigatorias.getSelectedRow(), 0);
        control.Conexao(obj_config._url);
        control.executaSQL("select * from tb_taxas where id_taxa = '" + codigo_taxa + "'");
        atualizaTabela();
    }//GEN-LAST:event_jTbl_taxaObrigatoriasMouseClicked

    private void jTbl_taxaObrigatorias1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbl_taxaObrigatorias1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            int parcela = (int) jTbl_taxaObrigatorias1.getValueAt(jTbl_taxaObrigatorias1.getSelectedRow(), 0);
            String entrada = "" + jTbl_taxaObrigatorias1.getValueAt(jTbl_taxaObrigatorias1.getSelectedRow(), 1);
            String modelo = "" + jTbl_taxaObrigatorias1.getValueAt(jTbl_taxaObrigatorias1.getSelectedRow(), 2);
            String coef = "" + jTbl_taxaObrigatorias1.getValueAt(jTbl_taxaObrigatorias1.getSelectedRow(), 3);
            entrada = entrada.replaceAll("%", "");

            control.Conexao(obj_config._url);
            control.executaSQL("select * from tb_taxas where parcela = '" + parcela + "' and entrada = '" + entrada + "' and ano_modelo = '" + modelo + "' and coeficiente = '" + coef + "'");
            atualizaTabela();
        }
    }//GEN-LAST:event_jTbl_taxaObrigatorias1KeyReleased

    private void jTbl_taxaObrigatorias1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_taxaObrigatorias1MouseClicked
        int parcela = (int) jTbl_taxaObrigatorias1.getValueAt(jTbl_taxaObrigatorias1.getSelectedRow(), 0);
        String entrada = "" + jTbl_taxaObrigatorias1.getValueAt(jTbl_taxaObrigatorias1.getSelectedRow(), 1);
        String modelo = "" + jTbl_taxaObrigatorias1.getValueAt(jTbl_taxaObrigatorias1.getSelectedRow(), 2);
        String coef = "" + jTbl_taxaObrigatorias1.getValueAt(jTbl_taxaObrigatorias1.getSelectedRow(), 3);
        entrada = entrada.replaceAll("%", "");

        control.Conexao(obj_config._url);
        control.executaSQL("select * from tb_taxas where parcela = '" + parcela + "' and entrada = '" + entrada + "' and ano_modelo = '" + modelo + "' and coeficiente = '" + coef + "'");
        atualizaTabela();
    }//GEN-LAST:event_jTbl_taxaObrigatorias1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtt_cancelar;
    private javax.swing.JButton jBtt_editar;
    private javax.swing.JButton jBtt_excluir;
    private javax.swing.JButton jBtt_novo;
    private javax.swing.JButton jBtt_salvar;
    private javax.swing.JComboBox jCbx_entrada;
    private javax.swing.JComboBox jCbx_parcela;
    private javax.swing.JComboBox jCbx_tipo;
    private javax.swing.JFormattedTextField jFTxt_ano_modelo;
    private javax.swing.JFormattedTextField jFTxt_dataCad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTbl_taxaObrigatorias;
    private javax.swing.JTable jTbl_taxaObrigatorias1;
    private javax.swing.JTextField jTxt_codigo;
    private javax.swing.JTextField jTxt_coeficiente;
    private javax.swing.JTextField jTxt_nome;
    // End of variables declaration//GEN-END:variables
 public void limpaCampos() {
        jTxt_codigo.setText("");
        jFTxt_dataCad.setText("");
        jTxt_nome.setText("");
        jCbx_tipo.setSelectedIndex(0);
        jCbx_parcela.setSelectedIndex(0);
        jCbx_entrada.setSelectedIndex(0);
        jTxt_coeficiente.setText("");
        jFTxt_ano_modelo.setText("");
    }

    public void HabilitaDesabilitaCampos(int acao) {

        if (acao == 1) {
            jTxt_nome.setEnabled(true);
            jCbx_tipo.setEnabled(true);
            jTxt_nome.setEnabled(true);
            jCbx_parcela.setEnabled(true);
            jCbx_entrada.setEnabled(true);
            jTxt_coeficiente.setEnabled(true);
            jFTxt_ano_modelo.setEnabled(true);
        } else {
            jTxt_nome.setEnabled(!true);
            jCbx_tipo.setEnabled(!true);
            jTxt_nome.setEnabled(!true);
            jCbx_parcela.setEnabled(false);
            jCbx_entrada.setEnabled(false);
            jTxt_coeficiente.setEnabled(false);
            jFTxt_ano_modelo.setEnabled(false);
        }
    }

    public boolean preencherObjeto() {
        mod.setId_taxa(Integer.parseInt(jTxt_codigo.getText()));
        if ("  /  /    ".equals(jFTxt_dataCad.getText())) {
            JOptionPane.showMessageDialog(null, "Digite a data corretamente!", "Erro!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        mod.setDatacad((java.sql.Date) validar.formDataStrToData(jFTxt_dataCad.getText()));

        char[] salarioErro = jTxt_coeficiente.getText().toCharArray();
        int ok = 0;
        for (int n = jTxt_coeficiente.getText().length() - 1; n > -1; n--) {
            if (salarioErro[n] == '.') {
                ok++;
            }
            if (ok > 1) {
                salarioErro[n] = 'E';
                ok--;
            }
        }

        if ("".equals(jTxt_coeficiente.getText())) {
            JOptionPane.showMessageDialog(null, "Digite o valor ou o coeficiente", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        String salario = String.valueOf(salarioErro);
        salario = salario.replaceAll("E", "");

        if ("Adicional".equals(jCbx_tipo.getSelectedItem())) {
            mod.setTipo("A");
            mod.setDescricao("");
            int par = Integer.parseInt((String) jCbx_parcela.getSelectedItem());
            mod.setParcela(par);

            String entrada = (String) jCbx_entrada.getSelectedItem();
            entrada = entrada.replaceAll("%", "");
            int ent = Integer.parseInt(entrada);

            mod.setEntrada(ent);
            mod.setValor(0);
            mod.setCoeficiente(Float.valueOf(salario));
            if ("  /  ".equals(jFTxt_ano_modelo.getText())) {
                JOptionPane.showMessageDialog(null, "Digite o ano do modelo", "Erro", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            mod.setAno_modelo(jFTxt_ano_modelo.getText());
        } else {
            String nomes = jTxt_nome.getText();
            nomes = nomes.replaceAll("  ", " ");
            if ((("".equals(nomes)) || (" ".equals(nomes))) && (!"Adicional".equals(jCbx_tipo.getSelectedItem()))) {
                JOptionPane.showMessageDialog(null, "Preencher o nome!!", "Erro", JOptionPane.ERROR_MESSAGE);
                jTxt_nome.setText("");
                return false;
            }
            mod.setDescricao(nomes);
            mod.setTipo("O");
            mod.setParcela(0);
            mod.setEntrada(0);
            mod.setValor(Double.valueOf(salario));
            mod.setCoeficiente(0);
            mod.setAno_modelo("");
        }

        return true;
    }

    public void preencherTabela(String SQL) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Descrição", "Valor"};
        control.executaSQL(SQL);
        try {
            control.rs.first();

            do {
                dados.add(new Object[]{control.rs.getInt("id_taxa"), control.rs.getString("descricao"), control.rs.getString("valor")});

            } while (control.rs.next());

        } catch (SQLException ex) {

        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTbl_taxaObrigatorias.setModel(modelo);
        jTbl_taxaObrigatorias.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTbl_taxaObrigatorias.getColumnModel().getColumn(0).setResizable(false);
        jTbl_taxaObrigatorias.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTbl_taxaObrigatorias.getColumnModel().getColumn(1).setResizable(false);
        jTbl_taxaObrigatorias.getColumnModel().getColumn(2).setPreferredWidth(121);
        jTbl_taxaObrigatorias.getColumnModel().getColumn(2).setResizable(false);
        jTbl_taxaObrigatorias.getTableHeader().setReorderingAllowed(false);
        jTbl_taxaObrigatorias.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTbl_taxaObrigatorias.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void preencherTabelaA(String SQL) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Parcela", "Entrada", "Ano modelo", "Coeficiente"};
        control.executaSQL(SQL);
        try {
            control.rs.first();

            do {
                String entrada = control.rs.getString("entrada");
                entrada += "%";
                dados.add(new Object[]{control.rs.getInt("Parcela"), entrada, control.rs.getString("ano_modelo"), control.rs.getString("coeficiente")});

            } while (control.rs.next());

        } catch (SQLException ex) {

        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTbl_taxaObrigatorias1.setModel(modelo);
        jTbl_taxaObrigatorias1.getColumnModel().getColumn(0).setPreferredWidth(55);
        jTbl_taxaObrigatorias1.getColumnModel().getColumn(0).setResizable(false);
        jTbl_taxaObrigatorias1.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTbl_taxaObrigatorias1.getColumnModel().getColumn(1).setResizable(false);
        jTbl_taxaObrigatorias1.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTbl_taxaObrigatorias1.getColumnModel().getColumn(2).setResizable(false);
        jTbl_taxaObrigatorias1.getColumnModel().getColumn(3).setPreferredWidth(186);
        jTbl_taxaObrigatorias1.getColumnModel().getColumn(3).setResizable(false);
        jTbl_taxaObrigatorias1.getTableHeader().setReorderingAllowed(false);
        jTbl_taxaObrigatorias1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTbl_taxaObrigatorias1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void atualizaTabela() {

        try {
            control.rs.first();
            jTxt_codigo.setText(String.valueOf(control.rs.getInt("id_taxa")));

            try {
                jFTxt_dataCad.setText(validar.formDataDateToStr(control.rs.getDate("datacad")));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro na data");
            }
            jTxt_nome.setText(control.rs.getString("descricao"));

            jCbx_parcela.setSelectedItem(control.rs.getString("parcela"));

            jCbx_entrada.setSelectedItem(control.rs.getString("entrada")+"%");

            jFTxt_ano_modelo.setText(control.rs.getString("ano_modelo"));
            if (control.rs.getString("tipo").equals("A")) {
                jCbx_tipo.setSelectedItem("Adicional");
                jTxt_coeficiente.setText(String.valueOf(control.rs.getFloat("coeficiente")));
                jLabel6.setText("coeficiente");
            } else {
                jCbx_tipo.setSelectedItem("Obrigatorio");
                jTxt_coeficiente.setText(String.valueOf(control.rs.getDouble("valor")));
                jLabel6.setText("Valor Taxa");
            }
            jBtt_novo.setEnabled(false);
            jBtt_salvar.setEnabled(false);
            jBtt_editar.setEnabled(true);
            jBtt_excluir.setEnabled(true);
            jBtt_cancelar.setEnabled(true);
            HabilitaDesabilitaCampos(0);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados do registro!", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }
}
