/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ControleFuncionarios;
import Controle.Maiuscula;
import Controle.ModeloTabela;
import Controle.Validacoes;
import Controle.Numeric;
import Controle.cadastro;
import Modelo.ModeloFuncionarios;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Murylo César Souza
 */
public class JIFuncionarios extends javax.swing.JInternalFrame {

    ConectaBanco conFun = new ConectaBanco();
    ConectaBanco conCid = new ConectaBanco();
    ModeloFuncionarios mod = new ModeloFuncionarios();
    ControleFuncionarios control = new ControleFuncionarios();
    Validacoes validar = new Validacoes();
    cadastro obj_config = new cadastro();
    MaskFormatter formatoData, formatoTelefone, formatoCEP, Fone;

    int flag = 0;

    /**
     * Creates new form JIFClientes
     */
    public JIFuncionarios() {
        initComponents();
        obj_config.carregaconfig();
        PreencherCombo();
        preencherTabela("select id_funcionario , nome , setor from tb_funcionarios order by id_funcionario");
        jTxt_nome.setDocument(new Maiuscula(50));
        jTxt_endereco.setDocument(new Maiuscula(100));
        jTxt_numero.setDocument(new Maiuscula(10));
        jTxt_bairro.setDocument(new Maiuscula(40));
        jTxt_setor.setDocument(new Maiuscula(25));
        jTxt_salario.setDocument(new Numeric(15));
        jTxt_email.setDocument(new Maiuscula(100));
        jFTxt_datapagamento.setDocument(new Numeric(2));
        jTxt_pesquisa.setDocument(new Maiuscula(100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxt_codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        try{
            formatoData= new MaskFormatter("##/##/####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_datacad = new JFormattedTextField(formatoData);
        ;
        jLabel3 = new javax.swing.JLabel();
        jTxt_nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCbx_estcivil = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        try{
            formatoData= new MaskFormatter("##/##/####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_datanasc = new JFormattedTextField(formatoData);
        jLabel7 = new javax.swing.JLabel();
        jRBt_mas = new javax.swing.JRadioButton();
        jRBt_fem = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jTxt_endereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxt_numero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxt_bairro = new javax.swing.JTextField();
        try{
            formatoCEP= new MaskFormatter("##.###-###");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_cep = new JFormattedTextField(formatoCEP);
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCbx_cidade = new javax.swing.JComboBox();
        jTxt_pesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_funcionario = new javax.swing.JTable();
        jBtt_novo = new javax.swing.JButton();
        jBtt_salvar = new javax.swing.JButton();
        jBtt_editar = new javax.swing.JButton();
        jBtt_excluir = new javax.swing.JButton();
        jBtt_cancelar = new javax.swing.JButton();
        jBtt_pesquisar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTxt_email = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTxt_salario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxt_setor = new javax.swing.JTextField();
        jRBt_Cidades = new javax.swing.JButton();
        try{
            Fone= new MaskFormatter("(##) 9####-####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jTxt_fone = new JFormattedTextField(Fone);
        ;
        try{
            Fone= new MaskFormatter("(##) 9####-####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jTxt_fone2 = new JFormattedTextField(Fone);
        ;
        jLabel18 = new javax.swing.JLabel();
        jRBt_contratado = new javax.swing.JRadioButton();
        jRBt_demitido = new javax.swing.JRadioButton();
        jFTxt_datapagamento = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastro de Funcionarios");

        jLabel1.setText("Código");

        jTxt_codigo.setEnabled(false);

        jLabel2.setText("Data Cadastro");

        jFTxt_datacad.setEnabled(false);

        jLabel3.setText("Nome");

        jTxt_nome.setEnabled(false);

        jLabel4.setText("Salário");

        jLabel5.setText("Estado civil");

        jCbx_estcivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Estdo Civil-", "Solteiro(a)", "Casado(a)", "Desquitado(a)", "Divorciado(a)", "Separado(a)", "Viuvo(a)", "Amasiado(a)" }));
        jCbx_estcivil.setEnabled(false);

        jLabel6.setText("Data Nasc.");

        jFTxt_datanasc.setEnabled(false);

        jLabel7.setText("Sexo:");

        buttonGroup1.add(jRBt_mas);
        jRBt_mas.setText("Masculino");
        jRBt_mas.setEnabled(false);

        buttonGroup1.add(jRBt_fem);
        jRBt_fem.setText("Feminino");
        jRBt_fem.setEnabled(false);

        jLabel8.setText("Endereço");

        jTxt_endereco.setEnabled(false);

        jLabel9.setText("Número");

        jTxt_numero.setEnabled(false);

        jLabel10.setText("Bairro");

        jTxt_bairro.setEnabled(false);

        jFTxt_cep.setEnabled(false);

        jLabel11.setText("CEP");

        jLabel12.setText("Cidade");

        jCbx_cidade.setEnabled(false);

        jTbl_funcionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTbl_funcionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_funcionarioMouseClicked(evt);
            }
        });
        jTbl_funcionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbl_funcionarioKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTbl_funcionario);

        jBtt_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/new.png"))); // NOI18N
        jBtt_novo.setText("Novo");
        jBtt_novo.setToolTipText("Novo");
        jBtt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_novoActionPerformed(evt);
            }
        });

        jBtt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/new.png"))); // NOI18N
        jBtt_salvar.setText("Salvar");
        jBtt_salvar.setToolTipText("Salvar");
        jBtt_salvar.setEnabled(false);
        jBtt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_salvarActionPerformed(evt);
            }
        });

        jBtt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jBtt_editar.setText("Editar");
        jBtt_editar.setToolTipText("Editar");
        jBtt_editar.setEnabled(false);
        jBtt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_editarActionPerformed(evt);
            }
        });

        jBtt_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/del.png"))); // NOI18N
        jBtt_excluir.setText("Excluir");
        jBtt_excluir.setToolTipText("Excluir");
        jBtt_excluir.setEnabled(false);
        jBtt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_excluirActionPerformed(evt);
            }
        });

        jBtt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancela.png"))); // NOI18N
        jBtt_cancelar.setText("Cancelar");
        jBtt_cancelar.setToolTipText("Cancelar");
        jBtt_cancelar.setEnabled(false);
        jBtt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_cancelarActionPerformed(evt);
            }
        });

        jBtt_pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        jBtt_pesquisar.setText("Pesquisa");
        jBtt_pesquisar.setToolTipText("Pesquisar");
        jBtt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_pesquisarActionPerformed(evt);
            }
        });

        jLabel14.setText("Telefone");

        jLabel15.setText("Telefone");

        jLabel16.setText("E_mail");

        jTxt_email.setEnabled(false);
        jTxt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_emailKeyTyped(evt);
            }
        });

        jLabel17.setText("Dia Pagamento");

        jTxt_salario.setEnabled(false);

        jLabel13.setText("Setor");

        jTxt_setor.setEnabled(false);

        jRBt_Cidades.setText("+");
        jRBt_Cidades.setEnabled(false);
        jRBt_Cidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBt_CidadesActionPerformed(evt);
            }
        });

        jTxt_fone.setEnabled(false);

        jTxt_fone2.setEnabled(false);

        jLabel18.setText("Status");

        buttonGroup3.add(jRBt_contratado);
        jRBt_contratado.setSelected(true);
        jRBt_contratado.setText("Contratado");
        jRBt_contratado.setEnabled(false);

        buttonGroup3.add(jRBt_demitido);
        jRBt_demitido.setText("Demitido");
        jRBt_demitido.setEnabled(false);

        jFTxt_datapagamento.setEnabled(false);
        jFTxt_datapagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFTxt_datapagamentoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFTxt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCbx_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jRBt_Cidades)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jTxt_fone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jTxt_fone2))
                            .addComponent(jTxt_email)))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxt_nome)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTxt_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jRBt_contratado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jRBt_demitido, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBtt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(136, 136, 136))
                            .addComponent(jTxt_pesquisa)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRBt_mas)
                                .addGap(6, 6, 6)
                                .addComponent(jRBt_fem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTxt_datanasc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(34, 34, 34)
                                .addComponent(jCbx_estcivil, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTxt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(7, 7, 7)
                                .addComponent(jTxt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtt_novo)
                                .addGap(28, 28, 28)
                                .addComponent(jBtt_salvar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtt_editar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtt_excluir)
                                .addGap(18, 18, 18)
                                .addComponent(jBtt_cancelar))
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(25, 25, 25)
                                .addComponent(jTxt_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jTxt_setor)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addGap(36, 36, 36)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jFTxt_datapagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtt_cancelar, jBtt_editar, jBtt_excluir, jBtt_novo, jBtt_salvar});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel14, jLabel15});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jFTxt_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jRBt_contratado)
                    .addComponent(jRBt_demitido))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jRBt_mas)
                    .addComponent(jRBt_fem)
                    .addComponent(jLabel6)
                    .addComponent(jFTxt_datanasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jCbx_estcivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTxt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTxt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTxt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jCbx_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jRBt_Cidades)
                    .addComponent(jTxt_fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_fone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTxt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxt_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTxt_setor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jFTxt_datapagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtt_pesquisar))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtt_novo)
                    .addComponent(jBtt_salvar)
                    .addComponent(jBtt_editar)
                    .addComponent(jBtt_excluir)
                    .addComponent(jBtt_cancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtt_cancelar, jBtt_editar, jBtt_excluir, jBtt_novo, jBtt_salvar});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCbx_cidade, jCbx_estcivil, jFTxt_cep, jFTxt_datacad, jFTxt_datanasc, jLabel1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, jRBt_fem, jRBt_mas, jTxt_bairro, jTxt_codigo, jTxt_email, jTxt_endereco, jTxt_nome, jTxt_numero, jTxt_pesquisa, jTxt_salario, jTxt_setor});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_novoActionPerformed
        flag = 0;
        conFun.Conexao(obj_config._url);
        conFun.executaSQL("select id_funcionario from tb_funcionarios order by id_funcionario");

        try {
            if (!conFun.rs.last()) {
                jTxt_codigo.setText("1");
            } else {
                jTxt_codigo.setText(String.valueOf(conFun.rs.getInt("id_funcionario") + 1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar o último código!\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
        java.util.Date datahoje = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        jFTxt_datacad.setText(df.format(datahoje));
        jTxt_pesquisa.setEnabled(false);
        jBtt_pesquisar.setEnabled(false);
        jBtt_novo.setEnabled(false);
        jBtt_salvar.setEnabled(true);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(true);

        HabilitaDesabilitaCampos(1);
        jRBt_contratado.setSelected(true);
        jRBt_contratado.setEnabled(false);
        jRBt_demitido.setEnabled(false);
    }//GEN-LAST:event_jBtt_novoActionPerformed

    private void jBtt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_editarActionPerformed
        HabilitaDesabilitaCampos(1);
        flag = 1;
        jTxt_nome.setEnabled(true);
        jBtt_novo.setEnabled(false);
        jBtt_salvar.setEnabled(true);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(true);

    }//GEN-LAST:event_jBtt_editarActionPerformed

    private void jBtt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_excluirActionPerformed
        jTxt_nome.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);
        HabilitaDesabilitaCampos(0);
        mod.setId_funcionario(Integer.parseInt(jTxt_codigo.getText()));
        control.ExcluirFuncionarios(mod);
        preencherTabela("select * from tb_funcionarios order by id_funcionario");
        limpaCampos();

    }//GEN-LAST:event_jBtt_excluirActionPerformed

    private void jBtt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_cancelarActionPerformed
        limpaCampos();
        HabilitaDesabilitaCampos(0);
        jTxt_nome.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);
    }//GEN-LAST:event_jBtt_cancelarActionPerformed

    private void jBtt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_pesquisarActionPerformed
        preencherTabela("select * from tb_funcionarios where nome like '%" + jTxt_pesquisa.getText() + "%' order by id_funcionario");
        jTxt_pesquisa.setText("");
    }//GEN-LAST:event_jBtt_pesquisarActionPerformed

    private void jTbl_funcionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_funcionarioMouseClicked
        atualizaTabela();
    }//GEN-LAST:event_jTbl_funcionarioMouseClicked

    private void jTbl_funcionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbl_funcionarioKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            atualizaTabela();
        }
    }//GEN-LAST:event_jTbl_funcionarioKeyReleased

    private void jBtt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_salvarActionPerformed
        if (preencherObjeto()) {
            if (flag == 0) {
                control.GravarFuncionarios(mod);
            } else {
                control.AlterarFuncionarios(mod);
            }
            jTxt_nome.setEnabled(false);
            jBtt_novo.setEnabled(true);
            jBtt_salvar.setEnabled(false);
            jBtt_editar.setEnabled(false);
            jBtt_excluir.setEnabled(false);
            jBtt_cancelar.setEnabled(false);
            limpaCampos();
            HabilitaDesabilitaCampos(0);
            preencherTabela("select * from tb_funcionarios order by id_funcionario");
        }
    }//GEN-LAST:event_jBtt_salvarActionPerformed

    private void jRBt_CidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBt_CidadesActionPerformed
        JIFCidades janela = new JIFCidades(2);
        Tela.jDesktop.add(janela);
        Tela.centralizaForm(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jRBt_CidadesActionPerformed

    private void jTxt_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_emailKeyTyped
        if (evt.getKeyChar() == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_jTxt_emailKeyTyped

    private void jFTxt_datapagamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTxt_datapagamentoKeyTyped
        if (evt.getKeyChar() == '.') {
            evt.consume();
        }
    }//GEN-LAST:event_jFTxt_datapagamentoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jBtt_cancelar;
    private javax.swing.JButton jBtt_editar;
    private javax.swing.JButton jBtt_excluir;
    private javax.swing.JButton jBtt_novo;
    private javax.swing.JButton jBtt_pesquisar;
    private javax.swing.JButton jBtt_salvar;
    public static javax.swing.JComboBox jCbx_cidade;
    private javax.swing.JComboBox jCbx_estcivil;
    private javax.swing.JFormattedTextField jFTxt_cep;
    private javax.swing.JFormattedTextField jFTxt_datacad;
    private javax.swing.JFormattedTextField jFTxt_datanasc;
    private javax.swing.JTextField jFTxt_datapagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jRBt_Cidades;
    private javax.swing.JRadioButton jRBt_contratado;
    private javax.swing.JRadioButton jRBt_demitido;
    private javax.swing.JRadioButton jRBt_fem;
    private javax.swing.JRadioButton jRBt_mas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbl_funcionario;
    private javax.swing.JTextField jTxt_bairro;
    private javax.swing.JTextField jTxt_codigo;
    private javax.swing.JTextField jTxt_email;
    private javax.swing.JTextField jTxt_endereco;
    private javax.swing.JFormattedTextField jTxt_fone;
    private javax.swing.JFormattedTextField jTxt_fone2;
    private javax.swing.JTextField jTxt_nome;
    private javax.swing.JTextField jTxt_numero;
    private javax.swing.JTextField jTxt_pesquisa;
    private javax.swing.JTextField jTxt_salario;
    private javax.swing.JTextField jTxt_setor;
    // End of variables declaration//GEN-END:variables

    public void limpaCampos() {
        jTxt_codigo.setText("");
        jFTxt_datacad.setText("");
        jTxt_nome.setText("");
        jRBt_mas.setSelected(!false);
        jRBt_fem.setSelected(!false);
        jFTxt_datanasc.setText("");
        jTxt_endereco.setText("");
        jTxt_bairro.setText("");
        jTxt_numero.setText("");
        jFTxt_cep.setText("");
        jTxt_fone.setText("");
        jTxt_fone2.setText("");
        jTxt_email.setText("");
        jTxt_pesquisa.setText("");
        jTxt_salario.setText("");
        jTxt_setor.setText("");
        jFTxt_datapagamento.setText("");
    }

    public void PreencherCombo() {

        conCid.Conexao(obj_config._url);
        conCid.executaSQL("select nome from tb_cidades order by nome");
        try {
            conCid.rs.first();
            jCbx_cidade.removeAllItems();
            do {
                jCbx_cidade.addItem(conCid.rs.getString("nome"));
            } while (conCid.rs.next());
        } catch (SQLException ex) {
        }
        conCid.Desconecta();
    }

    public void HabilitaDesabilitaCampos(int acao) {

        if (acao == 1) {
            jTxt_nome.setEnabled(true);
            jRBt_fem.setEnabled(true);
            jRBt_mas.setEnabled(true);
            jFTxt_datanasc.setEnabled(true);
            jCbx_estcivil.setEnabled(true);
            jTxt_endereco.setEnabled(true);
            jTxt_numero.setEnabled(true);
            jTxt_bairro.setEnabled(true);
            jFTxt_cep.setEnabled(true);
            jCbx_cidade.setEnabled(true);
            jTxt_fone.setEnabled(true);
            jTxt_fone2.setEnabled(true);
            jTxt_email.setEnabled(true);
            jTxt_salario.setEnabled(true);
            jTxt_setor.setEnabled(true);
            jFTxt_datapagamento.setEnabled(true);
            jTxt_pesquisa.setEnabled(false);
            jBtt_pesquisar.setEnabled(false);
            jRBt_Cidades.setEnabled(true);
            jRBt_contratado.setEnabled(true);
            jRBt_demitido.setEnabled(true);
        } else {
            jTxt_nome.setEnabled(!true);
            jRBt_fem.setEnabled(!true);
            jRBt_mas.setEnabled(!true);
            jFTxt_datanasc.setEnabled(!true);
            jCbx_estcivil.setEnabled(!true);
            jTxt_endereco.setEnabled(!true);
            jTxt_numero.setEnabled(!true);
            jTxt_bairro.setEnabled(!true);
            jFTxt_cep.setEnabled(!true);
            jCbx_cidade.setEnabled(!true);
            jTxt_fone.setEnabled(!true);
            jTxt_fone2.setEnabled(!true);
            jTxt_email.setEnabled(!true);
            jTxt_salario.setEnabled(!true);
            jTxt_setor.setEnabled(!true);
            jFTxt_datapagamento.setEnabled(!true);
            jTxt_pesquisa.setEnabled(!false);
            jBtt_pesquisar.setEnabled(!false);
            jRBt_Cidades.setEnabled(!true);
            jRBt_contratado.setEnabled(false);
            jRBt_demitido.setEnabled(false);
        }
    }

    public boolean preencherObjeto() {
        mod.setId_funcionario(Integer.parseInt(jTxt_codigo.getText()));
        if ("  /  /    ".equals(jFTxt_datacad.getText())) {
            JOptionPane.showMessageDialog(null, "Digite a data corretamente!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        mod.setDatacad((Date) validar.formDataStrToData(jFTxt_datacad.getText()));

        if (jRBt_contratado.isSelected()) {
            mod.setStatus("C");
        } else {
            mod.setStatus("D");
        }

        char[] validaData = jTxt_nome.getText().toCharArray();
        int ok = 0;
        for (int n = 0; n < jTxt_nome.getText().length(); n++) {
            if (validaData[n] == ' ') {
                ok++;
            }
        }
        if (ok == jTxt_nome.getText().length()) {

            JOptionPane.showMessageDialog(null, "Preencha o nome!", "Erro", JOptionPane.ERROR_MESSAGE);
            jTxt_nome.setText("");
            return false;
        }
        mod.setNome(jTxt_nome.getText());

        if (jRBt_mas.isSelected()) {
            mod.setSexo("M");
        } else if (jRBt_fem.isSelected()) {
            mod.setSexo("F");
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o sexo!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if ("  /  /    ".equals(jFTxt_datanasc.getText())) {
            JOptionPane.showMessageDialog(null, "Digite a data corretamente!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        mod.setDatanasc((Date) validar.formDataStrToData(jFTxt_datanasc.getText()));

        if ("-Estdo Civil-".equals(jCbx_estcivil.getSelectedItem())) {
            JOptionPane.showMessageDialog(null, "Selecione o estado civil!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        mod.setEstado_civil((String) jCbx_estcivil.getSelectedItem());
        mod.setEndereco(jTxt_endereco.getText());
        mod.setBairro(jTxt_bairro.getText());
        mod.setNumero(jTxt_numero.getText());
        mod.setCep(jFTxt_cep.getText());
        mod.setId_cidade((String) jCbx_cidade.getSelectedItem());
        
        if (("(  ) 9    -    ".equals(jTxt_fone.getText())) && ("(  ) 9    -    ".equals(jTxt_fone2.getText()))) {
            JOptionPane.showMessageDialog(null, "Digite um contato pelo menos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if ((!validar.ValidarDDDbr(jTxt_fone.getText())) && (!"(  ) 9    -    ".equals(jTxt_fone.getText()))) {
            JOptionPane.showMessageDialog(null, "O DDD está errado fone 1", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        mod.setTelefone1(jTxt_fone.getText());
        
        if ((!validar.ValidarDDDbr(jTxt_fone2.getText())) && (!"(  ) 9    -    ".equals(jTxt_fone2.getText()))) {
            JOptionPane.showMessageDialog(null, "O DDD está errado fone 2", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        mod.setTelefone2(jTxt_fone2.getText());;

        if (!validar.Validar_Email(jTxt_email.getText())) {
            JOptionPane.showMessageDialog(null, "O E_mail está errado!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        mod.setEmail(jTxt_email.getText());

        if (("".equals(jTxt_salario.getText()))) {
            JOptionPane.showMessageDialog(null, "O erro no Salário", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        mod.setSalario(Double.valueOf(jTxt_salario.getText().replaceAll("\\.", "").replaceAll("\\,", ".")));

        mod.setSetor(jTxt_setor.getText()); if ("".equals(jFTxt_datapagamento.getText())) {
            JOptionPane.showMessageDialog(null, "Digite a data_do_pagamento corretamente!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        mod.setData_pagamento(Integer.parseInt(jFTxt_datapagamento.getText()));

        return true;
    }

    public void preencherTabela(String SQL) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Nome do Funcionarios", "Setor"};
        conFun.Conexao(obj_config._url);
        conFun.executaSQL(SQL);
        try {
            conFun.rs.first();

            do {
                dados.add(new Object[]{conFun.rs.getInt("id_funcionario"), conFun.rs.getString("nome"), conFun.rs.getString("setor")});

            } while (conFun.rs.next());

        } catch (SQLException ex) {

        }
        conFun.Desconecta();
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTbl_funcionario.setModel(modelo);
        jTbl_funcionario.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTbl_funcionario.getColumnModel().getColumn(0).setResizable(false);
        jTbl_funcionario.getColumnModel().getColumn(1).setPreferredWidth(375);
        jTbl_funcionario.getColumnModel().getColumn(1).setResizable(false);
        jTbl_funcionario.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTbl_funcionario.getColumnModel().getColumn(2).setResizable(false);
        jTbl_funcionario.getTableHeader().setReorderingAllowed(false);
        jTbl_funcionario.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTbl_funcionario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void atualizaTabela() {
        conFun.Conexao(obj_config._url);
        conFun.executaSQL("select * from tb_funcionarios where id_funcionario = " + jTbl_funcionario.getValueAt(jTbl_funcionario.getSelectedRow(), 0));

        try {
            conFun.rs.first();
            jTxt_codigo.setText(String.valueOf(conFun.rs.getInt("id_funcionario")));

            if (conFun.rs.getString("status").equals("C")) {
                jRBt_contratado.setSelected(true);
                jRBt_demitido.setSelected(false);
            } else {
                jRBt_contratado.setSelected(!true);
                jRBt_demitido.setSelected(true);
            }

            jTxt_nome.setText(conFun.rs.getString("nome"));
            jFTxt_datapagamento.setText(conFun.rs.getString("Data_pagamento"));
            jTxt_endereco.setText(conFun.rs.getString("endereco"));
            jTxt_bairro.setText(conFun.rs.getString("bairro"));
            jTxt_numero.setText(conFun.rs.getString("numero"));
            jFTxt_cep.setText(conFun.rs.getString("cep"));
            jCbx_estcivil.setSelectedItem(conFun.rs.getString("estado_civil"));

            try {
                jFTxt_datacad.setText(validar.formDataDateToStr(conFun.rs.getDate("datacad")));
                jFTxt_datanasc.setText(validar.formDataDateToStr(conFun.rs.getDate("datanasc")));
            } catch (Exception e) {
                //JOptionPane.showMessageDialog(null, "Erro na data");
            }

            jFTxt_datapagamento.setText(String.valueOf(conFun.rs.getInt("data_pagamento")));

            if (conFun.rs.getString("sexo").equals("M")) {
                jRBt_mas.setSelected(true);
                jRBt_fem.setSelected(false);
            } else {
                jRBt_mas.setSelected(false);
                jRBt_fem.setSelected(true);
            }
            jTxt_fone.setText(conFun.rs.getString("fone1"));
            jTxt_fone.setText(conFun.rs.getString("fone2"));
            jTxt_email.setText(conFun.rs.getString("email"));
            jTxt_salario.setText(String.valueOf(conFun.rs.getDouble("salario")));
            jTxt_setor.setText(conFun.rs.getString("setor"));
            conCid.Conexao(obj_config._url);
            conCid.executaSQL("select nome from tb_cidades where id_cidade = " + conFun.rs.getInt("id_cidade"));
            conCid.rs.first();
            jCbx_cidade.setSelectedItem(conCid.rs.getString("nome"));
            jBtt_novo.setEnabled(false);
            jBtt_salvar.setEnabled(false);
            jBtt_editar.setEnabled(true);
            jBtt_excluir.setEnabled(true);
            jBtt_cancelar.setEnabled(true);
            HabilitaDesabilitaCampos(0);
            conCid.Desconecta();
            conFun.Desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados do registro!\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }
}
