/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ControleVenda;
import Controle.Imprimir;
import Controle.ModeloTabela;
import Controle.Validacoes;
import Controle.Numeric;
import Controle.cadastro;
import Modelo.ModeloVendas;
import com.itextpdf.text.DocumentException;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Murylo César Souza
 */
public class JIFVenda extends javax.swing.JInternalFrame {

    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco conFun = new ConectaBanco();
    ConectaBanco conCli = new ConectaBanco();
    ConectaBanco conVei = new ConectaBanco();
    ControleVenda control = new ControleVenda();
    ModeloVendas model = new ModeloVendas();
    Validacoes validar = new Validacoes();
    cadastro obj_config = new cadastro();
    DecimalFormat formatoDecimal = new DecimalFormat("##,###,###,##0.00");

    MaskFormatter formatoData, formatoCNPJCPF;

    int flag = 0;
    boolean carregamento = false;

    /**
     * Creates new form JIFVenda
     */
    public JIFVenda() {
        initComponents();
        obj_config.carregaconfig();

        jTxt_valor_venda.setDocument(new Numeric(12));
        jTxt_garantia.setDocument(new Numeric(3));

        PreencherComboFun("select nome from tb_funcionarios where status = 'C' order by nome");
        PreencherComboCliente();
        preencherTabela("select * from tb_veiculos V ,tb_modelos M where M.id_modelo = V.modelo and V.status = 'T' order by id_veiculo");
        preencherTabelaVenda("select * from tb_vendas VD ,tb_clientes_fornecedores C , tb_veiculos V ,tb_modelos M where"//Selecione as tabela
                + " VD.id_cliente = C.id_cliente_fornecedor"
                + " and V.id_veiculo = VD.id_veiculo "
                + " and M.id_modelo = V.modelo"
                + " order by VD.id_venda");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTbl_Veiculos_venda = new javax.swing.JTable();
        jBtt_novo = new javax.swing.JButton();
        jBtt_salvar = new javax.swing.JButton();
        jBtt_anula = new javax.swing.JButton();
        jBtt_excluir = new javax.swing.JButton();
        jBtt_cancelar = new javax.swing.JButton();
        try{
            formatoData= new MaskFormatter("##/##/####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_datacad = new JFormattedTextField(formatoData);
        ;
        jLabel115 = new javax.swing.JLabel();
        jTxt_codigo = new javax.swing.JTextField();
        jLabel113 = new javax.swing.JLabel();
        jCbx_Funcionarios = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxt_financiado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCbx_formaPagamento = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jFTxt_cpf = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTbl_Venda = new javax.swing.JTable();
        jTxt_garantia = new javax.swing.JTextField();
        jCbx_garantia = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jCbx_banco = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jCbx_Clientes = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        try{
            formatoDecimal= new DecimalFormat("##,###,###,##0.00");

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");
        }
        jTxt_valor_venda = jTxt_valor_venda =  new JFormattedTextField(formatoDecimal);
        jBtt_imprimir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Venda");

        jTbl_Veiculos_venda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTbl_Veiculos_venda.setEnabled(false);
        jScrollPane3.setViewportView(jTbl_Veiculos_venda);

        jBtt_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/new.png"))); // NOI18N
        jBtt_novo.setText("Novo");
        jBtt_novo.setToolTipText("Novo");
        jBtt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_novoActionPerformed(evt);
            }
        });

        jBtt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save.png"))); // NOI18N
        jBtt_salvar.setText("salvar");
        jBtt_salvar.setToolTipText("Salvar");
        jBtt_salvar.setEnabled(false);
        jBtt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_salvarActionPerformed(evt);
            }
        });

        jBtt_anula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/nula.png"))); // NOI18N
        jBtt_anula.setText("Anula");
        jBtt_anula.setToolTipText("Editar");
        jBtt_anula.setEnabled(false);
        jBtt_anula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_anulaActionPerformed(evt);
            }
        });

        jBtt_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/del.png"))); // NOI18N
        jBtt_excluir.setText("Excluir");
        jBtt_excluir.setToolTipText("Excluir");
        jBtt_excluir.setEnabled(false);
        jBtt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_excluirActionPerformed(evt);
            }
        });

        jBtt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancela.png"))); // NOI18N
        jBtt_cancelar.setText("Cancelar");
        jBtt_cancelar.setToolTipText("Cancelar");
        jBtt_cancelar.setEnabled(false);
        jBtt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_cancelarActionPerformed(evt);
            }
        });

        jFTxt_datacad.setEnabled(false);

        jLabel115.setText("Data entrada");

        jTxt_codigo.setEnabled(false);

        jLabel113.setText("Codigo");

        jCbx_Funcionarios.setEnabled(false);

        jLabel1.setText("funcionario");

        jLabel2.setText("Valor financiado");

        jTxt_financiado.setText("0");
        jTxt_financiado.setEnabled(false);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Veiculo da venda");

        jLabel5.setText("Valor venda");

        jCbx_formaPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Á vista", "Cheque", "Financiado" }));
        jCbx_formaPagamento.setEnabled(false);
        jCbx_formaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbx_formaPagamentoActionPerformed(evt);
            }
        });

        jLabel6.setText("Cliente");

        jFTxt_cpf.setEnabled(false);

        jLabel7.setText("CPF");

        jLabel8.setText("Pagamento");

        jLabel9.setText("Tempo garantia");

        jTbl_Venda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTbl_Venda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_VendaMouseClicked(evt);
            }
        });
        jTbl_Venda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbl_VendaKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTbl_Venda);

        jTxt_garantia.setEnabled(false);

        jCbx_garantia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DIA", "MÊS", "ANO" }));
        jCbx_garantia.setEnabled(false);

        jLabel4.setText("Banco");

        jCbx_banco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BancosCaixa", "BNDES", "Bradesco", "Banco do Brasi", "Itaú", "Santander", "HSBC" }));
        jCbx_banco.setEnabled(false);

        jButton1.setText("Pesquisa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCbx_Clientes.setEnabled(false);
        jCbx_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbx_ClientesActionPerformed(evt);
            }
        });

        jButton2.setText("Pesquisa Veiculos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTxt_valor_venda.setEnabled(false);
        jTxt_valor_venda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_valor_vendaKeyTyped(evt);
            }
        });

        jBtt_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Printer Add.jpg"))); // NOI18N
        jBtt_imprimir.setText("Imprimir");
        jBtt_imprimir.setEnabled(false);
        jBtt_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel113))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel115)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFTxt_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addComponent(jCbx_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbx_Funcionarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jFTxt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCbx_formaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5)
                                    .addGap(2, 2, 2)
                                    .addComponent(jTxt_valor_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(295, 295, 295)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxt_financiado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCbx_banco, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxt_garantia))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCbx_garantia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtt_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtt_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtt_anula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtt_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtt_cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtt_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel113, jLabel4, jLabel6, jLabel8});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTxt_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel115)
                    .addComponent(jTxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbx_Funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel113))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jFTxt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCbx_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jCbx_formaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTxt_garantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbx_garantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_valor_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCbx_banco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTxt_financiado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtt_anula)
                    .addComponent(jBtt_novo)
                    .addComponent(jBtt_salvar)
                    .addComponent(jBtt_excluir)
                    .addComponent(jBtt_cancelar)
                    .addComponent(jButton1)
                    .addComponent(jBtt_imprimir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel113, jLabel4, jLabel6, jLabel8});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_novoActionPerformed
        limpaCampos();
        flag = 0;
        conecta.Conexao(obj_config._url);
        conecta.executaSQL("select * from tb_vendas order by id_venda");

        try {
            if (!conecta.rs.last()) {

                jTxt_codigo.setText("1");
            } else {
                jTxt_codigo.setText(String.valueOf(conecta.rs.getInt("id_venda") + 1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir registro!\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }

        conecta.Desconecta();
        java.util.Date datahoje = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        jFTxt_datacad.setText(df.format(datahoje));
        jBtt_novo.setEnabled(false);
        jBtt_salvar.setEnabled(true);
        jBtt_anula.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(true);

        HabilitaDesabilitaCampos(1);
        preencherTabela("select * from tb_veiculos V ,tb_modelos M where M.id_modelo = V.modelo and V.status = 'T' order by id_veiculo");
    }//GEN-LAST:event_jBtt_novoActionPerformed

    private void jBtt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_salvarActionPerformed
        if (preencherObjeto()) {

            jBtt_novo.setEnabled(true);
            jBtt_salvar.setEnabled(false);
            jBtt_anula.setEnabled(false);
            jBtt_excluir.setEnabled(false);
            jBtt_cancelar.setEnabled(false);

            control.GravarVenda(model);
            limpaCampos();
            HabilitaDesabilitaCampos(0);
            preencherTabela("select * from tb_veiculos V ,tb_modelos M where M.id_modelo = V.modelo and V.status = 'T' order by id_veiculo");
            preencherTabelaVenda("select * from tb_vendas VD ,tb_clientes_fornecedores C , tb_veiculos V ,tb_modelos M where"//Selecione as tabela
                    + " VD.id_cliente = C.id_cliente_fornecedor"
                    + " and V.id_veiculo = VD.id_veiculo "
                    + " and M.id_modelo = V.modelo"
                    + " order by id_venda");

        }
    }//GEN-LAST:event_jBtt_salvarActionPerformed

    private void jBtt_anulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_anulaActionPerformed

        conecta.Conexao(obj_config._url);
        conecta.executaSQL("select id_veiculo from tb_vendas where id_venda = '" + (int) jTbl_Venda.getValueAt(jTbl_Venda.getSelectedRow(), 0) + "'");
        try {
            conecta.rs.first();
            int id_veiculo = conecta.rs.getInt("id_veiculo");

            control.AlterarVenda((int) jTbl_Venda.getValueAt(jTbl_Venda.getSelectedRow(), 0), id_veiculo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar código do veiculo\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }

        limpaCampos();
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_anula.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);
        HabilitaDesabilitaCampos(0);
        preencherTabela("select * from tb_veiculos V ,tb_modelos M where M.id_modelo = V.modelo and V.status = 'T' order by id_veiculo");
        preencherTabelaVenda("select * from tb_vendas VD ,tb_clientes_fornecedores C , tb_veiculos V ,tb_modelos M where"//Selecione as tabela
                + " VD.id_cliente = C.id_cliente_fornecedor"
                + " and V.id_veiculo = VD.id_veiculo "
                + " and M.id_modelo = V.modelo"
                + " order by id_venda");

    }//GEN-LAST:event_jBtt_anulaActionPerformed

    private void jBtt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_excluirActionPerformed
        jTxt_codigo.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_anula.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);
        control.ExcluirVenda(Integer.parseInt(jTxt_codigo.getText()));
        limpaCampos();
        HabilitaDesabilitaCampos(0);
        preencherTabela("select * from tb_veiculos V ,tb_modelos M where M.id_modelo = V.modelo and V.status = 'T' order by id_veiculo");
        preencherTabelaVenda("select * from tb_vendas VD ,tb_clientes_fornecedores C , tb_veiculos V ,tb_modelos M where"
                + " VD.id_cliente = C.id_cliente_fornecedor"
                + " and V.id_veiculo = VD.id_veiculo "
                + " and M.id_modelo = V.modelo"
                + " order by id_venda");

    }//GEN-LAST:event_jBtt_excluirActionPerformed

    private void jBtt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_cancelarActionPerformed
        limpaCampos();
        HabilitaDesabilitaCampos(0);
        jTxt_codigo.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_anula.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);
        jBtt_imprimir.setEnabled(false);
    }//GEN-LAST:event_jBtt_cancelarActionPerformed

    private void jCbx_formaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbx_formaPagamentoActionPerformed
        if (jCbx_formaPagamento.getSelectedItem() == "Financiado") {
            jTxt_financiado.setEnabled(true);
            jCbx_banco.setEnabled(true);
        } else {
            jTxt_financiado.setEnabled(!true);
            jCbx_banco.setEnabled(!true);
        }
        jTxt_financiado.setText("0");
    }//GEN-LAST:event_jCbx_formaPagamentoActionPerformed

    private void jTbl_VendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_VendaMouseClicked
        atualizaTabela();
    }//GEN-LAST:event_jTbl_VendaMouseClicked

    private void jTbl_VendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbl_VendaKeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            atualizaTabela();
        }
    }//GEN-LAST:event_jTbl_VendaKeyReleased

    private void jCbx_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbx_ClientesActionPerformed
        if (carregamento) {
            conecta.Conexao(obj_config._url);
            conecta.executaSQL("select fisica_juridica,cpf_cnpj from tb_clientes_fornecedores where nome = '" + ((String) jCbx_Clientes.getSelectedItem()) + "'");
            try {
                conecta.rs.first();

                if (conecta.rs.getString("fisica_juridica").equals("F")) {

                    jLabel7.setText("CPF");
                    formatoCNPJCPF = new MaskFormatter("###.###.###-##");
                } else {
                    jLabel7.setText("CNPJ");
                    formatoCNPJCPF = new MaskFormatter("##.###.###/####-##");
                }
                jFTxt_cpf.setText(String.valueOf(conecta.rs.getString("CPF_CNPJ")));

            } catch (SQLException ex) {
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao inserir a máscara!\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
            }
            conecta.Desconecta();
        }
        carregamento = true;
    }//GEN-LAST:event_jCbx_ClientesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Pesquisa_movimentacao(null, closable, 2).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Pesquisa_Veiculos(null, closable, 2).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JIFCliente_fornecedor janela = new JIFCliente_fornecedor(2);
        Tela.jDesktop.add(janela);
        Tela.centralizaForm(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JIFVeiculos janela = new JIFVeiculos(1);
        Tela.jDesktop.add(janela);
        Tela.centralizaForm(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTxt_valor_vendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_valor_vendaKeyTyped
        if (!((evt.getKeyChar() == ',') || (evt.getKeyChar() == '.') || (evt.getKeyChar() == '1') || (evt.getKeyChar() == '2') || (evt.getKeyChar() == '3') || (evt.getKeyChar() == '4') || (evt.getKeyChar() == '5') || (evt.getKeyChar() == '6') || (evt.getKeyChar() == '7') || (evt.getKeyChar() == '8') || (evt.getKeyChar() == '9') || (evt.getKeyChar() == '0'))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTxt_valor_vendaKeyTyped

    private void jBtt_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_imprimirActionPerformed

        try {
            new Imprimir().Venda_PDF(Integer.parseInt(jTxt_codigo.getText()));
        } catch (NumberFormatException | DocumentException | IOException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao criar arquivo pdf\n\n" + ex, "erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir pdf\n\n" + ex, "erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBtt_imprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtt_anula;
    private javax.swing.JButton jBtt_cancelar;
    private javax.swing.JButton jBtt_excluir;
    private javax.swing.JButton jBtt_imprimir;
    private javax.swing.JButton jBtt_novo;
    private javax.swing.JButton jBtt_salvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    public static javax.swing.JComboBox jCbx_Clientes;
    private javax.swing.JComboBox jCbx_Funcionarios;
    private javax.swing.JComboBox jCbx_banco;
    private javax.swing.JComboBox jCbx_formaPagamento;
    private javax.swing.JComboBox jCbx_garantia;
    private javax.swing.JFormattedTextField jFTxt_cpf;
    private javax.swing.JFormattedTextField jFTxt_datacad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable jTbl_Veiculos_venda;
    public static javax.swing.JTable jTbl_Venda;
    private javax.swing.JTextField jTxt_codigo;
    private javax.swing.JTextField jTxt_financiado;
    private javax.swing.JTextField jTxt_garantia;
    private javax.swing.JFormattedTextField jTxt_valor_venda;
    // End of variables declaration//GEN-END:variables

    public void limpaCampos() {
        jTxt_codigo.setText("");
        jFTxt_datacad.setText("");
        jTxt_valor_venda.setText("");
        jTxt_garantia.setText("");
        jTxt_financiado.setText("");

    }

    public void HabilitaDesabilitaCampos(int acao) {

        if (acao == 1) {
            jCbx_Funcionarios.setEnabled(true);
            jCbx_Clientes.setEnabled(true);
            jCbx_formaPagamento.setEnabled(true);
            jTxt_valor_venda.setEnabled(true);
            jTxt_garantia.setEnabled(true);
            jCbx_garantia.setEnabled(true);
            jTbl_Veiculos_venda.setEnabled(true);
        } else {
            jCbx_Funcionarios.setEnabled(!true);
            jCbx_Clientes.setEnabled(!true);
            jCbx_formaPagamento.setEnabled(!true);
            jTxt_valor_venda.setEnabled(!true);
            jTxt_garantia.setEnabled(!true);
            jCbx_garantia.setEnabled(!true);
            jTbl_Veiculos_venda.setEnabled(!true);
            jCbx_banco.setEnabled(!true);
            jTxt_financiado.setEnabled(!true);
        }
    }

    public void PreencherComboFun(String SQL) {
        conecta.Conexao(obj_config._url);
        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            jCbx_Funcionarios.removeAllItems();
            do {
                jCbx_Funcionarios.addItem(conecta.rs.getString("nome"));
            } while (conecta.rs.next());
        } catch (SQLException ex) {
        }
    }

    public void PreencherComboCliente() {

        conecta.executaSQL("select * from tb_clientes_fornecedores order by nome");
        try {
            conecta.rs.first();
            jCbx_Clientes.removeAllItems();
            if (conecta.rs.getString("fisica_juridica").equals("F")) {

                jLabel7.setText("CPF");
                formatoCNPJCPF = new MaskFormatter("###.###.###-##");
            } else {
                jLabel7.setText("CNPJ");
                formatoCNPJCPF = new MaskFormatter("##.###.###/####-##");
            }
            jFTxt_cpf.setText(String.valueOf(conecta.rs.getString("CPF_CNPJ")));

            do {
                jCbx_Clientes.addItem(conecta.rs.getString("nome"));
            } while (conecta.rs.next());
        } catch (SQLException ex) {
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir a máscara!\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
        conecta.Desconecta();
    }

    public boolean preencherObjeto() {

        model.setId_venda(Integer.parseInt(jTxt_codigo.getText()));
        model.setDatacad((Date) validar.formDataStrToData(jFTxt_datacad.getText()));
        if ("".equals(jTxt_valor_venda.getText())) {
            JOptionPane.showMessageDialog(null, "Complete o campo valor vendido!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        model.setCliente((String) (jCbx_Clientes.getSelectedItem()));
        model.setFuncionario((String) (jCbx_Funcionarios.getSelectedItem()));

        try {
            model.setId_veiculo((int) jTbl_Veiculos_venda.getValueAt(jTbl_Veiculos_venda.getSelectedRow(), 0));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione o veículo de venda!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (Double.valueOf(jTxt_valor_venda.getText().replaceAll("\\.", "").replaceAll("\\,", ".")) < Double.valueOf((String) jTbl_Veiculos_venda.getValueAt(jTbl_Veiculos_venda.getSelectedRow(), 6))) {
            JOptionPane.showMessageDialog(null, "Nao pode vender o veiculo baixo valor da vendido!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        model.setForma_pagamento((String) jCbx_formaPagamento.getSelectedItem());

        if (("".equals(jTxt_valor_venda.getText()))) {
            JOptionPane.showMessageDialog(null, "Erro no Valor venda!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        model.setValor_total(Float.valueOf(jTxt_valor_venda.getText().replaceAll("\\.", "").replaceAll("\\,", ".")));

        if (jCbx_formaPagamento.getSelectedItem() == "Financiado") {
            if (("".equals(jTxt_financiado.getText()))) {
                JOptionPane.showMessageDialog(null, "Erro no Valor venda!", "Erro", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            model.setValor_financiado(Float.valueOf(jTxt_financiado.getText().replaceAll("\\.", "").replaceAll("\\,", ".")));

        } else {
            model.setValor_financiado(0);
        }

        model.setBanco((String) jCbx_banco.getSelectedItem());

        if ("".equals(jTxt_garantia.getText())) {
            JOptionPane.showMessageDialog(null, "Complete o campo de garantia!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        int garantia = Integer.parseInt(jTxt_garantia.getText());
        model.setTempo_garantia(garantia);
        if ("MÊS".equals((String) jCbx_garantia.getSelectedItem())) {
            model.setTipo_garantia("MES");
        } else {
            model.setTipo_garantia((String) jCbx_garantia.getSelectedItem());
        }
        return true;
    }

    public void preencherTabela(String SQL) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Veiculo", "Marca", "Modelo", "Versão", "Placa", "Valor Veiculo"};
        conecta.Conexao(obj_config._url);
        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();

            do {
                String Veiculo = null;
                if (conecta.rs.getString("veiculo").equals("M")) {
                    Veiculo = "Moto";
                } else if (conecta.rs.getString("veiculo").equals("A")) {
                    Veiculo = "Automovel";
                } else if (conecta.rs.getString("veiculo").equals("M")) {
                    Veiculo = "Micro/Ônibus";
                } else if (conecta.rs.getString("veiculo").equals("C")) {
                    Veiculo = "Caminhão";
                }
                dados.add(new Object[]{conecta.rs.getInt("id_veiculo"), Veiculo, conecta.rs.getString("marca"), conecta.rs.getString("descricao"), conecta.rs.getString("versao"), conecta.rs.getString("placa"), conecta.rs.getString("valor_venda")});

            } while (conecta.rs.next());

        } catch (SQLException ex) {

        }
        conecta.Desconecta();
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTbl_Veiculos_venda.setModel(modelo);
        jTbl_Veiculos_venda.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTbl_Veiculos_venda.getColumnModel().getColumn(0).setResizable(false);
        jTbl_Veiculos_venda.getColumnModel().getColumn(1).setPreferredWidth(70);
        jTbl_Veiculos_venda.getColumnModel().getColumn(1).setResizable(false);
        jTbl_Veiculos_venda.getColumnModel().getColumn(2).setPreferredWidth(107);
        jTbl_Veiculos_venda.getColumnModel().getColumn(2).setResizable(false);
        jTbl_Veiculos_venda.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTbl_Veiculos_venda.getColumnModel().getColumn(3).setResizable(false);
        jTbl_Veiculos_venda.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTbl_Veiculos_venda.getColumnModel().getColumn(4).setResizable(false);
        jTbl_Veiculos_venda.getColumnModel().getColumn(5).setPreferredWidth(78);
        jTbl_Veiculos_venda.getColumnModel().getColumn(5).setResizable(false);
        jTbl_Veiculos_venda.getColumnModel().getColumn(6).setPreferredWidth(85);
        jTbl_Veiculos_venda.getColumnModel().getColumn(6).setResizable(false);
        jTbl_Veiculos_venda.getTableHeader().setReorderingAllowed(false);
        jTbl_Veiculos_venda.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTbl_Veiculos_venda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void preencherTabelaVenda(String SQL) {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Nulo", "Data", "Funcionarios", "Cliente", "Valor"};
        conecta.Conexao(obj_config._url);
        conecta.executaSQL(SQL);
        conFun.Conexao(obj_config._url);
        try {
            conecta.rs.first();

            do {
                conFun.executaSQL("select nome from tb_funcionarios where id_funcionario = " + conecta.rs.getInt("id_funcionario"));
                conFun.rs.first();
                String NULO = conecta.rs.getString("nulo");
                if ("T".equals(NULO)) {
                    NULO = "SIM";
                } else {
                    NULO = "---";
                }
                dados.add(new Object[]{conecta.rs.getInt("id_venda"), NULO, (validar.formDataDateToStr(conecta.rs.getDate("datacad"))), conFun.rs.getString("nome"), conecta.rs.getString("nome"), conecta.rs.getFloat("Valor_total")});
            } while (conecta.rs.next());

        } catch (SQLException ex) {
        }
        conFun.Desconecta();
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTbl_Venda.setModel(modelo);
        jTbl_Venda.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTbl_Venda.getColumnModel().getColumn(0).setResizable(false);
        jTbl_Venda.getColumnModel().getColumn(1).setPreferredWidth(40);
        jTbl_Venda.getColumnModel().getColumn(1).setResizable(false);
        jTbl_Venda.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTbl_Venda.getColumnModel().getColumn(2).setResizable(false);
        jTbl_Venda.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTbl_Venda.getColumnModel().getColumn(3).setResizable(false);
        jTbl_Venda.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTbl_Venda.getColumnModel().getColumn(4).setResizable(false);
        jTbl_Venda.getColumnModel().getColumn(5).setPreferredWidth(70);
        jTbl_Venda.getColumnModel().getColumn(5).setResizable(false);
        jTbl_Venda.getTableHeader().setReorderingAllowed(false);
        jTbl_Venda.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTbl_Venda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    public void atualizaTabela() {
        limpaCampos();
        conecta.Conexao(obj_config._url);
        conecta.executaSQL("select * from tb_vendas where id_venda = '" + jTbl_Venda.getValueAt(jTbl_Venda.getSelectedRow(), 0) + "'");
        try {
            conecta.rs.first();

            int Veiculo = conecta.rs.getInt("id_veiculo"), Clientes = conecta.rs.getInt("id_cliente"), Funcionarios = conecta.rs.getInt("id_funcionario");

            jTxt_codigo.setText(String.valueOf(conecta.rs.getInt("id_venda")));
            jFTxt_datacad.setText(validar.formDataDateToStr(conecta.rs.getDate("datacad")));
            jCbx_formaPagamento.setSelectedItem(conecta.rs.getString("forma_pagamento"));
            jTxt_valor_venda.setText(String.valueOf(conecta.rs.getDouble("valor_total")));
            jTxt_garantia.setText(conecta.rs.getString("tempo_garantia"));
            if ("Mes".equals((String) conecta.rs.getString("tipo_garantia"))) {

                jCbx_garantia.setSelectedItem("Mês");
            } else {
                jCbx_garantia.setSelectedItem((String) conecta.rs.getString("tipo_garantia"));
            }
            jCbx_banco.setSelectedItem(conecta.rs.getString("banco"));
            jTxt_financiado.setText(conecta.rs.getString("valor_financiado"));

            conecta.executaSQL("select nome,cpf_cnpj from tb_clientes_fornecedores where id_cliente_fornecedor = '" + Clientes + "'");
            conecta.rs.first();
            jCbx_Clientes.setSelectedItem(conecta.rs.getString("nome"));
            conecta.Desconecta();
            preencherTabela("select * from tb_veiculos V ,tb_modelos M where M.id_modelo = V.modelo and V.id_veiculo ='" + Veiculo + "'  order by id_veiculo");

            if (!"SIM".equals(jTbl_Venda.getValueAt(jTbl_Venda.getSelectedRow(), 1))) {
                jBtt_anula.setEnabled(true);
                jBtt_excluir.setEnabled(!true);
            } else {
                jBtt_anula.setEnabled(!true);
                jBtt_excluir.setEnabled(true);
            }
            PreencherComboFun("select nome from tb_funcionarios where id_funcionario = '" + Funcionarios + "'");
            jBtt_novo.setEnabled(false);
            jBtt_salvar.setEnabled(false);
            jBtt_cancelar.setEnabled(true);
            jBtt_imprimir.setEnabled(true);
            HabilitaDesabilitaCampos(0);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados do registro!\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

}
