/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ControleVeiculos;
import Controle.Maiuscula;
import Controle.ModeloTabela;
import Controle.Numeric;
import Controle.Validacoes;
import Controle.cadastro;
import Modelo.ModeloVeiculos;
import static Visao.JIFTroca.jTbl_Veiculos_saida;
import static Visao.JIFVenda.jTbl_Veiculos_venda;
import static Visao.Tela.jDesktop;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.math.BigDecimal;
import java.nio.channels.FileChannel;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Murylo César Souza
 */
public class JIFVeiculos extends javax.swing.JInternalFrame {

    ConectaBanco conMod = new ConectaBanco();
    ConectaBanco conecta = new ConectaBanco();
    ModeloVeiculos model = new ModeloVeiculos();
    ControleVeiculos control = new ControleVeiculos();
    Validacoes validar = new Validacoes();
    cadastro obj_config = new cadastro();
    MaskFormatter formatoData, anomodelo, Placa;
    DecimalFormat formatoDecimal = new DecimalFormat("##,###,###,##0.00");
    DecimalFormat formatoDecimal_lucro = new DecimalFormat("#,##0.00");
    NumberFormat Fd = NumberFormat.getInstance();
    int flag = 0;
    private String URL_Foto;
    private boolean seletor = false;
    private String formato = "????";
    String fotoAntida;

    int Movimentacao;

    /**
     * Creates new form JIFVeiculos
     *
     * @param movimentacao
     */
    public JIFVeiculos(int movimentacao) {
        Movimentacao = movimentacao;
        try {

            initComponents();
            obj_config.carregaconfig();
            double Lucro = obj_config._LucroVeiculoEntrada;
            jTxt_quilometro.setDocument(new Numeric(15));
            jTxt_versao.setDocument(new Maiuscula(50));
            jTxt_chassi.setDocument(new Maiuscula(17));
            jTxt_obs.setDocument(new Maiuscula(100));
            jCbx_marca.setModel(new javax.swing.DefaultComboBoxModel(validar.preencherCampo((String) jCbx_veiculo.getSelectedItem())));
            imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
            PreencherCombo("select descricao from tb_modelos where marca = '" + (String) jCbx_marca.getSelectedItem() + "' and veiculo ='" + (String) jCbx_veiculo.getSelectedItem() + "' order by descricao");
            preencherTabela();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Por favor configure o lucro do veiculo de entrada", "Erro", JOptionPane.ERROR_MESSAGE);
            JIFConf janela = new JIFConf();
            jDesktop.add(janela);
            Tela.centralizaForm(janela);
            janela.setVisible(true);
            dispose();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel113 = new javax.swing.JLabel();
        jTxt_codigo = new javax.swing.JTextField();
        jLabel115 = new javax.swing.JLabel();
        try{
            formatoData= new MaskFormatter("##/##/####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_datacad = new JFormattedTextField(formatoData);
        ;
        jLabel111 = new javax.swing.JLabel();
        jCbx_veiculo = new javax.swing.JComboBox();
        jRBt_compra = new javax.swing.JRadioButton();
        jRBt_troca = new javax.swing.JRadioButton();
        jLabel112 = new javax.swing.JLabel();
        jCbx_condicao = new javax.swing.JComboBox();
        jLabel114 = new javax.swing.JLabel();
        jTxt_quilometro = new javax.swing.JTextField();
        jCbx_marca = new javax.swing.JComboBox();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jCbx_modelo = new javax.swing.JComboBox();
        jLabel122 = new javax.swing.JLabel();
        jTxt_versao = new javax.swing.JTextField();
        jLabel125 = new javax.swing.JLabel();
        jTxt_chassi = new javax.swing.JTextField();
        imagem = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        try{
            formatoData = new MaskFormatter("##/##/####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_dataFabricacao = new JFormattedTextField(formatoData);
        ;
        jLabel124 = new javax.swing.JLabel();
        try{
            anomodelo= new MaskFormatter("##/##");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_anoModelo = new JFormattedTextField(anomodelo);
        ;
        jLabel127 = new javax.swing.JLabel();
        jCbx_porte = new javax.swing.JComboBox();
        jLabel126 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jCbx_cor = new javax.swing.JComboBox();
        jLabel129 = new javax.swing.JLabel();
        jCbx_porta = new javax.swing.JComboBox();
        jLabel116 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jTxt_obs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRBt_completo = new javax.swing.JRadioButton();
        jRBt_flex = new javax.swing.JRadioButton();
        jRBt_direcao = new javax.swing.JRadioButton();
        jRBt_arC = new javax.swing.JRadioButton();
        jBtt_alterafoto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTbl_Veiculos = new javax.swing.JTable();
        jRBt_entrada = new javax.swing.JRadioButton();
        jRBt_vendido_trocado = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jBtt_novo = new javax.swing.JButton();
        jBtt_salvar = new javax.swing.JButton();
        jBtt_editar = new javax.swing.JButton();
        jBtt_excluir = new javax.swing.JButton();
        jBtt_cancelar = new javax.swing.JButton();
        try{
            Placa= new MaskFormatter("UUU-####");

        }catch(Exception ex){

            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");

        }
        jFTxt_placa = new JFormattedTextField(Placa);
        ;
        jRBt_Modelos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTxt_valor_venda = new javax.swing.JTextField();
        try{
            formatoDecimal= new DecimalFormat("##,###,###,##0.00");

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");
        }
        jTxt_valor_pago = jTxt_valor_pago =  new JFormattedTextField(formatoDecimal);
        try{
            formatoDecimal_lucro = new DecimalFormat("#,##0.00");

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Não foi possível setar a mascara");
        }
        jTxt_lucro = jTxt_lucro =  new JFormattedTextField(formatoDecimal_lucro);
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setTitle("Cadastro de Veiculos");

        jLabel113.setText("Codigo");

        jTxt_codigo.setEnabled(false);

        jLabel115.setText("Data entrada");

        jFTxt_datacad.setEnabled(false);

        jLabel111.setText("Veiculo");

        jCbx_veiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Moto", "Automovel", "Micro/Ônibus", "Caminhão" }));
        jCbx_veiculo.setEnabled(false);
        jCbx_veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbx_veiculoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBt_compra);
        jRBt_compra.setSelected(true);
        jRBt_compra.setText("Compra");
        jRBt_compra.setEnabled(false);

        buttonGroup1.add(jRBt_troca);
        jRBt_troca.setText("Troca");
        jRBt_troca.setEnabled(false);

        jLabel112.setText("Condição");

        jCbx_condicao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novo", "Semi", "Usado" }));
        jCbx_condicao.setEnabled(false);
        jCbx_condicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbx_condicaoActionPerformed(evt);
            }
        });

        jLabel114.setText("Quilometragens");

        jTxt_quilometro.setText("0");
        jTxt_quilometro.setEnabled(false);
        jTxt_quilometro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_quilometroKeyTyped(evt);
            }
        });

        jCbx_marca.setEnabled(false);
        jCbx_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbx_marcaActionPerformed(evt);
            }
        });

        jLabel120.setText("Marca");

        jLabel121.setText("Modelo");

        jCbx_modelo.setEnabled(false);

        jLabel122.setText("Versão");

        jTxt_versao.setEnabled(false);

        jLabel125.setText("Chassi");

        jTxt_chassi.setEnabled(false);
        jTxt_chassi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_chassiKeyTyped(evt);
            }
        });

        imagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagem.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        imagem.setMaximumSize(new java.awt.Dimension(265, 200));
        imagem.setPreferredSize(new java.awt.Dimension(265, 200));

        jLabel123.setText("Data Fab.");

        jFTxt_dataFabricacao.setEnabled(false);

        jLabel124.setText("Ano Modelo");

        jFTxt_anoModelo.setEnabled(false);

        jLabel127.setText("Porte");

        jCbx_porte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pequeno", "Medio", "Grande" }));
        jCbx_porte.setEnabled(false);

        jLabel126.setText("Placa");

        jLabel128.setText("Cor");

        jCbx_cor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Preto", "Branco", "Vermelho", "Prata", "Amarelo" }));
        jCbx_cor.setEnabled(false);

        jLabel129.setText("N° porta");

        jCbx_porta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4" }));
        jCbx_porta.setEnabled(false);

        jLabel116.setText("Valor pago");

        jLabel3.setText("Lucro +");

        jLabel130.setText("Obs:");

        jTxt_obs.setEnabled(false);

        jLabel1.setText("Adicionais");

        jRBt_completo.setText("Completo");
        jRBt_completo.setEnabled(false);
        jRBt_completo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBt_completoActionPerformed(evt);
            }
        });

        jRBt_flex.setText("Flex");
        jRBt_flex.setEnabled(false);
        jRBt_flex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBt_flexActionPerformed(evt);
            }
        });

        jRBt_direcao.setText("Direção hidralica");
        jRBt_direcao.setEnabled(false);
        jRBt_direcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBt_direcaoActionPerformed(evt);
            }
        });

        jRBt_arC.setText("Ar condicionado");
        jRBt_arC.setEnabled(false);
        jRBt_arC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBt_arCActionPerformed(evt);
            }
        });

        jBtt_alterafoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/foto.png"))); // NOI18N
        jBtt_alterafoto.setText("Alterar Foto");
        jBtt_alterafoto.setEnabled(false);
        jBtt_alterafoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_alterafotoActionPerformed(evt);
            }
        });

        jTbl_Veiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTbl_Veiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbl_VeiculosMouseClicked(evt);
            }
        });
        jTbl_Veiculos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbl_VeiculosKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTbl_Veiculos);

        buttonGroup2.add(jRBt_entrada);
        jRBt_entrada.setText("Entrada");
        jRBt_entrada.setEnabled(false);

        buttonGroup2.add(jRBt_vendido_trocado);
        jRBt_vendido_trocado.setText("Vendido/Trocado");
        jRBt_vendido_trocado.setEnabled(false);

        jLabel4.setText("Status");

        jBtt_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/new.png"))); // NOI18N
        jBtt_novo.setText("Novo");
        jBtt_novo.setToolTipText("Novo");
        jBtt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_novoActionPerformed(evt);
            }
        });

        jBtt_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save.png"))); // NOI18N
        jBtt_salvar.setText("salvar");
        jBtt_salvar.setToolTipText("Salvar");
        jBtt_salvar.setEnabled(false);
        jBtt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_salvarActionPerformed(evt);
            }
        });

        jBtt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jBtt_editar.setText("Editar");
        jBtt_editar.setToolTipText("Editar");
        jBtt_editar.setEnabled(false);
        jBtt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_editarActionPerformed(evt);
            }
        });

        jBtt_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/del.png"))); // NOI18N
        jBtt_excluir.setText("Excluir");
        jBtt_excluir.setToolTipText("Excluir");
        jBtt_excluir.setEnabled(false);
        jBtt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_excluirActionPerformed(evt);
            }
        });

        jBtt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancela.png"))); // NOI18N
        jBtt_cancelar.setText("Cancelar");
        jBtt_cancelar.setToolTipText("Cancelar");
        jBtt_cancelar.setEnabled(false);
        jBtt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtt_cancelarActionPerformed(evt);
            }
        });

        jFTxt_placa.setEnabled(false);

        jRBt_Modelos.setText("+");
        jRBt_Modelos.setEnabled(false);
        jRBt_Modelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBt_ModelosActionPerformed(evt);
            }
        });

        jButton1.setText("Pesquisa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTxt_valor_venda.setEnabled(false);

        jTxt_valor_pago.setEnabled(false);
        jTxt_valor_pago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxt_valor_pagoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_valor_pagoKeyTyped(evt);
            }
        });

        jTxt_lucro.setEnabled(false);
        jTxt_lucro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxt_lucroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_lucroKeyTyped(evt);
            }
        });

        jLabel2.setText("Valor venda");

        jButton2.setText("Estoque");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel123)
                                        .addComponent(jLabel111, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel113, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel115)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFTxt_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jRBt_compra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRBt_troca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jFTxt_dataFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCbx_veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(jLabel112)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jCbx_condicao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel114)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTxt_quilometro, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jLabel124)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jFTxt_anoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel127)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCbx_porte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxt_chassi, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCbx_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRBt_Modelos)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel120, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel122, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel126, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel130, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jCbx_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel121, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTxt_obs, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTxt_versao, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel125))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(3, 3, 3)
                                                    .addComponent(jFTxt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(24, 24, 24)
                                                    .addComponent(jLabel128)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jCbx_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel129)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jCbx_porta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jRBt_completo)
                                                    .addGap(4, 4, 4)
                                                    .addComponent(jRBt_flex)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jRBt_direcao)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jRBt_arC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel116)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTxt_valor_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxt_lucro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxt_valor_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBt_entrada)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBt_vendido_trocado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBtt_alterafoto))
                                    .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 15, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtt_novo)
                                .addGap(18, 18, 18)
                                .addComponent(jBtt_salvar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtt_editar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtt_excluir)
                                .addGap(18, 18, 18)
                                .addComponent(jBtt_cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(28, 28, 28)
                                .addComponent(jButton1)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel126, jLabel130});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel111, jLabel113, jLabel120, jLabel122, jLabel123});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRBt_compra)
                                    .addComponent(jRBt_troca)
                                    .addComponent(jFTxt_datacad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel115)
                                    .addComponent(jTxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel113, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCbx_veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel111))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel114)
                                .addComponent(jCbx_condicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxt_quilometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel112)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jFTxt_anoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel127)
                                .addComponent(jCbx_porte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel123)
                                .addComponent(jFTxt_dataFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel124)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel121)
                                .addComponent(jCbx_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCbx_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel120))
                            .addComponent(jRBt_Modelos, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel122)
                            .addComponent(jTxt_versao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel125)
                            .addComponent(jTxt_chassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel126)
                            .addComponent(jLabel128)
                            .addComponent(jCbx_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel129)
                            .addComponent(jCbx_porta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTxt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jRBt_completo)
                            .addComponent(jRBt_flex)
                            .addComponent(jRBt_direcao)
                            .addComponent(jRBt_arC))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel130)
                            .addComponent(jTxt_obs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel116)
                    .addComponent(jLabel3)
                    .addComponent(jBtt_alterafoto)
                    .addComponent(jRBt_entrada)
                    .addComponent(jRBt_vendido_trocado)
                    .addComponent(jLabel4)
                    .addComponent(jTxt_valor_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_valor_pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_lucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtt_novo)
                    .addComponent(jBtt_salvar)
                    .addComponent(jBtt_editar)
                    .addComponent(jBtt_excluir)
                    .addComponent(jBtt_cancelar)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCbx_condicao, jCbx_cor, jCbx_marca, jCbx_modelo, jCbx_porta, jCbx_porte, jCbx_veiculo});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jFTxt_anoModelo, jFTxt_dataFabricacao, jFTxt_datacad, jTxt_codigo, jTxt_obs, jTxt_quilometro, jTxt_versao});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel111, jLabel112, jLabel113, jLabel114, jLabel115, jLabel116, jLabel120, jLabel121, jLabel122, jLabel123, jLabel124, jLabel125, jLabel126, jLabel127, jLabel128, jLabel129, jLabel130, jLabel3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCbx_condicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbx_condicaoActionPerformed
        if (jCbx_condicao.getSelectedItem() == "Novo") {
            jTxt_quilometro.setText("0");
            jTxt_quilometro.setEnabled(!true);
            jRBt_compra.setSelected(true);
            jRBt_compra.setEnabled(!true);
            jRBt_troca.setEnabled(!true);
        } else {
            jTxt_quilometro.setText("0");
            jTxt_quilometro.setEnabled(true);
            jRBt_compra.setEnabled(true);
            jRBt_troca.setEnabled(true);
        }

    }//GEN-LAST:event_jCbx_condicaoActionPerformed

    private void jBtt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_novoActionPerformed

        limpaCampos();
        flag = 0;
        conecta.Conexao(obj_config._url);
        conecta.executaSQL("select id_veiculo from tb_veiculos order by id_veiculo");

        try {
            if (!conecta.rs.last()) {
                jTxt_codigo.setText("1");
            } else {
                jTxt_codigo.setText(String.valueOf(conecta.rs.getInt("id_veiculo") + 1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir registro");
        }

        conecta.Desconecta();
        java.util.Date datahoje = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        jFTxt_datacad.setText(df.format(datahoje));
        HabilitaDesabilitaCampos(1);
        jBtt_novo.setEnabled(false);
        jBtt_salvar.setEnabled(true);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(true);

        jRBt_compra.setEnabled(!true);
        jRBt_troca.setEnabled(!true);
        jTxt_quilometro.setText("0");
        jTxt_quilometro.setEnabled(!true);
        jRBt_completo.setEnabled(!true);
        jRBt_flex.setEnabled(true);
        jRBt_direcao.setEnabled(!true);
        jRBt_arC.setEnabled(!true);
        jCbx_porta.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"0"}));
        jCbx_porta.setEnabled(!true);
        imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));

    }//GEN-LAST:event_jBtt_novoActionPerformed

    private void jBtt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_salvarActionPerformed
        if (preencherObjeto()) {

            boolean exe = false;

            if ((flag == 0) && (control.GravarVeiculos(model))) {
                exe = true;
            } else if ((flag != 0) && (control.AlterarVeiculos(model))) {

                if (seletor) {
                    exe = true;
                    if ((!"".equals(fotoAntida)) && (new File("Imagens\\" + fotoAntida).exists()) && (!new File("Imagens\\" + fotoAntida).delete())) {
                        JOptionPane.showMessageDialog(null, "Arquivo nao deletado");
                    }
                }
            }
            if (exe) {
                if ((seletor) && (new File(URL_Foto).exists())) {
                    try {
                        FileInputStream origem = new FileInputStream(URL_Foto);  //arquivo que você quer copiar
                        FileOutputStream destino = new FileOutputStream("Imagens\\" + jTxt_codigo.getText() + formato); //onde irá ficar a copia do aquivo
                        FileChannel fcOrigem = origem.getChannel();
                        FileChannel fcDestino = destino.getChannel();
                        fcOrigem.transferTo(0, fcOrigem.size(), fcDestino);//copiando o arquivo e salvando no diretório que você escolheu  
                        destino.close();
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Erro ao copiar imagem\n\n" + ex);
                    }
                }
            }
            limpaCampos();
            preencherTabela();
            HabilitaDesabilitaCampos(0);
            jTxt_codigo.setEnabled(false);
            jBtt_novo.setEnabled(true);
            jBtt_salvar.setEnabled(false);
            jBtt_editar.setEnabled(false);
            jBtt_excluir.setEnabled(false);
            jBtt_cancelar.setEnabled(false);
            imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
            Movimentacao();

        }
    }//GEN-LAST:event_jBtt_salvarActionPerformed

    private void jBtt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_editarActionPerformed

        flag = 1;
        HabilitaDesabilitaCampos(1);
        jBtt_novo.setEnabled(false);
        jBtt_salvar.setEnabled(true);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(true);

        fotoAntida = URL_Foto;
        if (jCbx_veiculo.getSelectedItem() == "Moto") {
            jRBt_completo.setEnabled(!true);
            jRBt_flex.setEnabled(true);
            jRBt_direcao.setEnabled(!true);
            jRBt_arC.setEnabled(!true);

        } else {
            jRBt_completo.setEnabled(true);
            jRBt_flex.setEnabled(true);
            jRBt_direcao.setEnabled(true);
            jRBt_arC.setEnabled(true);
        }
        if (jCbx_condicao.getSelectedItem() == "Novo") {
            jTxt_quilometro.setEnabled(!true);
            jRBt_compra.setEnabled(!true);
            jRBt_troca.setEnabled(!true);
        } else {
            jTxt_quilometro.setText("0");
        }
        seletor = false;
    }//GEN-LAST:event_jBtt_editarActionPerformed

    private void jBtt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_excluirActionPerformed
        jTxt_codigo.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);

        if ((control.ExcluirVeiculos(Integer.parseInt(jTxt_codigo.getText())))) {
            if (((new File("Imagens\\" + URL_Foto)).exists()) && !"".equals(URL_Foto)) {
                if (!new File("Imagens\\" + URL_Foto).delete()) {

                    JOptionPane.showMessageDialog(null, "Foto não deletada");
                }
            }
        }
        limpaCampos();
        HabilitaDesabilitaCampos(0);
        preencherTabela();
        imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
        Movimentacao();

    }//GEN-LAST:event_jBtt_excluirActionPerformed

    private void jBtt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_cancelarActionPerformed
        limpaCampos();
        HabilitaDesabilitaCampos(0);
        jTxt_codigo.setEnabled(false);
        jBtt_novo.setEnabled(true);
        jBtt_salvar.setEnabled(false);
        jBtt_editar.setEnabled(false);
        jBtt_excluir.setEnabled(false);
        jBtt_cancelar.setEnabled(false);
        imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));

    }//GEN-LAST:event_jBtt_cancelarActionPerformed

    private void jTbl_VeiculosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbl_VeiculosKeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            atualizaTabela();
        }
    }//GEN-LAST:event_jTbl_VeiculosKeyReleased

    private void jTbl_VeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbl_VeiculosMouseClicked
        atualizaTabela();
    }//GEN-LAST:event_jTbl_VeiculosMouseClicked

    private void jRBt_completoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBt_completoActionPerformed
        if (jRBt_completo.isSelected()) {
            jRBt_flex.setSelected(true);
            jRBt_direcao.setSelected(true);
            jRBt_arC.setSelected(true);
        } else {
            jRBt_flex.setSelected(!true);
            jRBt_direcao.setSelected(!true);
            jRBt_arC.setSelected(!true);
        }
    }//GEN-LAST:event_jRBt_completoActionPerformed

    private void jBtt_alterafotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtt_alterafotoActionPerformed
        try {
            javax.swing.JFileChooser busca_foto = new javax.swing.JFileChooser();
            busca_foto.setMultiSelectionEnabled(false);
            busca_foto.setCurrentDirectory(new File("D:\\"));
            busca_foto.setDialogTitle("Selecione a foto do veiculo");
            busca_foto.setFileFilter(new FileNameExtensionFilter("JPG, GIF, BMP e PNG", "jpg", "gif", "png", "bmp"));//nao entendi pq tem que repetir as extencoes  
            busca_foto.setFileSelectionMode(JFileChooser.FILES_ONLY);

            if (busca_foto.showOpenDialog(this) == 0) {// se clica em abrir imagem faz isso... 

                char[] format = formato.toCharArray(), foto = busca_foto.getSelectedFile().getName().toCharArray();
                format[0] = foto[busca_foto.getSelectedFile().getName().length() - 4];
                format[1] = foto[busca_foto.getSelectedFile().getName().length() - 3];
                format[2] = foto[busca_foto.getSelectedFile().getName().length() - 2];
                format[3] = foto[busca_foto.getSelectedFile().getName().length() - 1];
                char[] upper = String.valueOf(format).toCharArray();
                for (int i = 0; i < upper.length; i++) {
                    upper[i] = Character.toUpperCase(upper[i]);
                }
                formato = String.valueOf(upper);
                if ((".PNG".equals(formato)) || (".JPG".equals(formato)) || (".GIF".equals(formato)) || (".BMP".equals(formato))) {

                    URL_Foto = busca_foto.getSelectedFile().getAbsolutePath();
                    imagem.setIcon(new ImageIcon(new ImageIcon(busca_foto.getSelectedFile().getAbsolutePath()).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
                    seletor = true;
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor selecione as imagens com o formato:\n\n.PNG, .JPG, .GIF, .BMP");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir seletor de arquivo\n\n!" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtt_alterafotoActionPerformed

    private void jCbx_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbx_marcaActionPerformed
        imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
        PreencherCombo("select descricao from tb_modelos where marca = '" + (String) jCbx_marca.getSelectedItem() + "' and veiculo ='" + (String) jCbx_veiculo.getSelectedItem() + "' order by descricao");
        URL_Foto = "";
    }//GEN-LAST:event_jCbx_marcaActionPerformed

    private void jCbx_veiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbx_veiculoActionPerformed
        if (jCbx_veiculo.getSelectedItem() == "Moto") {
            jRBt_completo.setEnabled(!true);
            jRBt_flex.setEnabled(true);
            jRBt_direcao.setEnabled(!true);
            jRBt_arC.setEnabled(!true);

            jRBt_completo.setSelected(!true);
            jRBt_flex.setSelected(!true);
            jRBt_direcao.setSelected(!true);
            jRBt_arC.setSelected(!true);
            jCbx_porta.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"0"}));
            jCbx_porta.setEnabled(!true);
        } else {
            jRBt_completo.setEnabled(true);
            jRBt_flex.setEnabled(true);
            jRBt_direcao.setEnabled(true);
            jRBt_arC.setEnabled(true);
            jCbx_porta.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"2", "3", "4"}));
            jCbx_porta.setEnabled(true);
        }
        URL_Foto = "";
        jCbx_marca.setModel(new javax.swing.DefaultComboBoxModel(validar.preencherCampo((String) jCbx_veiculo.getSelectedItem())));
        imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
        PreencherCombo("select descricao from tb_modelos where marca = '" + (String) jCbx_marca.getSelectedItem() + "' and veiculo ='" + (String) jCbx_veiculo.getSelectedItem() + "' order by descricao");
    }//GEN-LAST:event_jCbx_veiculoActionPerformed

    private void jRBt_direcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBt_direcaoActionPerformed
        cbx();
    }//GEN-LAST:event_jRBt_direcaoActionPerformed

    private void jRBt_flexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBt_flexActionPerformed
        cbx();
    }//GEN-LAST:event_jRBt_flexActionPerformed

    private void jRBt_arCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBt_arCActionPerformed
        cbx();
    }//GEN-LAST:event_jRBt_arCActionPerformed

    private void jRBt_ModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBt_ModelosActionPerformed
        JIFModelos janela = new JIFModelos();
        Tela.jDesktop.add(janela);
        Tela.centralizaForm(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_jRBt_ModelosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Pesquisa_Veiculos(null, closable, 1).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxt_chassiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_chassiKeyTyped
        if ((evt.getKeyChar() == 'o') || (evt.getKeyChar() == 'q') || (evt.getKeyChar() == 'i')
                || (evt.getKeyChar() == 'O') || (evt.getKeyChar() == 'Q') || (evt.getKeyChar() == 'I') || (evt.getKeyChar() == ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTxt_chassiKeyTyped

    private void jTxt_quilometroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_quilometroKeyTyped
        if ((evt.getKeyChar() == '.') || (evt.getKeyChar() == ',')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTxt_quilometroKeyTyped

    private void jTxt_valor_pagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_valor_pagoKeyReleased
        jTxt_valor_venda.setText(Fd.format(new BigDecimal(validar.Lucro_Veiculo_Entrada(jTxt_valor_pago.getText(), jTxt_lucro.getText(), obj_config._LucroVeiculoEntrada / 100))));
    }//GEN-LAST:event_jTxt_valor_pagoKeyReleased

    private void jTxt_lucroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_lucroKeyReleased
        jTxt_valor_venda.setText(Fd.format(new BigDecimal(validar.Lucro_Veiculo_Entrada(jTxt_valor_pago.getText(), jTxt_lucro.getText(), obj_config._LucroVeiculoEntrada / 100))));
    }//GEN-LAST:event_jTxt_lucroKeyReleased

    private void jTxt_valor_pagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_valor_pagoKeyTyped
        if (!((evt.getKeyChar() == ',') || (evt.getKeyChar() == '.') || (evt.getKeyChar() == '1') || (evt.getKeyChar() == '2') || (evt.getKeyChar() == '3') || (evt.getKeyChar() == '4') || (evt.getKeyChar() == '5') || (evt.getKeyChar() == '6') || (evt.getKeyChar() == '7') || (evt.getKeyChar() == '8') || (evt.getKeyChar() == '9') || (evt.getKeyChar() == '0'))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTxt_valor_pagoKeyTyped

    private void jTxt_lucroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_lucroKeyTyped
        if (!((evt.getKeyChar() == ',') || (evt.getKeyChar() == '.') || (evt.getKeyChar() == '1') || (evt.getKeyChar() == '2') || (evt.getKeyChar() == '3') || (evt.getKeyChar() == '4') || (evt.getKeyChar() == '5') || (evt.getKeyChar() == '6') || (evt.getKeyChar() == '7') || (evt.getKeyChar() == '8') || (evt.getKeyChar() == '9') || (evt.getKeyChar() == '0'))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTxt_lucroKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        conecta.Conexao(obj_config._url);
        conecta.executaSQL("select count(*) from tb_veiculos where status = 'T' and veiculo ='M'");
        try {
            int motos, automovel, onibus, caminhao;
            if (conecta.rs.first()) {
                motos = conecta.rs.getInt("count");
            } else {
                motos = 0;
            }

            conecta.Desconecta();
            conecta.Conexao(obj_config._url);
            conecta.executaSQL("select count(*) from tb_veiculos where status = 'T' and veiculo ='A'");
            if (conecta.rs.first()) {
                automovel = conecta.rs.getInt("count");
            } else {
                automovel = 0;
            }
            conecta.Desconecta();
            conecta.Conexao(obj_config._url);
            conecta.executaSQL("select count(*) from tb_veiculos where status = 'T' and veiculo ='O'");
            if (conecta.rs.first()) {
                onibus = conecta.rs.getInt("count");
            } else {
                onibus = 0;
            }
            conecta.Desconecta();
            conecta.Conexao(obj_config._url);
            conecta.executaSQL("select count(*) from tb_veiculos where status = 'T' and veiculo ='C'");
            if (conecta.rs.first()) {
                caminhao = conecta.rs.getInt("count");
            } else {
                caminhao = 0;
            }
//                                                                                                                                            Automovel
            JOptionPane.showMessageDialog(null, "Motos           = " + motos + "\n\nAutomovel   = " + automovel + "\n\n"
                    + "Onibus         = " + onibus + "\n\nCaminhão   = " + caminhao, "Estoque", JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Existe\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel imagem;
    private javax.swing.JButton jBtt_alterafoto;
    private javax.swing.JButton jBtt_cancelar;
    private javax.swing.JButton jBtt_editar;
    private javax.swing.JButton jBtt_excluir;
    private javax.swing.JButton jBtt_novo;
    private javax.swing.JButton jBtt_salvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCbx_condicao;
    private javax.swing.JComboBox jCbx_cor;
    private javax.swing.JComboBox jCbx_marca;
    public static javax.swing.JComboBox jCbx_modelo;
    private javax.swing.JComboBox jCbx_porta;
    private javax.swing.JComboBox jCbx_porte;
    private javax.swing.JComboBox jCbx_veiculo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFormattedTextField jFTxt_anoModelo;
    private javax.swing.JFormattedTextField jFTxt_dataFabricacao;
    private javax.swing.JFormattedTextField jFTxt_datacad;
    private javax.swing.JFormattedTextField jFTxt_placa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JButton jRBt_Modelos;
    private javax.swing.JRadioButton jRBt_arC;
    private javax.swing.JRadioButton jRBt_completo;
    private javax.swing.JRadioButton jRBt_compra;
    private javax.swing.JRadioButton jRBt_direcao;
    private javax.swing.JRadioButton jRBt_entrada;
    private javax.swing.JRadioButton jRBt_flex;
    private javax.swing.JRadioButton jRBt_troca;
    private javax.swing.JRadioButton jRBt_vendido_trocado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTable jTbl_Veiculos;
    private javax.swing.JTextField jTxt_chassi;
    private javax.swing.JTextField jTxt_codigo;
    private javax.swing.JFormattedTextField jTxt_lucro;
    private javax.swing.JTextField jTxt_obs;
    private javax.swing.JTextField jTxt_quilometro;
    private javax.swing.JFormattedTextField jTxt_valor_pago;
    private javax.swing.JTextField jTxt_valor_venda;
    private javax.swing.JTextField jTxt_versao;
    // End of variables declaration//GEN-END:variables

    public void limpaCampos() {
        jTxt_codigo.setText("");
        jFTxt_datacad.setText("");
        jTxt_quilometro.setText("");
        jFTxt_dataFabricacao.setText("");
        jFTxt_anoModelo.setText("");
        jTxt_versao.setText("");
        jTxt_chassi.setText("");
        jFTxt_placa.setText("");
        jRBt_completo.setSelected(!true);
        jRBt_flex.setSelected(!true);
        jRBt_direcao.setSelected(!true);
        jRBt_arC.setSelected(!true);
        jTxt_obs.setText("");
        jTxt_valor_pago.setText("");
        jTxt_lucro.setText("");
        jTxt_valor_venda.setText("");
        jRBt_entrada.setSelected(true);
        imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
        fotoAntida = null;

    }

    public void HabilitaDesabilitaCampos(int acao) {

        if (acao == 1) {
            jRBt_compra.setSelected(true);
            jRBt_compra.setEnabled(true);
            jRBt_troca.setEnabled(true);
            jCbx_veiculo.setEnabled(true);
            jCbx_condicao.setEnabled(true);
            jTxt_quilometro.setEnabled(true);
            jFTxt_dataFabricacao.setEnabled(true);
            jFTxt_anoModelo.setEnabled(true);
            jCbx_porte.setEnabled(true);
            jCbx_marca.setEnabled(true);
            jCbx_modelo.setEnabled(true);
            jTxt_versao.setEnabled(true);
            jTxt_chassi.setEnabled(true);
            jFTxt_placa.setEnabled(true);
            jCbx_cor.setEnabled(true);
            jCbx_porta.setEnabled(true);
            jRBt_completo.setEnabled(true);
            jRBt_flex.setEnabled(true);
            jRBt_direcao.setEnabled(true);
            jRBt_arC.setEnabled(true);
            jTxt_obs.setEnabled(true);
            jTxt_valor_pago.setEnabled(true);
            jTxt_lucro.setEnabled(true);
            jBtt_alterafoto.setEnabled(true);
            jRBt_Modelos.setEnabled(true);
        } else {
            jRBt_compra.setEnabled(!true);
            jRBt_troca.setEnabled(!true);
            jCbx_veiculo.setEnabled(!true);
            jCbx_condicao.setEnabled(!true);
            jTxt_quilometro.setEnabled(!true);
            jFTxt_dataFabricacao.setEnabled(!true);
            jFTxt_anoModelo.setEnabled(!true);
            jCbx_porte.setEnabled(!true);
            jCbx_marca.setEnabled(!true);
            jCbx_modelo.setEnabled(!true);
            jTxt_versao.setEnabled(!true);
            jTxt_chassi.setEnabled(!true);
            jFTxt_placa.setEnabled(!true);
            jCbx_cor.setEnabled(!true);
            jCbx_porta.setEnabled(!true);
            jRBt_completo.setEnabled(!true);
            jRBt_flex.setEnabled(!true);
            jRBt_direcao.setEnabled(!true);
            jRBt_arC.setEnabled(!true);
            jTxt_obs.setEnabled(!true);
            jRBt_entrada.setEnabled(!true);
            jRBt_vendido_trocado.setEnabled(!true);
            jTxt_valor_pago.setEnabled(!true);
            jTxt_lucro.setEnabled(!true);
            jBtt_alterafoto.setEnabled(!true);
            jRBt_Modelos.setEnabled(!true);
        }
    }

    public void PreencherCombo(String SQL) {

        conMod.Conexao(obj_config._url);
        conMod.executaSQL(SQL);
        try {
            conMod.rs.first();
            jCbx_modelo.removeAllItems();
            do {
                jCbx_modelo.addItem(conMod.rs.getString("descricao"));
            } while (conMod.rs.next());
        } catch (SQLException ex) {
        }
        conMod.Desconecta();
    }

    public void preencherTabela() {
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código", "Data", "Marca", "Modelo", "Versão", "Placa", "chassi"};
        conecta.Conexao(obj_config._url);
        conecta.executaSQL("select * from tb_veiculos V ,tb_modelos M where M.id_modelo = V.modelo and V.status != 'A'  order by id_veiculo");
        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("id_veiculo"), (validar.formDataDateToStr(conecta.rs.getDate("datacad"))), conecta.rs.getString("marca"), conecta.rs.getString("descricao"), conecta.rs.getString("versao"), conecta.rs.getString("placa"), conecta.rs.getString("chassi")});
            } while (conecta.rs.next());

        } catch (SQLException ex) {

        }
        conecta.Desconecta();
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTbl_Veiculos.setModel(modelo);
        jTbl_Veiculos.getColumnModel().getColumn(0).setPreferredWidth(50);//90
        jTbl_Veiculos.getColumnModel().getColumn(0).setResizable(false);
        jTbl_Veiculos.getColumnModel().getColumn(1).setPreferredWidth(100);//420
        jTbl_Veiculos.getColumnModel().getColumn(1).setResizable(false);
        jTbl_Veiculos.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTbl_Veiculos.getColumnModel().getColumn(2).setResizable(false);
        jTbl_Veiculos.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTbl_Veiculos.getColumnModel().getColumn(3).setResizable(false);
        jTbl_Veiculos.getColumnModel().getColumn(4).setPreferredWidth(190);
        jTbl_Veiculos.getColumnModel().getColumn(4).setResizable(false);
        jTbl_Veiculos.getColumnModel().getColumn(5).setPreferredWidth(100);
        jTbl_Veiculos.getColumnModel().getColumn(5).setResizable(false);
        jTbl_Veiculos.getColumnModel().getColumn(6).setPreferredWidth(192);
        jTbl_Veiculos.getColumnModel().getColumn(6).setResizable(false);
        jTbl_Veiculos.getTableHeader().setReorderingAllowed(false);
        jTbl_Veiculos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTbl_Veiculos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public boolean preencherObjeto() {
        model.setId_veiculo(Integer.parseInt(jTxt_codigo.getText()));
        model.setDataCad((Date) validar.formDataStrToData(jFTxt_datacad.getText()));

        if (jRBt_compra.isSelected()) {
            model.setCompra_venda("C");
        } else {
            model.setCompra_venda("T");
        }
        if (jCbx_veiculo.getSelectedItem() == "Moto") {
            model.setVeiculo("M");
        } else if (jCbx_veiculo.getSelectedItem() == "Automovel") {
            model.setVeiculo("A");
        } else if (jCbx_veiculo.getSelectedItem() == "Micro/Ônibus") {
            model.setVeiculo("O");
        } else if (jCbx_veiculo.getSelectedItem() == "Caminhão") {
            model.setVeiculo("C");
        }

        if (jCbx_condicao.getSelectedItem() == "Novo") {
            model.setCondicao("N");
        } else if (jCbx_veiculo.getSelectedItem() == "Semi") {
            model.setCondicao("S");
        } else {
            model.setCondicao("U");
        }
        if ("".equals(jTxt_quilometro.getText())) {
            JOptionPane.showMessageDialog(null, "Complete o campo quilomentragens", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        model.setQuilomentragem(Integer.parseInt(jTxt_quilometro.getText()));

        if ("  /  /    ".equals(jFTxt_dataFabricacao.getText())) {
            JOptionPane.showMessageDialog(null, "Digite a data de fabricação!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        model.setDataFab((Date) validar.formDataStrToData(jFTxt_dataFabricacao.getText()));

        model.setAnoModelo(jFTxt_anoModelo.getText());
        if (jCbx_porte.getSelectedItem() == "Pequeno") {
            model.setPorte("P");
        } else if (jCbx_porte.getSelectedItem() == "Medio") {
            model.setPorte("M");
        } else {
            model.setPorte("G");
        }
        model.setMarca((String) jCbx_marca.getSelectedItem());
        model.setModelo((String) jCbx_modelo.getSelectedItem());
        model.setVersao(jTxt_versao.getText());
        if (!validar.chassi(jTxt_chassi.getText())) {
            JOptionPane.showMessageDialog(null, "Chassi invalido", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        model.setChassi(jTxt_chassi.getText());
        model.setPlaca(jFTxt_placa.getText());
        model.setCor((String) jCbx_cor.getSelectedItem());
        int porta = Integer.parseInt((String) (jCbx_porta.getSelectedItem()));
        model.setPorta(porta);
        if (jRBt_flex.isSelected()) {
            model.setFlex("T");
        } else {
            model.setFlex("F");
        }
        if (jRBt_direcao.isSelected()) {
            model.setDirecao_hidraulica("T");
        } else {
            model.setDirecao_hidraulica("F");
        }
        if (jRBt_arC.isSelected()) {
            model.setAr_condicionado("T");
        } else {
            model.setAr_condicionado("F");
        }

        model.setObs(jTxt_obs.getText());

        if (("".equals(jTxt_valor_pago.getText()))) {
            JOptionPane.showMessageDialog(null, "O erro no Valor_pago", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        model.setValor_pago(Double.valueOf(jTxt_valor_pago.getText().replaceAll("\\.", "").replaceAll("\\,", ".")));

        jTxt_valor_venda.setText(Fd.format(new BigDecimal(validar.Lucro_Veiculo_Entrada(jTxt_valor_pago.getText(), jTxt_lucro.getText(), obj_config._LucroVeiculoEntrada))));
        if (("".equals(jTxt_valor_venda.getText()))) {
            JOptionPane.showMessageDialog(null, "Complete o campo Valor_pago", "Atenção", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        model.setValor_venda(Double.valueOf(jTxt_valor_pago.getText().replaceAll("\\.", "").replaceAll("\\,", ".")));

        if (jRBt_entrada.isSelected()) {
            model.setSituacao("T");
        } else {
            model.setSituacao("F");
        }
        model.setFoto(jTxt_codigo.getText() + formato);
        return true;
    }

    public void atualizaTabela() {
        limpaCampos();
        conecta.Conexao(obj_config._url);
        conecta.executaSQL("select * from tb_veiculos V,tb_modelos M where V.id_veiculo = '" + jTbl_Veiculos.getValueAt(jTbl_Veiculos.getSelectedRow(), 0) + "'"
                + " and M.id_modelo = V.modelo");
        try {

            conecta.rs.first();
            jTxt_codigo.setText(String.valueOf(conecta.rs.getInt("id_veiculo")));
            jFTxt_datacad.setText(validar.formDataDateToStr(conecta.rs.getDate("datacad")));

            if (conecta.rs.getString("compra_troca").equals("C")) {
                jRBt_troca.setSelected(!true);
            } else if (conecta.rs.getString("compra_troca").equals("T")) {
                jRBt_troca.setSelected(true);
            }

            jCbx_porta.setSelectedItem(conecta.rs.getString("porta"));

            if (conecta.rs.getString("veiculo").equals("M")) {
                jCbx_veiculo.setSelectedItem("Moto");
                jCbx_porta.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"0"}));
                jCbx_porta.setEnabled(!true);
            } else if (conecta.rs.getString("veiculo").equals("A")) {
                jCbx_veiculo.setSelectedItem("Automovel");
            } else if (conecta.rs.getString("veiculo").equals("O")) {
                jCbx_veiculo.setSelectedItem("Micro/Ônibus");
            } else if (conecta.rs.getString("veiculo").equals("C")) {
                jCbx_veiculo.setSelectedItem("Caminhão");
            }

            if (conecta.rs.getString("condicao").equals("N")) {
                jCbx_condicao.setSelectedItem("Novo");
            } else if (conecta.rs.getString("condicao").equals("S")) {
                jCbx_condicao.setSelectedItem("Semi");
            } else if (conecta.rs.getString("condicao").equals("U")) {
                jCbx_condicao.setSelectedItem("Usado");
            }

            if (conecta.rs.getString("condicao").equals("N")) {
                jTxt_quilometro.setText("0");
            } else {
                jTxt_quilometro.setText(conecta.rs.getString("quilomentragem"));
            }

            jFTxt_dataFabricacao.setText(validar.formDataDateToStr(conecta.rs.getDate("datafab")));
            jFTxt_anoModelo.setText(conecta.rs.getString("anomodelo"));

            if ("P".equals(conecta.rs.getString("porte"))) {
                jCbx_porte.setSelectedItem("Pequeno");
            } else if ("M".equals(conecta.rs.getString("porte"))) {
                jCbx_porte.setSelectedItem("Medio");
            } else if ("G".equals(conecta.rs.getString("porte"))) {
                jCbx_porte.setSelectedItem("Grande");
            }
            jCbx_marca.setSelectedItem(conecta.rs.getString("marca"));
            jCbx_modelo.setSelectedItem(conecta.rs.getString("descricao"));
            jTxt_versao.setText(conecta.rs.getString("versao"));

            jTxt_chassi.setText(conecta.rs.getString("chassi"));
            jFTxt_placa.setText(conecta.rs.getString("placa"));
            jCbx_cor.setSelectedItem(conecta.rs.getString("cor"));
            int ok = 0;
            if ("T".equals(conecta.rs.getString("flex"))) {
                jRBt_flex.setSelected(true);
                ok++;
            } else {
                jRBt_flex.setSelected(!true);
            }

            if ("T".equals(conecta.rs.getString("direcao_hidraulica"))) {
                jRBt_direcao.setSelected(true);
                ok++;
            } else {
                jRBt_direcao.setSelected(!true);
            }

            if ("T".equals(conecta.rs.getString("ar_condicionado"))) {
                jRBt_arC.setSelected(true);
                ok++;
            } else {
                jRBt_arC.setSelected(!true);
            }
            if (ok == 3) {
                jRBt_completo.setSelected(true);
            }
            jTxt_obs.setText(conecta.rs.getString("obs"));
            jTxt_valor_pago.setText(Fd.format(new BigDecimal(conecta.rs.getString("valor_pago"))));
            jTxt_valor_venda.setText(Fd.format(new BigDecimal(conecta.rs.getString("valor_venda"))));
            if ("T".equals(conecta.rs.getString("status"))) {
                jRBt_entrada.setSelected(true);
                jRBt_vendido_trocado.setSelected(!true);
            } else {
                jRBt_entrada.setSelected(!true);
                jRBt_vendido_trocado.setSelected(true);
            }
            if (new File("Imagens\\" + conecta.rs.getString("foto")).exists()) {
                URL_Foto = conecta.rs.getString("foto");
                imagem.setIcon(new ImageIcon(new ImageIcon(("Imagens\\" + conecta.rs.getString("foto"))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
            } else {
                imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(validar.preencherFoto((String) jCbx_marca.getSelectedItem()))).getImage().getScaledInstance(475, 307, Image.SCALE_DEFAULT)));
                URL_Foto = "";
            }
            jBtt_novo.setEnabled(false);
            jBtt_salvar.setEnabled(false);
            jBtt_editar.setEnabled(true);
            jBtt_excluir.setEnabled(true);
            jBtt_cancelar.setEnabled(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados do registro!" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
        conecta.Desconecta();
        HabilitaDesabilitaCampos(0);
        jRBt_flex.setEnabled(!true);
    }

    private void cbx() {
        if ((jRBt_flex.isSelected()) && (jRBt_direcao.isSelected()) && (jRBt_arC.isSelected())) {
            jRBt_completo.setSelected(true);
        } else if ((!jRBt_flex.isSelected()) || (!jRBt_direcao.isSelected()) || (!jRBt_arC.isSelected())) {
            jRBt_completo.setSelected(!true);
        }
    }

    private void Movimentacao() {
        if (Movimentacao == 1) {
            ArrayList dados = new ArrayList();
            String[] Colunas = new String[]{"Código", "Veiculo", "Marca", "Modelo", "Versão", "Placa", "chassi"};
            conecta.Conexao(obj_config._url);
            conecta.executaSQL("select * from tb_veiculos V ,tb_modelos M where M.id_modelo = V.modelo and V.status = 'T' order by id_veiculo");
            try {
                conecta.rs.first();

                do {
                    String Veiculo = null;
                    if (conecta.rs.getString("veiculo").equals("M")) {
                        Veiculo = "Moto";
                    } else if (conecta.rs.getString("veiculo").equals("A")) {
                        Veiculo = "Automovel";
                    } else if (conecta.rs.getString("veiculo").equals("M")) {
                        Veiculo = "Micro/Ônibus";
                    } else if (conecta.rs.getString("veiculo").equals("C")) {
                        Veiculo = "Caminhão";
                    }
                    dados.add(new Object[]{conecta.rs.getInt("id_veiculo"), Veiculo, conecta.rs.getString("marca"), conecta.rs.getString("descricao"), conecta.rs.getString("versao"), conecta.rs.getString("placa"), conecta.rs.getString("chassi")});

                } while (conecta.rs.next());

            } catch (SQLException ex) {

            }
            conecta.Desconecta();
            ModeloTabela modelo = new ModeloTabela(dados, Colunas);
            jTbl_Veiculos_venda.setModel(modelo);
            jTbl_Veiculos_venda.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTbl_Veiculos_venda.getColumnModel().getColumn(0).setResizable(false);
            jTbl_Veiculos_venda.getColumnModel().getColumn(1).setPreferredWidth(70);
            jTbl_Veiculos_venda.getColumnModel().getColumn(1).setResizable(false);
            jTbl_Veiculos_venda.getColumnModel().getColumn(2).setPreferredWidth(107);
            jTbl_Veiculos_venda.getColumnModel().getColumn(2).setResizable(false);
            jTbl_Veiculos_venda.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTbl_Veiculos_venda.getColumnModel().getColumn(3).setResizable(false);
            jTbl_Veiculos_venda.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTbl_Veiculos_venda.getColumnModel().getColumn(4).setResizable(false);
            jTbl_Veiculos_venda.getColumnModel().getColumn(5).setPreferredWidth(78);
            jTbl_Veiculos_venda.getColumnModel().getColumn(5).setResizable(false);
            jTbl_Veiculos_venda.getColumnModel().getColumn(6).setPreferredWidth(85);
            jTbl_Veiculos_venda.getColumnModel().getColumn(6).setResizable(false);
            jTbl_Veiculos_venda.getTableHeader().setReorderingAllowed(false);
            jTbl_Veiculos_venda.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            jTbl_Veiculos_venda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        } else if (Movimentacao == 2) {
            ArrayList dados = new ArrayList();
            String[] Colunas = new String[]{"Código", "Marca", "Modelo", "Versão", "Placa", "chassi"};
            conecta.Conexao(obj_config._url);
            conecta.executaSQL("select * from tb_veiculos where status = 'T' order by id_veiculo");
            conMod.Conexao(obj_config._url);
            try {
                conecta.rs.first();

                do {
                    conMod.executaSQL("select * from tb_modelos where id_modelo = " + conecta.rs.getInt("modelo"));
                    conMod.rs.first();
                    dados.add(new Object[]{conecta.rs.getInt("id_veiculo"), conecta.rs.getString("marca"), conMod.rs.getString("descricao"), conecta.rs.getString("versao"), conecta.rs.getString("placa"), conecta.rs.getString("chassi")});

                } while (conecta.rs.next());

            } catch (SQLException ex) {
            }
            conecta.Desconecta();
            ModeloTabela modelo = new ModeloTabela(dados, Colunas);
            jTbl_Veiculos_saida.setModel(modelo);
            jTbl_Veiculos_saida.getColumnModel().getColumn(0).setPreferredWidth(51);
            jTbl_Veiculos_saida.getColumnModel().getColumn(0).setResizable(false);
            jTbl_Veiculos_saida.getColumnModel().getColumn(1).setPreferredWidth(225);
            jTbl_Veiculos_saida.getColumnModel().getColumn(1).setResizable(false);
            jTbl_Veiculos_saida.getColumnModel().getColumn(2).setPreferredWidth(225);
            jTbl_Veiculos_saida.getColumnModel().getColumn(2).setResizable(false);
            jTbl_Veiculos_saida.getColumnModel().getColumn(3).setPreferredWidth(250);
            jTbl_Veiculos_saida.getColumnModel().getColumn(3).setResizable(false);
            jTbl_Veiculos_saida.getColumnModel().getColumn(4).setPreferredWidth(118);
            jTbl_Veiculos_saida.getColumnModel().getColumn(4).setResizable(false);
            jTbl_Veiculos_saida.getColumnModel().getColumn(5).setPreferredWidth(118);
            jTbl_Veiculos_saida.getColumnModel().getColumn(5).setResizable(false);
            jTbl_Veiculos_saida.getTableHeader().setReorderingAllowed(false);
            jTbl_Veiculos_saida.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            jTbl_Veiculos_saida.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        }
    }

}
