/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Murylo
 */
public final class Manual extends javax.swing.JInternalFrame {

    int Manual = 0;

    /**
     * Creates new form Manual
     */
    public Manual() {
        initComponents();
        Manual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anterior = new javax.swing.JButton();
        proximo = new javax.swing.JButton();
        numero = new javax.swing.JLabel();
        imagem = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);

        anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/back.png"))); // NOI18N
        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        proximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/next_1.png"))); // NOI18N
        proximo.setText("Proximo");
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });

        numero.setText("jLabel2");

        imagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Manual.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(460, 460, 460)
                .addComponent(anterior))
            .addGroup(layout.createSequentialGroup()
                .addGap(670, 670, 670)
                .addComponent(proximo))
            .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(620, 620, 620)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anterior)
                    .addComponent(proximo)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        Manual--;
        Manual();
    }//GEN-LAST:event_anteriorActionPerformed

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
        Manual++;
        Manual();
    }//GEN-LAST:event_proximoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel numero;
    private javax.swing.JButton proximo;
    // End of variables declaration//GEN-END:variables

    void Manual() {
        if (Manual <= 0) {

            Manual = 0;
            numero.setText("Página: 1");

            proximo.setEnabled(true);
            anterior.setEnabled(false);
            imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/Imagens/Manual.PNG")).getImage().getScaledInstance(784, 684, Image.SCALE_DEFAULT)));

        } else if (Manual == 1) {

            numero.setText("Página: 2");
            proximo.setEnabled(true);
            anterior.setEnabled(true);

            imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/Imagens/Manual1.PNG")).getImage().getScaledInstance(784, 651, Image.SCALE_DEFAULT)));
        } else if (Manual == 2) {

            numero.setText("Página: 3");
            proximo.setEnabled(true);
            anterior.setEnabled(true);

            imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/Imagens/Manual2.PNG")).getImage().getScaledInstance(784, 684, Image.SCALE_DEFAULT)));
        } else if (Manual >= 3) {

            numero.setText("Página: 4");
            proximo.setEnabled(false);
            anterior.setEnabled(true);

            Manual = 3;
            imagem.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/Imagens/Manual3.PNG")).getImage().getScaledInstance(784, 650, Image.SCALE_DEFAULT)));
        }

    }

}
