/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ModeloTabela;
import Controle.Validacoes;
import Controle.cadastro;
import static Visao.JIFVenda.jTbl_Veiculos_venda;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Murylo César Souza
 */
public class Pesquisa_Veiculos extends javax.swing.JDialog {

    ConectaBanco conecta = new ConectaBanco();

    ConectaBanco conMod = new ConectaBanco();
    Validacoes validar = new Validacoes();
    cadastro obj_config = new cadastro();
    int Pesquisa;

    /**
     * Creates new form Pesquisa_Veiculos
     *
     * @param parent
     * @param modal
     * @param pesquisa
     */
    public Pesquisa_Veiculos(java.awt.Frame parent, boolean modal, int pesquisa) {
        super(parent, modal);
        initComponents();
        Pesquisa = pesquisa;
        obj_config.carregaconfig();

        PreencherCombo("select * from tb_modelos order by descricao");
        if (Pesquisa == 2) {
            jRBt_todos.setEnabled(false);
            jRBt_entrada.setEnabled(false);
            jRBt_saida.setEnabled(false);
            jRBt_entrada.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel111 = new javax.swing.JLabel();
        jCbx_veiculo = new javax.swing.JComboBox();
        jLabel112 = new javax.swing.JLabel();
        jCbx_condicao = new javax.swing.JComboBox();
        jLabel120 = new javax.swing.JLabel();
        jCbx_marca = new javax.swing.JComboBox();
        jLabel121 = new javax.swing.JLabel();
        jCbx_modelo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jRBt_entrada = new javax.swing.JRadioButton();
        jRBt_saida = new javax.swing.JRadioButton();
        jRBt_todos = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pequisa_Veiculo");
        setMinimumSize(new java.awt.Dimension(304, 240));
        setResizable(false);

        jLabel111.setText("Veículo");

        jCbx_veiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Moto", "Automovel", "Micro/Ônibus", "Caminhão" }));
        jCbx_veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbx_veiculoActionPerformed(evt);
            }
        });
        jCbx_veiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCbx_veiculoKeyReleased(evt);
            }
        });

        jLabel112.setText("Condição");

        jCbx_condicao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Novo", "Semi", "Usado" }));

        jLabel120.setText("Marca");

        jCbx_marca.setEnabled(false);
        jCbx_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbx_marcaActionPerformed(evt);
            }
        });

        jLabel121.setText("Modelo");

        jCbx_modelo.setEnabled(false);

        jLabel1.setText("Versão");

        jLabel2.setText("Situação");

        buttonGroup1.add(jRBt_entrada);
        jRBt_entrada.setText("Entrada");

        buttonGroup1.add(jRBt_saida);
        jRBt_saida.setText("Saída");

        buttonGroup1.add(jRBt_todos);
        jRBt_todos.setSelected(true);
        jRBt_todos.setText("Todos");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancela.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel120, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jCbx_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel111, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jCbx_veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel112)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCbx_condicao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel121, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCbx_modelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jRBt_todos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jRBt_entrada)
                        .addGap(18, 18, 18)
                        .addComponent(jRBt_saida, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jCbx_marca, jCbx_modelo, jTextField1});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel111, jLabel120, jLabel121, jLabel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbx_veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel111)
                    .addComponent(jCbx_condicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel112))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbx_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel120))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel121)
                    .addComponent(jCbx_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRBt_entrada)
                    .addComponent(jRBt_saida)
                    .addComponent(jRBt_todos))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCbx_marca, jCbx_modelo, jTextField1});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel111, jLabel120, jLabel121, jLabel2});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCbx_veiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbx_veiculoActionPerformed
        if (jCbx_veiculo.getSelectedItem() == "Todos") {
            jCbx_marca.setEnabled(false);
            jCbx_modelo.setEnabled(false);
        } else {
            jCbx_marca.setEnabled(true);
            jCbx_modelo.setEnabled(true);
            jCbx_marca.setModel(new javax.swing.DefaultComboBoxModel(validar.preencherCampo((String) jCbx_veiculo.getSelectedItem())));
            PreencherCombo("select * from tb_modelos where marca = '" + (String) jCbx_marca.getSelectedItem() + "' order by descricao");
        }
    }//GEN-LAST:event_jCbx_veiculoActionPerformed

    private void jCbx_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbx_marcaActionPerformed

        PreencherCombo("select * from tb_modelos where marca = '" + (String) jCbx_marca.getSelectedItem() + "' order by descricao");
    }//GEN-LAST:event_jCbx_marcaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCbx_veiculoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCbx_veiculoKeyReleased
        if (jCbx_veiculo.getSelectedItem() == "Todos") {
            jCbx_marca.setEnabled(false);
            jCbx_modelo.setEnabled(false);
        } else {
            jCbx_marca.setEnabled(true);
            jCbx_modelo.setEnabled(true);
            jCbx_marca.setModel(new javax.swing.DefaultComboBoxModel(validar.preencherCampo((String) jCbx_veiculo.getSelectedItem())));
        }
    }//GEN-LAST:event_jCbx_veiculoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String SQL, veiculo, Marca, Modelo, condicao = null, situacao;

        if (jCbx_veiculo.getSelectedItem() == "Todos") {
            veiculo = "";
            Marca = "";
        } else if (jCbx_veiculo.getSelectedItem() == "Moto") {
            veiculo = "M";
            Marca = (String) (jCbx_marca.getSelectedItem());
        } else if (jCbx_veiculo.getSelectedItem() == "Automovel") {
            veiculo = "A";
            Marca = (String) (jCbx_marca.getSelectedItem());
        } else if (jCbx_veiculo.getSelectedItem() == "Micro/Ônibus") {
            veiculo = "O";
            Marca = (String) (jCbx_marca.getSelectedItem());
        } else {
            veiculo = "C";
            Marca = (String) (jCbx_marca.getSelectedItem());
        }

        if (jCbx_condicao.getSelectedItem() == "Todos") {
            condicao = "";
        } else if (jCbx_condicao.getSelectedItem() == "Novo") {
            condicao = "N";
        } else if (jCbx_condicao.getSelectedItem() == "Semi") {
            condicao = "S";
        } else if (jCbx_condicao.getSelectedItem() == "Usado") {
            condicao = "U";
        }

        if (jRBt_todos.isSelected()) {
            situacao = "";
        } else if (jRBt_entrada.isSelected()) {
            situacao = "T";
        } else {
            situacao = "F";
        }

        if ((jCbx_modelo.getSelectedItem() == "Todos") || (jCbx_veiculo.getSelectedItem() == "Todos")) {
            Modelo = "";
        } else {
            Modelo = (String) (jCbx_modelo.getSelectedItem());
        }

        if (jCbx_veiculo.getSelectedItem() != "Todos") {
            SQL = "select * from tb_veiculos V ,tb_modelos M where V.veiculo like '%" + veiculo + "%' and V.condicao like '%" + condicao + "%' and "
                    + "V.marca like '%" + Marca + "%' and "
                    + "V.versao  like '%" + jTextField1.getText() + "%' "
                    + "and V.status like '%" + situacao + "%' "
                    + "and M.descricao like '%" + Modelo + "%' "
                    + "and V.modelo = M.id_modelo "
                    + "and V.status != 'A'"
                    + "order by V.id_veiculo";
        } else {
            SQL = "select * from tb_veiculos V ,tb_modelos M where V.veiculo like '%" + veiculo + "%'"
                    + " and V.condicao like '%" + condicao + "%'"
                    + " and V.versao like '%" + jTextField1.getText() + "%'"
                    + " and V.status like '%" + situacao + "%'"
                    + " and V.modelo = M.id_modelo"
                    + " and V.status != 'A'"
                    + " order by V.id_veiculo";
        }
        if (Pesquisa == 1) {
            ArrayList dados = new ArrayList();
            String[] Colunas = new String[]{"Código", "Data", "Marca", "Modelo", "Versão", "Placa", "chassi"};

            conecta.Conexao(obj_config._url);

            conecta.executaSQL(SQL);

            try {
                conecta.rs.first();
                do {
                    String data = (validar.formDataDateToStr(conecta.rs.getDate("datacad")));
                    dados.add(new Object[]{conecta.rs.getInt("id_veiculo"), data, conecta.rs.getString("marca"), conecta.rs.getString("descricao"), conecta.rs.getString("versao"), conecta.rs.getString("placa"), conecta.rs.getString("chassi")});

                } while (conecta.rs.next());

            } catch (SQLException ex) {
                conecta.executaSQL("select * from tb_veiculos V ,tb_modelos M where M.id_modelo = V.modelo and V.status != 'A' order by id_veiculo");

                try {
                    conecta.rs.first();

                    do {
                        String data = (validar.formDataDateToStr(conecta.rs.getDate("datacad")));
                        dados.add(new Object[]{conecta.rs.getInt("id_veiculo"), data, conecta.rs.getString("marca"), conecta.rs.getString("descricao"), conecta.rs.getString("versao"), conecta.rs.getString("placa"), conecta.rs.getString("chassi")});

                    } while (conecta.rs.next());

                    conecta.Desconecta();
                    JOptionPane.showMessageDialog(null, "Pesquisa não encontrada!", "Erro", JOptionPane.ERROR_MESSAGE);
                } catch (SQLException exe) {
                    JOptionPane.showMessageDialog(null, "Erro na Pesquisa!\n\n" + exe, "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }

            conecta.Desconecta();
            ModeloTabela modelo = new ModeloTabela(dados, Colunas);

            JIFVeiculos.jTbl_Veiculos.setModel(modelo);
            JIFVeiculos.jTbl_Veiculos.getColumnModel().getColumn(0).setPreferredWidth(50);
            JIFVeiculos.jTbl_Veiculos.getColumnModel().getColumn(0).setResizable(false);
            JIFVeiculos.jTbl_Veiculos.getColumnModel().getColumn(1).setPreferredWidth(100);
            JIFVeiculos.jTbl_Veiculos.getColumnModel().getColumn(1).setResizable(false);
            JIFVeiculos.jTbl_Veiculos.getColumnModel().getColumn(2).setPreferredWidth(200);
            JIFVeiculos.jTbl_Veiculos.getColumnModel().getColumn(2).setResizable(false);
            JIFVeiculos.jTbl_Veiculos.getColumnModel().getColumn(3).setPreferredWidth(150);
            JIFVeiculos.jTbl_Veiculos.getColumnModel().getColumn(3).setResizable(false);
            JIFVeiculos.jTbl_Veiculos.getColumnModel().getColumn(4).setPreferredWidth(190);
            JIFVeiculos.jTbl_Veiculos.getColumnModel().getColumn(4).setResizable(false);
            JIFVeiculos.jTbl_Veiculos.getColumnModel().getColumn(5).setPreferredWidth(100);
            JIFVeiculos.jTbl_Veiculos.getColumnModel().getColumn(5).setResizable(false);
            JIFVeiculos.jTbl_Veiculos.getColumnModel().getColumn(6).setPreferredWidth(192);
            JIFVeiculos.jTbl_Veiculos.getColumnModel().getColumn(6).setResizable(false);
            JIFVeiculos.jTbl_Veiculos.getTableHeader().setReorderingAllowed(false);
            JIFVeiculos.jTbl_Veiculos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            JIFVeiculos.jTbl_Veiculos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        } else if (Pesquisa == 2) {

            ArrayList dados = new ArrayList();
            String[] Colunas = new String[]{"Código", "Veiculo", "Marca", "Modelo", "Versão", "Placa", "Valor Veiculo"};

            conecta.Conexao(obj_config._url);
            conecta.executaSQL(SQL);

            try {
                conecta.rs.first();
                do {
                    String Veiculo = null;
                    if (conecta.rs.getString("veiculo").equals("M")) {
                        Veiculo = "Moto";
                    } else if (conecta.rs.getString("veiculo").equals("A")) {
                        Veiculo = "Automovel";
                    } else if (conecta.rs.getString("veiculo").equals("M")) {
                        Veiculo = "Micro/Ônibus";
                    } else if (conecta.rs.getString("veiculo").equals("C")) {
                        Veiculo = "Caminhão";
                    }
                    dados.add(new Object[]{conecta.rs.getInt("id_veiculo"), Veiculo, conecta.rs.getString("marca"), conecta.rs.getString("descricao"), conecta.rs.getString("versao"), conecta.rs.getString("placa"), conecta.rs.getString("valor_venda")});

                } while (conecta.rs.next());

            } catch (SQLException ex) {
                conecta.executaSQL("select * from tb_veiculos V ,tb_modelos M where M.id_modelo = V.modelo  and V.status != 'A' order by id_veiculo");

                try {
                    conecta.rs.first();

                    do {
                        String Veiculo = null;
                        if (conecta.rs.getString("veiculo").equals("M")) {
                            Veiculo = "Moto";
                        } else if (conecta.rs.getString("veiculo").equals("A")) {
                            Veiculo = "Automovel";
                        } else if (conecta.rs.getString("veiculo").equals("M")) {
                            Veiculo = "Micro/Ônibus";
                        } else if (conecta.rs.getString("veiculo").equals("C")) {
                            Veiculo = "Caminhão";
                        }
                        dados.add(new Object[]{conecta.rs.getInt("id_veiculo"), Veiculo, conecta.rs.getString("marca"), conecta.rs.getString("descricao"), conecta.rs.getString("versao"), conecta.rs.getString("placa"), conecta.rs.getString("valor_venda")});

                    } while (conecta.rs.next());

                    conecta.Desconecta();
                    JOptionPane.showMessageDialog(null, "Pesquisa não encontrada!", "Erro", JOptionPane.ERROR_MESSAGE);
                } catch (SQLException exe) {
                    JOptionPane.showMessageDialog(null, "Erro na Pesquisa!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }

            conecta.Desconecta();

            ModeloTabela modelo = new ModeloTabela(dados, Colunas);
            jTbl_Veiculos_venda.setModel(modelo);
            jTbl_Veiculos_venda.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTbl_Veiculos_venda.getColumnModel().getColumn(0).setResizable(false);
            jTbl_Veiculos_venda.getColumnModel().getColumn(1).setPreferredWidth(70);
            jTbl_Veiculos_venda.getColumnModel().getColumn(1).setResizable(false);
            jTbl_Veiculos_venda.getColumnModel().getColumn(2).setPreferredWidth(107);
            jTbl_Veiculos_venda.getColumnModel().getColumn(2).setResizable(false);
            jTbl_Veiculos_venda.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTbl_Veiculos_venda.getColumnModel().getColumn(3).setResizable(false);
            jTbl_Veiculos_venda.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTbl_Veiculos_venda.getColumnModel().getColumn(4).setResizable(false);
            jTbl_Veiculos_venda.getColumnModel().getColumn(5).setPreferredWidth(78);
            jTbl_Veiculos_venda.getColumnModel().getColumn(5).setResizable(false);
            jTbl_Veiculos_venda.getColumnModel().getColumn(6).setPreferredWidth(85);
            jTbl_Veiculos_venda.getColumnModel().getColumn(6).setResizable(false);
            jTbl_Veiculos_venda.getTableHeader().setReorderingAllowed(false);
            jTbl_Veiculos_venda.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            jTbl_Veiculos_venda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisa_Veiculos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisa_Veiculos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisa_Veiculos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisa_Veiculos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Pesquisa_Veiculos dialog = new Pesquisa_Veiculos(new javax.swing.JFrame(), true, 0);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCbx_condicao;
    private javax.swing.JComboBox jCbx_marca;
    private javax.swing.JComboBox jCbx_modelo;
    private javax.swing.JComboBox jCbx_veiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRBt_entrada;
    private javax.swing.JRadioButton jRBt_saida;
    private javax.swing.JRadioButton jRBt_todos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public void PreencherCombo(String SQL) {
        conMod.Conexao(obj_config._url);
        conMod.executaSQL(SQL);
        try {
            conMod.rs.first();
            jCbx_modelo.removeAllItems();
            jCbx_modelo.addItem("Todos");
            do {
                jCbx_modelo.addItem(conMod.rs.getString("descricao"));
            } while (conMod.rs.next());
        } catch (SQLException ex) {
        }
        conMod.Desconecta();
    }

    public int buscaCodigoModelo() {
        conMod.Conexao(obj_config._url);
        conMod.executaSQL("select * from tb_modelos where descricao = '" + (String) (jCbx_modelo.getSelectedItem()) + "'");
        try {
            conMod.rs.first();
            int id_modelo = conMod.rs.getInt("id_modelo");

            conMod.Desconecta();
            return id_modelo;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível localizar a modelo cadastrado com este código!" + (String) (jCbx_modelo.getSelectedItem()));

        }
        conMod.Desconecta();
        return 0;
    }

}
